### ISSUE TITLE
Ensure 'hostname' is not 'localhost' by default

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#100]
Install will fail if the 'localhost' is used as the hostname during setup. If this is the only hostname detected, it should not be provided as the default during setup.

**Comment by mbaser** [comment]
I am not sure if you mean:
![screenshot_2018-08-07_01-58-09](https://user-images.githubusercontent.com/6398752/43745062-98336a7e-99e5-11e8-8660-7baef7611ea1.png)

**Comment by mbaser** [comment]
commits 765a862b7d04c8ade9d1d0434261840512f55d0d and e2ce84795d10230483ea5d6655e0aebb59215352 closed this issue
