### ISSUE TITLE
Failed to install gluu-server 4.5.2 on rhel9 and suse 15.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/community-edition-setup#1008]
![Screenshot from 2023-08-21 11-40-42](https://github.com/GluuFederation/community-edition-setup/assets/34593983/994914c5-c8ba-4a46-89f1-ac8810340697)
we Faced error when downloading gluu-server using gluu-install.py.

**Comment by devrimyatar** [comment]
@MohitMaliFtechiz
* On SUSE Execute `sudo SUSEConnect -p PackageHub/15.4/x86_64`
* On RHEL: install `unzip`
