### ISSUE TITLE
CE 2.4.2-1-3 rpm package lacks json/simplejson libraries

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/community-edition-setup#103]
Full package name: **gluu-server-2.4.2-1-3.centos7.x86_64** (corrected my mistake, it's not a src package, but a stable release)

Not sure is it issue or its removal was planned. My Ubuntu 2.4.2-1-1 instance still contains them under `/opt/jython/Lib/json`. I believe some of our stock custom scripts may still use it for parsing configuration files. I had an issue with running CR script which (without any need for this) tried to import this library, here is the result:

```
2016-03-16 18:46:47,870 INFO  [org.xdi.service.PythonService] (pool-5-thread-9) Debugging: json include - 
2016-03-16 18:46:47,871 INFO  [org.xdi.service.PythonService] (pool-5-thread-9)  No module named json
2016-03-16 18:46:47,885 INFO  [org.xdi.service.PythonService] (pool-5-thread-9) Debugging: simplejson include - 
2016-03-16 18:46:47,885 INFO  [org.xdi.service.PythonService] (pool-5-thread-9)  No module named simplejson
```
So if its location was simply changed we'll need to verify that all scripts which need it are functioning.

**Comment by adrian-gluu** [comment]
this is wrong! why are you trying src.rpm instead of .rpm?

**Comment by aliaksander-samuseu** [comment]
Adrian, I'm installing it the usual way, with yum install from repo. I just copypasted the name of the package as dpkg displays it when list of installed packages is queried.

**Comment by aliaksander-samuseu** [comment]
Here is the full output:

```
# rpm -qi gluu-server-2.4.2
Name        : gluu-server-2.4.2
Version     : 1
Release     : 3.centos7
Architecture: x86_64
Install Date: Tue 15 Mar 2016 06:37:38 PM CDT
Group       : Gluu
Size        : 1706673260
License     : MIT
Signature   : RSA/SHA1, Mon 07 Mar 2016 04:39:26 PM CST, Key ID 5b76117e0544ba38
Source RPM  : gluu-server-2.4.2-1-3.centos7.src.rpm
Build Date  : Mon 07 Mar 2016 02:16:41 PM CST
Build Host  : pkg-rpm2.gluu.org
Relocations : (not relocatable)
Packager    : Gluu support <support@gluu.org>
Vendor      : Gluu, Inc.
Summary     : Gluu chroot CE environment

```

**Comment by mzico** [comment]
@adrian-gluu: Adrian, if we follow public CentOS7 doc ( https://gluu.org/docs/deployment/centos7/)..... this 'src.rpm' is coming. IMO, if that's not stable, shouldn't we point public doc which can pull stable release ( i.e. only rpm )

**Comment by adrian-gluu** [comment]
I'm using the same jython for both deb and rpm /opt/jython/ 
Can you double check this issue?Yura did you get this error?

**Comment by aliaksander-samuseu** [comment]
I used this command to verify my suspicion (after I spotted the include error in script log when it failed):
find /opt/jython/Lib/ -ipath "*json*"

For the latest CentOS7 package (1-3) it shows nothing. For 2.4.2-1-1 deb instance it shows a lot of subfolders.

**Comment by yurem** [comment]
`
su - tomcat
 /opt/jython/bin/jython --version
Jython 2.7.0
`

**Comment by yurem** [comment]
size of /opt/jython-2.7.0 in Cent OS 6.7 CE 2.4.2 is 172 575 884

**Comment by yurem** [comment]
Adrian, can you install your rpm and check if the size and jython version are is ok?

**Comment by adrian-gluu** [comment]
just fixed jython:
http://repo.gluu.org/centos/7/gluu-server-2.4.2-1-4.centos7.x86_64.rpm

**Comment by yurem** [comment]
We uses jython versio which provides this library
