### ISSUE TITLE
Use the host's DNS, not google dns

### ISSUE THREAD

**Issue by JohnTheodore** [GluuFederation/community-edition-setup#104]
We deployed gluu-server, but our nodes don't have Internet access. Though we obviously have working dns. It makes more sense for /etc/resolv.conf in the chroot to match what is in /etc/resolv.conf on the host. versus picking google dns.

**Comment by yurem** [comment]
You can log into gluu-server and change DNS setting according to your requirements. Please open support ticket here support.gluu.org if needed

**Comment by adrian-gluu** [comment]
I think google DNS are the best option because they are unbreakable, in case your ISP dns goes down google dns will still up and our app witll continue working

**Comment by JohnTheodore** [comment]
This issue was mostly for the default setting, I know I can change it.

I'm assuming more agency to the person installing the software. If they setup their DNS a certain way, overriding them with google dns seems unnecessary. Even if Google DNS is more stable than their incumbent DNS.

For most people in the world, going to DNS servers in California is very high latency. Normally you'd want DNS to be local and close (which it is typically on the host).

Also in our case, having DNS queries for an application go out the Internet can be a security risk.

**Comment by adrian-gluu** [comment]
Hello John you can open a ticket in support.gluu.org and also if you don't want to use google DNS you can use your own editing the the /etc/resolv.conf file.

Thanks!
