### ISSUE TITLE
Use one ox-ldap.properties file across all applications

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#105]
It's idea for discussion.Now we have 4 xyz-ldap.properties files:
oxauth-ldap.properties
oxtrust-ldap.properties
oxidp-ldap.properties
oxasimba-ldap.properties

The next one will be:
oxcas-ldap.properties

In these all applications we uses same LDAP layer (code and backend).

I offer by default to install only one: ox-ldap.properties

After that we only need to apply small update to these applications. It should load data from  ox-ldap.properties if there is no application specific ldap configuration.

**Comment by mzico** [comment]
+1

**Comment by yurem** [comment]
oxIdp and oxCas attempts to read [ox-ldap.properties](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/ox-ldap.properties) first

We need to improve oxAuth/oxTrust/oxAsimba now

**Comment by yurem** [comment]
Applications should use next logic:
    Check oxzyx-ldap.properties availability.
    Read ox-ldap.properties if isn't.
    Delete oxzyx-ldap.properties creation from the installer.

Sample method: https://github.com/GluuFederation/oxTrust/blob/master/openid-auth-client/src/main/java/org/gluu/oxauth/client/conf/Configuration.java#L111

Code which uses it String ldapConfigurationFileName = "oxzyx-ldap.properties";
FileConfiguration fileConfiguration = loadLdapConfiguration(ldapConfigurationFileName, false);
if (fileConfiguration == null) {
ldapConfigurationFileName = "ox-ldap.properties";
fileConfiguration = loadLdapConfiguration(ldapConfigurationFileName, true);
}

**Comment by yurem** [comment]
Fixed
