### ISSUE TITLE
Infinite certificate error loop from tomcat when installing legitimate certificates

### ISSUE THREAD

**Issue by JohnTheodore** [GluuFederation/community-edition-setup#106]
I followed this guide: https://www.gluu.org/docs/deployment/ubuntu/ .. and everything works fine. Once I replace httpd.cert and httpd.key with my own legitimate certificate, I have a redirect loop. I can load the login page, and my cert is working (the green lock shows, etc, so it's legit). Though after I click login.. I get a redirect loop.

 here is https://gist.github.com/JohnTheodore/ac138c62b2f5c151b466 with a full log loop cycle in /opt/tomcat/logs/wrapper.log. That pattern repeats for as long as my web browser is trying to login.

I tried setting server.xml to use http, since there is no need for tomcat to use ssl since the client (apache2) and server (tomcat) live on the same host. but I get the same error from the wrapper.log.

Is there any documentation on how to fix this or set this up? I couldn't find docs for this area on the website.

**Comment by mzico** [comment]
You also need to update java keystore ( cacerts ). Check [this](https://support.gluu.org/other/unable-to-login-after-updating-cert-and-key-files-2409) out. And feel free to open ticket in our support portal: https://support.gluu.org

**Comment by JohnTheodore** [comment]
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, support@gluu.org and inform them of the time the error occurred, and anything you might have done that may have caused the error.

**Comment by JohnTheodore** [comment]
hmm, I can't register or login either. Is the support webapp broken? when I get directed to idp.gluu.org it just hangs until I 500

**Comment by willow9886** [comment]
Sorry, John. It's a really old IDP. We're in the process of upgrading. Let me restart OpenDJ and that should do the trick.

**Comment by JohnTheodore** [comment]
@willow9886 I'm still getting a 500. also this page isn't index by google. I would have used the google cache if it was.

**Comment by willow9886** [comment]
OK it should be up now.

**Comment by JohnTheodore** [comment]
Now I get "You are not autorized to see requested page!", note the spelling error also.

I'm clicking this link: https://support.gluu.org/other/unable-to-login-after-updating-cert-and-key-files-2409

**Comment by willow9886** [comment]
This is a private ticket from one of our customers... perhaps it was at one point public, but they added private details and decided to make the whole ticket private.

**Comment by JohnTheodore** [comment]
Can you copy and paste the relevant bits into this thread?

**Comment by willow9886** [comment]
Yea, let me try to summarize:

- Better to use a specific CN than wildcard cert.
- Video of Zico [performing the cert update](https://www.youtube.com/watch?v=0Ba8i7jbJPY&feature=youtu.be).
- You must update the key in `/etc/pki/java` directory.
- The keystore password is: changeit
- There's currently no way to set certificates at installation time


Hopefully that helps. Let us know if you need additional info. 

Thanks for your patience.
