### ISSUE TITLE
fix(comminity-edition-setup): Upgrade script not working.

### ISSUE THREAD

**Issue by mmrraju** [GluuFederation/community-edition-setup#1061]
[Ticket-11989](https://support.gluu.org/upgrade/11989/facing-issue-with-ugrade-script/)

Here Gluu Server upgrade [scripts](https://gluu.org/docs/gluu-server/4.5/upgrade/#offline-upgrade-from-4x-to-450) not working.
Getting  error `Not Found` 404 for some url
like `https://raw.githubusercontent.com/GluuFederation/gluu-snap/master/facter/facter `

![Screenshot from 2024-11-11 22-17-09](https://github.com/user-attachments/assets/1d029cd7-172c-4534-8fc0-f2d73b492ef8)

**Comment by akhina-gluu** [comment]
Do we have any update on this

**Comment by mmrraju** [comment]
Yes, issue is resolved. https://github.com/GluuFederation/gluu4/pull/22

I've updated comment in ticket.
