### ISSUE TITLE
Can't apply ACL rules to OpenDJ 3

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#108]
Current setup supports OpenDJ 4. There is working example: ce-dev.gluu.org
But, there is one error in log:
09:11:12 03/25/16 The value
(targetattr!="userPassword||authPassword||changes||changeNumber||changeType||changeTime||targetDN||newRDN||newSuperior||deleteOldRDN||targetEntryUUID||changeInitiatorsName||changeLogCookie||includedAttributes")(version
3.0; acl "Anonymous read access"; allow (read,search,compare)

We need to find if statement to setup.py to run right command for OpenDJ 4.

**Comment by yurem** [comment]
More info from setup.log
`
09:11:09 03/25/16 Running: /bin/su ldap -c cd /opt/opendj/bin ;  /opt/opendj/bin/dsconfig --trustAll --no-prompt --hostname localhost --port 4444 --bindDN "cn=directory manager" --bindPasswordFile /home/ldap/.pw set-access-control-handler-prop --remove global-aci:'(targetattr!="userPassword||authPassword||changes||changeNumber||changeType||changeTime||targetDN||newRDN||newSuperior||deleteOldRDN||targetEntryUUID||changeInitiatorsName||changeLogCookie||includedAttributes")(version 3.0; acl "Anonymous read access"; allow (read,search,compare) userdn="ldap:///anyone";)'
09:11:12 03/25/16 The value
(targetattr!="userPassword||authPassword||changes||changeNumber||changeType||changeTime||targetDN||newRDN||newSuperior||deleteOldRDN||targetEntryUUID||changeInitiatorsName||changeLogCookie||includedAttributes")(version
3.0; acl "Anonymous read access"; allow (read,search,compare)
userdn="ldap:///anyone";) for the global-aci property does not exist
`

**Comment by nynymike** [comment]
I don't see why we need anonymous access at all. We should open an issue with FR just to be helpful though and let them know.

**Comment by yurem** [comment]
Fixed
