### ISSUE TITLE
Package gluu-server-2.4.2-1-2.centos6.x86_64.rpm is not signed

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#109]
CentOS: 6.7
Doc: https://gluu.org/docs/deployment/centos/

![notsigned](https://cloud.githubusercontent.com/assets/7156097/14067832/2d1b1920-f434-11e5-8061-1ca67aa141d9.png)

**Comment by adrian-gluu** [comment]
just re signed again

**Comment by pmmenzel** [comment]
This is happening again with 2.4.3 #133
