### ISSUE TITLE
Use default IP in setup.py when using setup.properties file

### ISSUE THREAD

**Issue by tecoholic** [GluuFederation/community-edition-setup#111]
setup.py shows the system IP address and domain name when doing a fresh install. For e.g.,

```
Enter IP Address [159.203.xx.xx] : 
Enter hostname [localhost] : gluu.example.com
```

But when using a `setup.properties` file when migrating between versions, it doesn't have a default.

```
Installing Gluu Server...
For more info see:
  ./setup.log  
  ./setup_error.log
** All clear text passwords contained in ./setup.properties.last.

IP address :
...
```
It would be nice to have the default just like when we are doing a fresh install.

**Comment by nynymike** [comment]
We're going to address this in 2.4.4. For now, just edit the properties file for the new server.

**Comment by ganesh-at-wiw** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/3545304ff83c3ddd62bbbb9983cfcd7beaf10d57#diff-2eeaed663bd0d25b7e608891384b7298

Above are the changes in setup.py to cover your suggestion.
