### ISSUE TITLE
Install 3-rd party dependecies during setup

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#115]
Right now setup.py is mature tool to install CE

In creates /idp structure from scratch, extract Shib templates from oxTrust.war, prepare base folders structure.

In addition we can do next to avoid bugs during chroot creating/upgrade and speed up this process:
1) Remove /opt/apache-tomcat-7.0.65 folder and put source zip into /opt/dist
2) Remove /opt/jython-2.7.0 folder and put source zip into /opt/dist
3) Remove /opt/opendj folder and put source zip into /opt/dist
4) Improve installer to unpack/install points 1-3 during setup. We need to create new method simular to [install_saml](https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L1139)

**Comment by ganesh-at-wiw** [comment]
Okay, tomcat procedure is ready.
Will add others.

**Comment by ganesh-at-wiw** [comment]
Jython procedure is ready.
going to work on opendj now.

**Comment by ganesh-at-wiw** [comment]
Prepared opendj as well.
Created new branch install_procedures_ganesh.
Next will be the creation of packages.

**Comment by yurem** [comment]
I've merged this into master.

Now we have mach easier approach to update tomcat/jyton/opendj in all  supported OS.
Also this should help with new chroot development.
