### ISSUE TITLE
RHEL 6.7 CE 2.4.3 packagin issues

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#118]
RHEL 6.7: Uncomment 2 lines in postinstall regading /tmp/user.list and /tmp/group.list

RHEL 6.7: Make sure that next files in /opt/gluu-server-2.4.3/tmp confrorms OS: group.list, user.list, system_group.list, system_user.list, profile

**Comment by yurem** [comment]
https://github.com/GluuFederation/community-edition-setup/issues/116

**Comment by adrian-gluu** [comment]
fixed:
http://repo.gluu.org/centos/testing/gluu-server-2.4.3-1-2.centos6.x86_64.rpm
