### ISSUE TITLE
RHEL 7.2 CE 2.4.3 packaging issues

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#119]
1) RHEL 7.2: OpenDj 2.6 -> OpenDJ 3.0

2) RHEL 7.2: Add check_ssl command

3) RHEL 7.2: Make sure that next files in /opt/gluu-server-2.4.3/tmp confrorms OS: group.list, user.list, system_group.list, system_user.list, profile

**Comment by adrian-gluu** [comment]
Just fixed on this one
http://repo.gluu.org/centos/7/gluu-server-2.4.3-1-2.centos7.x86_64.rpm
