### ISSUE TITLE
chroot environment should pull /etc/resolv.conf from actual host

### ISSUE THREAD

**Issue by zeroluck** [GluuFederation/community-edition-setup#121]
As referenced in https://support.gluu.org/installation/cant-resolve-dns-names-inside-chroot-2294 when you install gluu-server on CentOS, the DNS server is hardcoded to 8.8.8.8 (google) within the chroot environment. This doesn't work in some environments. It would be nice if /etc/resolv.conf was synced with the actual host or at least pulled from the actual host OS on creation.

The referenced ticket was from gluu-server24, but I just installed gluu-server-2.4.2 and it still has 8.8.8.8 hardcoded into it.

**Comment by yurem** [comment]
Fixed. CE 3.0.0 do this in 2 places:

1. On package install

2. On CE startup
