### ISSUE TITLE
Deploy bcprov-jdk16-1.46.jar into tomcat_home/endorsed

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#122]
The solution should depends on method of resolving [this](https://github.com/GluuFederation/oxAuth/issues/205) issue

**Comment by dmogn** [comment]
Can we upgrade bcprov-jdk16-1.46.jar to latest BC version? 
Shib IDP3 needs v1.53.
I found that replacement bcprov-jdk16-1.46.jar with bcprov-jdk15on-154.jar works well.

**Comment by yurem** [comment]
We uses bcprov-jdk15on-154.j now
