### ISSUE TITLE
Debian 8.4 support

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#123]
I've reviewed current CE 2.4.3 for Debian 8.4. It's ready to release by 80%

Here are problems:
1) Missing fodler /opt/gluu-server-2.4.3/sys/class/net/lo
2) Missing folder /opt/gluu-server-2.4.3/lib/modules
3) Replace /opt from other up to date CE (CentOS 6.7 or 7.0)
4) Copy /tmp/group.list and /tmp/user.list from other up to date CE
5) Regenerate and review files /tmp/system_group.list /tmp/system_user.list Please, don't copy from other CE. Every OS has own folder and permissions structure
6) Update setup.py to detect debian properly
7) Prepare simular to https://github.com/GluuFederation/community-edition-setup/blob/master/templates/httpd_2.4.conf apache2.conf for Debian
8) Install/enable/disable required apache modules.
9) Run fetch source to get latest dists.

@adrian-gluu You can do points 1-5 and 8-9
@ganesh-at-wiw We need to asks you to resolve point 7, Adrian, can give URL to test package
@yurem Please fix point 6

**Comment by yurem** [comment]
10)  dpkg -r gluu-server-2.4.3 don't stop gluu-server!!!

**Comment by yurem** [comment]
11) /opt/gluu-server-2.4.3/dev contains a loot of garbage. Please check what we have in chroot CentOS 7.0 folder.

**Comment by adrian-gluu** [comment]
sorted  1-5 and 8-9 and 10-11
am ready to rebuild the pkg please let me know when i can run fetch_sources and rebuild the pkg

**Comment by adrian-gluu** [comment]
@yurem why we cannot use the same as ubuntu-14.04, apache 2 in debian 8 and ubuntu 16.04 is pretty much the same as in our old ubuntu deb pkg:
@ganesh-at-wiw We need to asks you to resolve point 7, Adrian, can give URL to test package

**Comment by adrian-gluu** [comment]
@yurem 
i think for this 2 steps:
6) Update setup.py to detect debian properly
7) Prepare simular to https://github.com/GluuFederation/community-edition-setup/blob/master/templates/httpd_2.4.conf apache2.conf for Debian

we can use our ubuntu 14.04 approach

**Comment by yurem** [comment]
Tasks for new iteration:
1. Missing /var/run/tomcat
2. Remove /tmp.new
3. Clean up /tmp/system_group.list and /tmp/system_user.list There is duplicity and extra space in each line
4. Apply Ganesh changes
Ganesh Dutt Sharma: few modifications for Debian new version CE
Ganesh Dutt Sharma: 1. a2enmod headers
Ganesh Dutt Sharma: 2. a2dismod antiloris
Ganesh Dutt Sharma: 3. a2enmod proxy
Ganesh Dutt Sharma: 4. a2enmod ssl
5. Fetch sources again
6. apt-get clean all inside chroot
7. Remove /root/libapache2-mod-antiloris_0.4-1_amd64.deb And uninstall it if you installed it. We ar enot using it.
8. Rebuild deb

**Comment by adrian-gluu** [comment]
ok i added all those fixes into this one:
http://repo.gluu.org/debian/pool/main/testing/gluu-server-2.4.3_1-3~Db8jessie_amd64.deb

**Comment by yurem** [comment]
1. Missing postinstall script. Please, copy it from ubuntu pkg.
2. Review all other package scripts... Compare them with Ubuntu packages scripts
3. Remove extra space at the end of each line in  /tmp/system_group.list and /tmp/system_user.list 
4. Run fetch_source for 2.4.3 target. There is no latest setup in this build.
5. Rebuild deb

**Comment by adrian-gluu** [comment]
sorted all the steps in this one:
http://repo.gluu.org/debian/pool/main/testing/gluu-server-2.4.3_1-4~Db8jessie_amd64.deb

**Comment by yurem** [comment]
It's almost ready. We need to rebuild it again with fetch-sources to include updated setup. This update contains fixes for path to cacerts and changing hostame in Debian 8.4

Also we need to apply attached patch
[optimize_perm.zip](https://github.com/GluuFederation/community-edition-setup/files/248389/optimize_perm.zip)
Unzip it to /tmp and run patch -p1 < optimize_perm.diff

**Comment by adrian-gluu** [comment]
http://repo.gluu.org/debian/pool/main/testing/gluu-server-2.4.3_1-6~Db8jessie_amd64.deb
