### ISSUE TITLE
Remove duplicate apache conf file

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#124]
Currently there are 2 gluu conf apache files. I think in order to simplify setup we should keep only one. Can we remove https_gluu_2.4.conf and update setup.py? Are the same? Here is diff:
    --- https_gluu.conf	Thu Apr 14 21:26:22 2016
    +++ https_gluu_2.4.conf	Thu Apr 14 21:26:22 2016

    @@ -1,3 +1,5 @@
    +# for Apache 2.4.*
    +
     <VirtualHost  %(ip)s:80>
             ServerName %(hostname)s
             Redirect  / https://%(hostname)s/
    @@ -10,9 +12,9 @@
     
             LogLevel warn
             SSLEngine on
     -        SSLProtocol all -SSLv2 -SSLv3 +TLSv1.2 +TLSv1.1 +TLSv1
     +        SSLProtocol -ALL +TLSv1
              SSLHonorCipherOrder On
     -        SSLCipherSuite ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:DHE-RSA-AES128-SHA256:DHE-DSS-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES128-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK
     +        SSLCipherSuite EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA+SHA384:EECDH:EDH+aRSA:HIGH:!MEDIUM
              SSLCertificateFile %(httpdCertFn)s
              SSLCertificateKeyFile %(httpdKeyFn)s
 
     @@ -35,7 +37,6 @@
              <Location /oxauth>
                      ProxyPass ajp://localhost:8009/oxauth retry=5 disablereuse=On
                      ProxyPassReverse ajp://localhost:8009/oxauth
     -                Header set Access-Control-Allow-Origin "*"
                      Order allow,deny
                      Allow from all
              </Location>

**Comment by ganesh-at-wiw** [comment]
Yura I think this is for apache2.2 vs 2.4.

**Comment by yurem** [comment]
yes,both files looks very similar. Why we need to 2 files?

**Comment by ganesh-at-wiw** [comment]
Both work fine at CentOS 7.2 and Ubuntu 16.04.
So, removing the file https_gluu_2.4.conf  which is unused.
