### ISSUE TITLE
Please add attributes and scope for imap connection

### ISSUE THREAD

**Issue by dollar007** [GluuFederation/community-edition-setup#127]
I think we should define one LDAP attribtue called `gluuIMAPData` which contains a JSON:

```
{
 "imapusername": "foobar@acme.com",
 "imaphost": "mail.acme.com",
 "imapport": "993",
 "useSSL": "true",
 "imapPassword": {encryptedString: "XBik468/7YKd4jN84scIH+x5hw==", 
                              "cipher": "blowfish",
                              "mode": "CTR"
}

```

There is a good online [tool](http://codebeautify.org/encrypt-decrypt) I found which has a number of two-way encryption algorithms.  We need to find an algorithm where we have compatible libraries for both Java and php. 

OpenID Connect scope (this should NOT be a default scope!!!):
          'name' : 'gluuIMAPData' ,
          'Description' : 'This data has information about your imap connection.',
          'Claims' :  ['imapData']

**Comment by yurem** [comment]
In order to make right decision about this can you add more information to this issue.

1) Is it will be part of CE or we need this only for one specific instance?
2) Which application requests this scope?

**Comment by yurem** [comment]
I will add them to 2.4.4

**Comment by willow9886** [comment]
@yurem we need this updated in order to use our roundcube oxd plugin.. any chance we can get an earlier fix for this?

**Comment by nynymike** [comment]
These attributes should be prefixed either "gluu" or "ox" if they are our attributes.

**Comment by nynymike** [comment]
I'm assigning this to shekhar. We need to add the attribute to the opendj schema, we need to add it to gluuPerson objectclass, and we need to update the template attributes.ldif

**Comment by willow9886** [comment]
@shekhar16 any update on this?

**Comment by shekhar16** [comment]
it is already done.
https://github.com/GluuFederation/oxTrust/issues/253

**Comment by yurem** [comment]
Fixed in https://github.com/GluuFederation/community-edition-setup/commit/74096d1d54615d07969a6f62a1dc98e7eae053d4
