### ISSUE TITLE
Ubuntu 16.04 support

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#129]

**Comment by yurem** [comment]
Setting up gluu-server-2.4.3 (1-1~xenial+Ub16.04) ...
dpkg: error processing package gluu-server-2.4.3 (--install):
 subprocess installed post-installation script returned error exit status 126
In Ubuntu 16.04
> sr/sbin/chroot /opt/gluu-server-2.4.3
> /usr/sbin/chroot: failed to run command ‘/bin/bash’: Permission denied

Also, @adrian-gluu are /tmp/system_(user/group) files from Ubuntu 16.04?

**Comment by adrian-gluu** [comment]
here is why:
/usr/sbin/chroot /opt/gluu-server-2.4.3 /bin/su - root -c '/tmp/user.list'
/usr/sbin/chroot: failed to run command ‘/bin/su’: Permission denied
it looks like chroot cannot execute su am not sure how to fix that yet but i found what is causing it

**Comment by yurem** [comment]
Done
