### ISSUE TITLE
Isn't our default setting for amount of memory allocated for Tomcat outdated?

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/community-edition-setup#132]
It's currently still on 1.5Gb, AFAICR, what probably was enough for 2.3.x instances, but clearly isn't for 2.4.x

Shouldn't we rise it to at least 3GB now? I've seen several tickets in which people were reporting issues with services failing to start and in the end it became clear that's because they simply left Tomcat's allocations at default value when they were running setup.py, assuming that the fact it's a default should mean it's okay to use it for a test installation.

**Comment by nynymike** [comment]
Yes, I was thininking the same. Let's make the default 3GB, which would leave 1GB for LDAP.
