### ISSUE TITLE
Cron jobs don't start inside of the container of 2.4.3 CE deb packages

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/community-edition-setup#134]
Environment: Ubuntu 14.04, gluu-server-2.4.3-1.4

To reproduce:

You may try to check logs of the cron job running logmanager script that is already there from the beginning at `/opt/gluu/logs/logmanager.log`, or create a simple test job with `# crontab -e` like that:

```
* * * * * /bin/touch /var/log/cronworks
```

and check whether this file is created

Here is [card in Trello](https://trello.com/c/at7onW4b/251-issue-with-no-cron-jobs-installed-through-crontab-running-in-2-4-3-ubuntu-containers) for the issue. Ganesh and me have checked for a bunch of possible usual causes of cron job failures we have found on the internet, but couldn't found a way to fix it.

**Comment by adrian-gluu** [comment]
did you check if the cron service is running?
/etc/init.d/cron or service cron status???

**Comment by adrian-gluu** [comment]
also are you trying to run this form inside of the chroot or from the outside?
if this is an issue on the chroot did you check it the host outside of the chroot?
please confirm that

**Comment by aliaksander-samuseu** [comment]
@adrian-gluu 

Yes, we've tried to restart service many times, daemon is shown in pgrep's and ps's output, we've checked permissions on files, the theory that root user may have been locked due to password expiration and other causes you can find in google - nothing of that worked
```
/etc/init.d/cron status
Rather than invoking init scripts through /etc/init.d, use the service(8)
utility, e.g. service cron status

Since the script you are attempting to invoke has been converted to an
Upstart job, you may also use the status(8) utility, e.g. status cron
cron start/running, process 2025
```

**Comment by aliaksander-samuseu** [comment]
Yes, the issue is only inside of chroot, cron works outside (we actually had to set the cronjob for cluster outside of the container as a temporal measure for one of our custmers)

**Comment by adrian-gluu** [comment]
I will dig about it, but i don't have to much clue about it

**Comment by aliaksander-samuseu** [comment]
Hi, @adrian-gluu 

I'm now observing the same issue in gluu-server-2.4.4-1-1.centos6.rpm package installed on CentOS 6.7 We probably should give it another look. That also means that our logmanager script won't be running

**Comment by willow9886** [comment]
Closing.
