### ISSUE TITLE
FileNotFoundException: WEB-INF/lib/oxtrust-configuration-2.4.3-SNAPSHOT.jar

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/community-edition-setup#135]
From latest setup.py [master]:

17:55:34 06/07/16 Unpacking oxtrust-configuration.jar from identity.war...
17:55:34 06/07/16 Created dir: /opt/dist/tmp_identity
17:55:34 06/07/16 Running: /usr/bin/jar xf /opt/tomcat/webapps/identity.war WEB-INF/lib/oxtrust-configuration-2.4.3-SNAPSHOT.jar
17:55:34 06/07/16 Unpacking oxtrust-configuration.jar...
17:55:34 06/07/16 Running: /usr/bin/jar xf WEB-INF/lib/oxtrust-configuration-2.4.3-SNAPSHOT.jar
17:55:35 06/07/16 java.io.FileNotFoundException: WEB-INF/lib/oxtrust-configuration-2.4.3-SNAPSHOT.jar (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at sun.tools.jar.Main.run(Main.java:260)
        at sun.tools.jar.Main.main(Main.java:1231)

**Comment by dmogn** [comment]
Maybe early 2.4.4 for developers will solve it.

**Comment by dmogn** [comment]
Still exists in the 2.4.4 Beta.

**Comment by yurem** [comment]
You should put into CE oxtrust and setup with same version number

**Comment by yurem** [comment]
In latest setup.py:

```
self.oxVersion = '2.4.4-SNAPSHOT'
self.githubBranchName = 'master'
```

Hence oxtrust.war should have 2.4.4-SNAPSHOT version

There is no this bug in CE 2.4.4 beta2

**Comment by yurem** [comment]
We can make setup.py smarter and use file pattern:  WEB-INF/lib/oxtrust-configuration-*.jar

**Comment by dmogn** [comment]
>> use file pattern: WEB-INF/lib/oxtrust-configuration-*.jar

07:23:40 07/04/16 Unpacking oxtrust-configuration.jar from identity.war...
07:23:40 07/04/16 Created dir: /opt/dist/tmp_identity
07:23:40 07/04/16 Running: /usr/bin/jar xf /opt/tomcat/webapps/identity.war WEB-INF/lib/oxtrust-configuration-*.jar
07:23:40 07/04/16 Unpacking oxtrust-configuration.jar...
07:23:40 07/04/16 Running: /usr/bin/jar xf WEB-INF/lib/oxtrust-configuration-*.jar
07:23:40 07/04/16 java.io.FileNotFoundException: WEB-INF/lib/oxtrust-configuration-*.jar (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at sun.tools.jar.Main.run(Main.java:260)
        at sun.tools.jar.Main.main(Main.java:1231)

I'll fit it today.

**Comment by dmogn** [comment]
I found the problem. oxtrust-configuration has been unpaked 2 times in setup.

Testing...

**Comment by dmogn** [comment]
Fixed.
