### ISSUE TITLE
Proposal for tihgtening up security of our Apache package inside the container

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/community-edition-setup#137]
One of our clients proposes these changes to Gluu's default Apache's config file (from CentOS7 package):

Currently: `SSLProtocol all -SSLv2 -SSLv3 +TLSv1.2 +TLSv1.1 +TLSv1`

After: `SSLProtocol -ALL +TLSv1`

--

Currently: `SSLCipherSuite ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:DHE-RSA-AES128-SHA256:DHE-DSS-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES128-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK`

After: `SSLCipherSuite EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA+SHA384:EECDH:EDH+aRSA:HIGH:!MEDIUM`

**Comment by willow9886** [comment]
This was a recommendation from one of EDU customers who has implemented this in his own environment...

@aliaksander-samuseu notes that: 

>Limiting selection of protocols in such way may create issues in some complex setups, with a lot of different clients, like native apps on different mobile OS versions, outdated browsers that still may be used by many users that not belong to environment that is controlled by the organizations using Gluu as IdP etc. It's easy to recommend to some corporate client to use only latest software with support of most secure protocols (and still there will be some issues anyway), but probably not to someone dealing with more general audience worldwide. 
>
>It's a good material for some article perhaps, on securing the installation, though we need more material like that to make it a solid one :) Also, as it's not directly related to Gluu, but it just can be subdivided into problems of securing its well-know components (tomcat, apache, ldap server etc), it may happen to be just too much of excessive work, these subjects are well covered by those packets' mainteners.
>

@nynymike any thoughts? Perhaps we should assign to @zamilskhan for creation of an article in the docs about this?

Thanks, guys.

**Comment by mzico** [comment]
One point... while applying new cipher suite... previously we tightened our ciphersuite according to this EDU but it turned out that.... 95% organizations are not ready ( or not in a position ) to align their setup to support the stronger setup from SSL.  

So.. even if we include this in our default Gluu Server we might need to lower the level of SSL and CipherSuite to accommodate other people.

**Comment by aliaksander-samuseu** [comment]
@mzico is right, most likely. And after talking to Jeff, it seems that this is something they prefer to use internally rather than something they would recommend as defaults. I'm not even sure whether we really need an article on that, as this is a standard security tunning which is covered by Apache-related docs all over the internet already.

**Comment by aliaksander-samuseu** [comment]
I'm closing it now, seems it's too tight for a general instance.
