### ISSUE TITLE
Apache MPMs differ between Gluu's packages for different distros

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/community-edition-setup#139]
While helping a customer striving to prepare his instance for high load scenario, it became apparent for me that Apache installed as a part of Gluu packages has different MPMs (Multi-Processing Modules) right out of the box in different distros. Like, in my test ubuntu 2.4.3 instance [  mpm_event_module](http://httpd.apache.org/docs/current/mod/event.html) is configured (what is a good thing and a way to go as it's the most efficient one), but at client's CentOS6.7 instance (and also at another CentOS7 instance) it was [mpm_prefork_module](https://httpd.apache.org/docs/2.4/mod/prefork.html), which is rather outdated and inefficient one.

This won't constitute a big issue for most of the use cases when load on the instance doesn't reach extreme levels, but will very likely create issues in high-load scenarios, as pre-fork will create a separate **process** for each incoming HTTP request, which will exist until this connection lives (which even worse if HTTP keep-alives are taken into consideration). These drawbacks were mitigated in more recent "worker" and "event" MPMs.

2 questions:
1. Why do we have different MPMs configured for different packages? Is it intended?
2. Shouldn't we switch all our packages to using **mpm_event_module** right out of the box? It should be stable enough and the only drawback it has comparing to prefork is that it's not compatible with "non-thread-safe" libraries and modules.

**Comment by ganesh-at-wiw** [comment]
The answer to your point 1 is that, we're using default configurations.
For point 2, I test it out and let you know.

**Comment by ganesh-at-wiw** [comment]
For point 2, we can enable worker module by uncommenting the line:
GLUU.[root@localhost community-edition-setup]# grep HTTPD /etc/sysconfig/httpd 

> HTTPD=/usr/sbin/httpd.worker

and restarting httpd service.

**Comment by ganesh-at-wiw** [comment]
I think we should keep things as such.
If need be, we can make changes for specific users only.
