### ISSUE TITLE
There is no facter and check_sll commands

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#14]
We need to allow tomcat user to execute these commands: facter, check_ssl

**Comment by worldiswelcome** [comment]
facter was part of puppet stuff.
Do we want to install facter individually?

**Comment by yurem** [comment]
oxTrust runs it to gather statistic

**Comment by worldiswelcome** [comment]
I've added facter to the server rpm.

**Comment by yurem** [comment]
Can you add check_ssl command too?
