### ISSUE TITLE
Configure GluuOpenDJ to allow schema modification

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#15]
According to oxTrust log file
Attributes: Failed to add new attribute type to LDAP schema
LDAPException(resultCode=80 (other), errorMessage='An error occurred while attempting to write the updated schema:  IOException(Permission denied)', diagnosticMessage='An error occurred while attempting to write the updated schema:  IOException(Permission denied)')

I suspect we need to change Gluu-OpenDJ configuration to enable these operations.
More info:
GLUU.[root@cec65 config]# cat config.ldif | grep aci | grep schema
ds-cfg-global-aci: (target="ldap:///cn=schema")(targetscope="base")(targetattr="objectClass||attributeTypes||dITContentRules||dITStructureRules||ldapSyntaxes||matchingRules||matchingRuleUse||nameForms||objectClasses")(version 3.0; acl "User-Visible Schema Operational Attributes"; allow (read,search,compare) userdn="ldap:///anyone";)
ds-cfg-global-aci: (targetattr="createTimestamp||creatorsName||modifiersName||modifyTimestamp||entryDN||entryUUID||subschemaSubentry")(version 3.0; acl "User-Visible Operational Attributes"; allow (read,search,compare) userdn="ldap:///anyone";)

**Comment by yurem** [comment]
I tied to run cn=schema modification manually in order to gather more information about this issue. On every steps I tried to remove part which causes issue.
But we can't to do that because our 101-ox.ldif uses them.

It looks like we need to run few additional ds-confing commands in order to resolve these issues.
 
These are list of iterations and results:
1)
#!RESULT ERROR
#!CONNECTION ldap://cec65.gluu.info:1636
#!DATE 2015-01-26T18:25:26.688
#!ERROR [LDAP: error code 21 - When attempting to modify entry cn=schema to add one or more values for attribute attributeTypes, value "( 1234567890 NAME 'test' EQUALITY caseIgnoreMatch ORDERING caseIgnoreOrderingMatchSUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 USAGE userApplications X-SCHEMA-FILE '100-user.ldif' X-ORIGIN 'gluu' )" was found to be invalid according to the associated syntax:  The definition for the attribute type with OID 1234567890 declared that ordering matching should be performed using the matching rule "caseignoreorderingmatchsubstr".  No such ordering matching rule is configured for use in the Directory Server]
dn: cn=schema
changetype: modify
add: attributeTypes
attributeTypes: ( 1234567890 NAME 'test' EQUALITY caseIgnoreMatch ORDERING cas
 eIgnoreOrderingMatchSUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.
 115.121.1.15 USAGE userApplications X-SCHEMA-FILE '100-user.ldif' X-ORIGIN 'g
 luu' )
-

2)
#!RESULT ERROR
#!CONNECTION ldap://cec65.gluu.info:1636
#!DATE 2015-01-26T18:29:08.881
#!ERROR [LDAP: error code 21 - When attempting to modify entry cn=schema to add one or more values for attribute attributeTypes, value "( 1234567890 NAME 'test' EQUALITY caseIgnoreMatch ORDERING caseIgnoreOrderingMatchSYNTAX 1.3.6.1.4.1.1466.115.121.1.15 USAGE userApplications X-SCHEMA-FILE '100-user.ldif' X-ORIGIN 'gluu' )" was found to be invalid according to the associated syntax:  The definition for the attribute type with OID 1234567890 declared that ordering matching should be performed using the matching rule "caseignoreorderingmatchsyntax".  No such ordering matching rule is configured for use in the Directory Server]
dn: cn=schema
changetype: modify
add: attributeTypes
attributeTypes: ( 1234567890 NAME 'test' EQUALITY caseIgnoreMatch ORDERING cas
 eIgnoreOrderingMatchSYNTAX 1.3.6.1.4.1.1466.115.121.1.15 USAGE userApplicatio
 ns X-SCHEMA-FILE '100-user.ldif' X-ORIGIN 'gluu' )
-

3)
#!RESULT ERROR
#!CONNECTION ldap://cec65.gluu.info:1636
#!DATE 2015-01-26T18:29:38.827
#!ERROR [LDAP: error code 21 - When attempting to modify entry cn=schema to add one or more values for attribute attributeTypes, value "( 1234567890 NAME 'test' EQUALITY caseIgnoreMatchSYNTAX 1.3.6.1.4.1.1466.115.121.1.15 USAGE userApplications X-SCHEMA-FILE '100-user.ldif' X-ORIGIN 'gluu' )" was found to be invalid according to the associated syntax:  The definition for the attribute type with OID 1234567890 declared that equality matching should be performed using the matching rule "caseignorematchsyntax".  No such equality matching rule is configured for use in the Directory Server]
dn: cn=schema
changetype: modify
add: attributeTypes
attributeTypes: ( 1234567890 NAME 'test' EQUALITY caseIgnoreMatchSYNTAX 1.3.6.
 1.4.1.1466.115.121.1.15 USAGE userApplications X-SCHEMA-FILE '100-user.ldif' 
 X-ORIGIN 'gluu' )
-
4)
#!RESULT ERROR
#!CONNECTION ldap://cec65.gluu.info:1636
#!DATE 2015-01-26T18:29:59.143
#!ERROR [LDAP: error code 80 - An error occurred while attempting to write the updated schema:  IOException(Permission denied)]
dn: cn=schema
changetype: modify
add: attributeTypes
attributeTypes: ( 1234567890 NAME 'test'SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 U
 SAGE userApplications X-SCHEMA-FILE '100-user.ldif' X-ORIGIN 'gluu' )
-

**Comment by nynymike** [comment]
I think this requires `dsconfig`

**Comment by nynymike** [comment]
Error 80 : "The result code that should be used if no other result code is appropriate" Directly updating the OpenDJ schema via LDAP is just not a good idea. Ideally this would be sent to salt for remote execution on the LDAP servers in the topology. Perhaps we should just remove the hook to LDAP and say : make sure you update your LDAP schema!

**Comment by yurem** [comment]
We limit user here. He is able to add new attributes and remove added attributes. He can't drop server schema.

**Comment by nynymike** [comment]
Jan 25, 2015 2:25:21 PM org.opends.quicksetup.util.UIKeyStore getInstance
INFO: Path /home/ldap/.opendj/gui-keystore does not exist

I think this is a result of /home/ldap being owned by root:root   

When this folder gets created, its really important its owned by ldap:ldap. 

Also, there should not be any .bash_history in /home/ldap/.bash_history

**Comment by yurem** [comment]
Are you speaking about chroot with gluu-opendj installation?

**Comment by nynymike** [comment]
yes, after install of Gluu Server, when I ls the /home/ folder, I can see that `/home/ldap` is not owned by `ldap:ldap`  I wonder if this user was added through the useradd tool properly...

**Comment by yurem** [comment]
We have fixed /home/ldap owner. There is something which we need to fix additionally in order to resolve it.
