### ISSUE TITLE
Integrate resolution to auto-config timezone/etc in rpm installer

### ISSUE THREAD

**Issue by devmaster** [GluuFederation/community-edition-setup#150]
I was asked to put this in as a req on github. The gluu installer should setup/config whatever is needed such that the timestamps on the log entries actually match the data/time/tz on the server it was installed on. 

https://support.gluu.org/installation/gluu-server-system-time-config-2686

**Comment by aliaksander-samuseu** [comment]
There is also a [relevant request](https://github.com/GluuFederation/community-edition-setup/issues/71) from before

**Comment by mzico** [comment]
@devmaster : Let's follow [previous](https://github.com/GluuFederation/community-edition-setup/issues/71) ticket.
