### ISSUE TITLE
Move gluu-server initd/systemd scripts into setup/init folder

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#158]
Right now it's not easy to manage and modify init.d/system.d gluu-server scripts. The problem appears because we store them on build servers only (for each OS we have copy on each server).
In build process we use ./feth_sources.sh bash script which gets specified setup version. We need to modify it to extract required gluu-server script after downloading setup.

**Comment by adrian-gluu** [comment]
https://repo.gluu.org/centos/testing/gluu-server-2.4.4-1-3.centos6.x86_64.rpm
https://repo.gluu.org/ubuntu/pool/main/trusty-devel/gluu-server-2.4.4_1-3~trusty+Ub14.04_amd64.deb

**Comment by ganesh-at-wiw** [comment]
now 2.4.4 versions are copied to github project: https://github.com/GluuFederation/community-edition-package

**Comment by ganesh-at-wiw** [comment]
The scripts have been merged and are working fine with Ubuntu 16.04, 14.04 and CentOS 6.x.

**Comment by ganesh-at-wiw** [comment]
Adding support for RHEL 6 and Debian 8 as well.

**Comment by yurem** [comment]
@ganesh-at-wiw any updates on this? Can we remove 2.4.4 version files from repo? In 2.4.4 we still use old scripts.

**Comment by ganesh-at-wiw** [comment]
Hi Yura, debian testing is going on and one more thing is there that echo statements do not run properly.
So, working on that.

**Comment by ganesh-at-wiw** [comment]
Removed rest of the unnecessary checks for RedHat based OSs.
