### ISSUE TITLE
Add function to configure cronjob for automatic updates

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#159]
During setup we need to create cronjob to do updates.

This process should be configuable. Installer should asks if user need this job and answe on questions about this job run frequency.

Default values are:
Install OS updates automatically: Y
Install OS updates: daily

For RHEL we need to do additional investigation. Can we enable these options?

**Comment by ganesh-at-wiw** [comment]
> [Tuesday 9 August 2016 3:52:33 PM Ganesh Dutt Sharma] how about cron for updates?

> [Tuesday 9 August 2016 3:52:45 PM Ganesh Dutt Sharma] this is another issue pending for long :)

> [Tuesday 9 August 2016 3:52:58 PM Yuriy Movchan] Mide and I decided to not use it

> [Tuesday 9 August 2016 3:53:01 PM Yuriy Movchan] We added comments to this issue

> [Tuesday 9 August 2016 3:53:20 PM Ganesh Dutt Sharma] oh ok

> [Tuesday 9 August 2016 3:53:23 PM Yuriy Movchan] it can cause issue in docker

> [Tuesday 9 August 2016 3:53:29 PM Ganesh Dutt Sharma] can that be closed?

> [Tuesday 9 August 2016 3:54:31 PM Yuriy Movchan] https://github.com/GluuFederation/community-edition-setup/issues/158

> [Tuesday 9 August 2016 3:54:58 PM Yuriy Movchan] I opened this issue to get simple access to gluu-server scripts

> [Tuesday 9 August 2016 3:55:12 PM Yuriy Movchan] Now we have to change it in chroot
