### ISSUE TITLE
Use import-ldif instead of ldapmodify to load data in import script

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#162]
If there are a lot of users, ldapmodify to import might take hours. A better option is to stop tomcat and the DS and to use the ``/opt/opendj/bin/import-ldif `` script, which is much faster. 

It's also important to update `/opt/opendj/config/java.properties`  to give the import JVM as much memory as possible (perhaps add tomcat + ldap memory from setup.properties):

```
  overwrite-env-java-args=true
  import-ldif.offline.java-args=-Xms2560M -Xmx2560M
```

The run

```
  $ bin/dsjavaproperties
```

To Append Imported Data to Existing Data:
 Stop the server if it is running.
```
 $ service opendj stop
```

 Import the LDIF file, appending the new data to the existing data. For example:
```
 $ import-ldif -n userRoot  -l new.ldif -R reject-log.ldif
```

**Comment by tecoholic** [comment]
This has been implemented in the new script [import244.py](https://github.com/GluuFederation/community-edition-setup/blob/master/static/scripts/import244.py)

**Comment by mzico** [comment]
@tecoholic @zamilskhan @nynymike : I think we can test this by 500K users? 
Here is my suggestion: 

- Install 2.4.3
- Generate 500K users in 2.4.3
- Try to upgrade to 2.4.4
- Let's see how ldif-import goes

?

**Comment by zamilskhan** [comment]
@mzico sure.
