### ISSUE TITLE
setup.py with -s not installing shibd in 2.4.4

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#164]
OS: CentOS6.x
How to reproduce: 
- Get 'setup.properties.last'
- Use upper one and 'setup.py -s' in another VM
- Two type of errors: 
  - oxTrustConf JSON merging not happening:  `INFO   | jvm 1    | 2016/08/10 19:03:41 | 2016-08-10 19:03:41,830 ERROR [org.gluu.oxtrust.config.OxTrustConfiguration] Failed to load configuration from LDAP
    INFO   | jvm 1    | 2016/08/10 19:03:41 | org.gluu.site.ldap.persistence.exception.MappingException: Failed to convert json value '{`
    
    ```
     - This can be fixed by changing ["configGeneration":enabled] to ["configGeneration":false] followed by tomcat restart
    ```
  -  Shibboleth vm are missing: `INFO   | jvm 1    | 2016/08/10 19:35:18 | 2016-08-10 19:35:17,989 ERROR [org.gluu.oxtrust.ldap.service.TemplateService] Failed to load velocity template 'sp-metadata.xml'
    INFO   | jvm 1    | 2016/08/10 19:35:18 | org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'sp-metadata.xml.vm'`

**Comment by lrockwell** [comment]
Having the similiar issues on RHEL 7.2 64bit

Traceback (most recent call last):
  File "./setup.py", line 2141, in <module>
    installObject.apache_version = installObject.determineApacheVersionForOS()
  File "./setup.py", line 732, in determineApacheVersionForOS
    return self.determineApacheVersion("httpd")
  File "./setup.py", line 720, in determineApacheVersion
    apache_version = p.stdout.read().strip().split(' ')[2].split('/')[1]
IndexError: list index out of range

**Comment by nynymike** [comment]
As a workaround, use the interactive installation and just select the Shib IDP component when prompted.

**Comment by yurem** [comment]
@mzico  can you verify this in latest CE 3.0.0 Alpha builds?

**Comment by mzico** [comment]
@yurem : Sorry... I missed the message. I'll test 3.0.0

**Comment by yurem** [comment]
I've tested in in 3.0.0 and I can't reproduce this issue. IDP works fine after installation and setup properly detects that I installed Saml in other VM.
