### ISSUE TITLE
Remove Unused Shib IDP Services

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#167]
No one uses the Attribute Service (attributes are sent in the SSO assertion) and no one uses artifact endpoints (which in fact are not even mapped in apache. Let's remove this to reduce the size of the SAML metadata from the initial configuration.

Attribute Service
Artifact Endpoints
SAML 1.1 or Shib 1.3 endpoints
See [InCommon recommendations](https://spaces.internet2.edu/display/InCFederation/Protocol+Support+for+New+IdPs)

**Comment by yurem** [comment]
@Val, can you review if this is needed for IDP3 too?

**Comment by uboznikov** [comment]
@yurem Please see above.
