### ISSUE TITLE
Disable UsernamePassword Handler 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#168]
I was testing a SAML client that included this in the `AuthnRequest`

```
<samlp:AuthnRequest
   <samlp:RequestedAuthnContext Comparison="exact">
        <saml:AuthnContextClassRef>
            urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
        </saml:AuthnContextClassRef>
   </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```
I was surprised when I got back this form... which is certainly not going to work:

![image](https://cloud.githubusercontent.com/assets/3717101/17978897/c1b82802-6abd-11e6-89de-39a4a53030c4.png)

Let's comment out U/P login handler.  Configuration file: `/opt/idp/conf/handler.xml`

```
    <!--  Username/password login handler -->

<!--
    <ph:LoginHandler xsi:type="ph:UsernamePassword"
                  jaasConfigurationLocation="file:///opt/idp/conf/login.config">
        <ph:AuthenticationMethod>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</ph:AuthenticationMethod>
    </ph:LoginHandler>
-->
```

**Comment by yurem** [comment]
@mzico can you update template in oxTrust: https://github.com/GluuFederation/oxTrust/tree/master/configuration/template/shibboleth2/idp/handler.xml ?

**Comment by mzico** [comment]
@yurem : done.

**Comment by yurem** [comment]
Thanks, it will be part of 2.4.5. Our setup extract templates from identity.war and copy them to right place during install.
