### ISSUE TITLE
Remove second defintion of gluuStatus attribute

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#169]
There are 2 definitions of gluuStatus in attributes.ldif:
1) https://github.com/GluuFederation/community-edition-setup/blob/master/templates/attributes.ldif#L793
2) https://github.com/GluuFederation/community-edition-setup/blob/master/templates/attributes.ldif#L1093

This duplicity led to issue with SCIM. We need to keep only one definition.

Also this fix should be part of 2.4.1 SP1

**Comment by shekhar16** [comment]
Fixed.

**Comment by yurem** [comment]
Fixed
