### ISSUE TITLE
Should CE support SOAP Endpoints

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#17]
According to the https://wiki.shibboleth.net/confluence/display/SHIB2/IdPApacheTomcatPrepare sections "Support SOAP Endpoints" we can allow legacy Shibboleth SPs using SAML 1.1 in CE.

Do we really needs to support SAML 1.1?

**Comment by mzico** [comment]
My two cents... I don't think we should support SAML 1.1

**Comment by yurem** [comment]
I added this issue after this transaction: https://github.com/GluuFederation/community-edition-setup/commit/5ac0ed8af73f31ca0864f3c8f9702b5b7367b8d0

**Comment by nynymike** [comment]
Not in this version...
