### ISSUE TITLE
Dockerizing Gluu Server

### ISSUE THREAD

**Issue by dalareo** [GluuFederation/community-edition-setup#170]
I am aware of **Docker Edition** of Gluu, but what I am trying to get is a **_dockerized Gluu CE_** in order to create a template to be delivered into [EduCaaS](http://educaas.io) (open learning environment built over Rancher).
I am creating a Dockerfile (attached to this message), but I guess I need also to attach to my "gluu-server" container a Tomcat container and a database one. Anybody working on it?

[Dockerfile.zip](https://github.com/GluuFederation/community-edition-setup/files/439441/Dockerfile.zip)

**Comment by yurem** [comment]
In CE 3.0.0 we are going to replace many parts: http://gluu.org/CE-roadmap
We can back to this question after 3.0.0 release

**Comment by nynymike** [comment]
@shouro Can you take a look at these docker files. Any thoughts?

**Comment by shouro** [comment]
We are not working on docker CE version.
CE developed to work on chroot so if you do it you may need to modify current CE structure.
Tecnicaly you can do it using tools like supervisord and a modified setup.py .
how you are planing to use 'CherryPy' ?

**Comment by dalareo** [comment]
Great job @pi0 ! I created an issue in the repo: not able to load login page!

**Comment by indiependente** [comment]
Hi everyone!
Is there any documentation on how to spin up a docker image of the CE?

Thanks 😃

**Comment by willow9886** [comment]
hey there @indiependente, please see Mike's statement here on a [docker version of Gluu](https://support.gluu.org/installation/4384/docker-question/#at24530). 

Thanks.

**Comment by blaggacao** [comment]
@nynymike Please consider the ongoing earthquake shift towards kubernetes when deciding on your orchestration choice:

- http://rancher.com/rancher-labs-launches-rancher-2-0/
(they usually have good sensors deep inside the docker ecosystem)

- which leads me to referencing this "breaking news": 
https://blog.docker.com/2017/10/kubernetes-docker-platform-and-moby-project/

**Comment by blaggacao** [comment]
If someone could point me to some resources I could start with a docker-compose.yml as an evening project, have done it before, and I'd really play around a little bit with gluu...

**Comment by nynymike** [comment]
We are working on it. The Gluu Server is a bunch of services configured and working together. It's not a trivial stateless web application.

**Comment by blaggacao** [comment]
If you want to give a try on local kubernetes, right away, I can really recommend you `minikube` or `minishift` - minishift has extra componentes, but i find it a slight bit more user friendly and self explaining...
