### ISSUE TITLE
Add a section for csync2 tool's logs to our log rotation script.

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/community-edition-setup#171]
Was proposed by Gene in [this ticket](https://support.gluu.org/outages/oxtrust-wasnt-allow-to-access-user-data-3175/#at14431). We use csync2 in our manual cluster solution. Currently it simply overwrites its own logs at each run. It would be useful to have them stored for some time for auditing purposes, in that case we need them be archived/removed as time goes.

Here is Gene's opinion on how it could be done:

```
Below is a sample of what could be put in /etc/logrotate.d/csync2:

/var/log/csync2*.log {
        daily
        rotate 7
        copytruncate
        compress
        missingok
        notifempty
}
```

But as we employ our own log rotation script run by cron  - `/opt/gluu/bin/logmanager.sh` - it may be a better solution to add it there, for consistency.

We'll need to figure out which logs we need to put in there. It also needs to account for the fact that those logs may be absent, as the script is the same both for standalone and cluster setups.

**Comment by tecoholic** [comment]
@aliaksander-samuseu I don't work on this part of the project. Maybe there is a mistake in ticket assignment.

**Comment by tecoholic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a section for csync2 tool's logs to our log rotation script Setup #171](https://trello.com/c/QJ0D9Rho/59-add-a-section-for-csync2-tools-logs-to-our-log-rotation-script-setup-171)

**Comment by tecoholic** [comment]
We are no longer using csync2 in versions 3.x and up for clustering. I am closing this ticket as out of date.
