### ISSUE TITLE
Allow admin to selct which container to use : tomcat or Jetty

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#173]
oxAuth/oxTrust are ready to start under jetty.
We need to support to run oxauth.war/identity.war under jetty 9.3

**Comment by nynymike** [comment]
I think we should just get rid of tomcat. Less options means less support headaches.

**Comment by dmogn** [comment]
oxAsimba are ready to start under jetty too.

**Comment by yurem** [comment]
I agree, less options is better for us

**Comment by yurem** [comment]
Only Jetty now.
