### ISSUE TITLE
Tomcat/OpenDJ services run under root user insided containers of CentOS7/RHEL7-based instances.

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/community-edition-setup#176]
Results of quick survey I did show that in containers of the latest packages (2.4.3-2.4.4)  based on CentOS7/RHEL7 distros services of Tomcat and OpenDJ run under root user, instead of "tomcat"/"ldap" users, respectively.  I just run`ps -aux | grep -i java` on those vms within container to check for this. This behavior can't be seen in containers based on CentOS6.x or Ubuntu 14.02 distros.

**Comment by ganesh-at-wiw** [comment]
I've added my changes to https://github.com/GluuFederation/community-edition-setup/tree/ganesh-tomcat-user-fix. RPM build process is going on. As soon as it's tested, I'll intimate.

**Comment by ganesh-at-wiw** [comment]
I've fixed the tomcat and opendj scripts to run under tomcat and ldap users resp.
RPM package build is going on. After testing it, I can confirm if things are working well and can request Yura to merge the package.

**Comment by aliaksander-samuseu** [comment]
Checked Ganesh's fix method, and it worked for me.

**Comment by ganesh-at-wiw** [comment]
Closing this and now the rpm will verify the further working.
