### ISSUE TITLE
setup.py is saving base64 properties with newlines in setup.properties.last in 2.4.4

### ISSUE THREAD

**Issue by ryno75** [GluuFederation/community-edition-setup#184]
Setup.py is saving the setup.properties.last file with multi-line values to base64 properties.  When trying to utilize a properties file with those multiline values (with the -f option) it fails to retrieve correct values for any multiline properties.
- Example

```
oxasimba_config_base64=ewogICAgIm9yZ0ludW0iOiJAITU5NjAuRUFCQy5BQjA1LjUzRTchMDAwMSEyQ0Y5LjBCOTUiLAog
 ICAgIm94YXNpbWJhIjoib3U9b3hhc2ltYmEsbz1AITU5NjAuRUFCQy5BQjA1LjUzRTchMDAwMSEy
 Q0Y5LjBCOTUsbz1nbHV1IiwKICAgICJpZHBzIjoib3U9aWRwcyxvdT1veGFzaW1iYSxvPUAhNTk2
 MC5FQUJDLkFCMDUuNTNFNyEwMDAxITJDRjkuMEI5NSxvPWdsdXUiLAogICAgInNlbGVjdG9ycyI6
 Im91PXNlbGVjdG9ycyxvdT1veGFzaW1iYSxvPUAhNTk2MC5FQUJDLkFCMDUuNTNFNyEwMDAxITJD
 RjkuMEI5NSxvPWdsdXUiLAogICAgInJlcXVlc3RvcnMiOiJvdT1yZXF1ZXN0b3JzLG91PW94YXNp
 bWJhLG89QCE1OTYwLkVBQkMuQUIwNS41M0U3ITAwMDEhMkNGOS4wQjk1LG89Z2x1dSIsCiAgICAi
 cmVxdWVzdG9ycG9vbHMiOiJvdT1yZXF1ZXN0b3Jwb29scyxvdT1veGFzaW1iYSxvPUAhNTk2MC5F
 QUJDLkFCMDUuNTNFNyEwMDAxITJDRjkuMEI5NSxvPWdsdXUiCn0K
```

But that should actually look like...

```
oxasimba_config_base64=ewogICAgIm9yZ0ludW0iOiJAIURGQzIuMjQ3Ny44M0RGLkEyNDAhMDAwMSE5NDk2LkQ0NTAiLAogICAgIm94YXNpbWJhIjoib3U9b3hhc2ltYmEsbz1AIURGQzIuMjQ3Ny44M0RGLkEyNDAhMDAwMSE5NDk2LkQ0NTAsbz1nbHV1IiwKICAgICJpZHBzIjoib3U9aWRwcyxvdT1veGFzaW1iYSxvPUAhREZDMi4yNDc3LjgzREYuQTI0MCEwMDAxITk0OTYuRDQ1MCxvPWdsdXUiLAogICAgInNlbGVjdG9ycyI6Im91PXNlbGVjdG9ycyxvdT1veGFzaW1iYSxvPUAhREZDMi4yNDc3LjgzREYuQTI0MCEwMDAxITk0OTYuRDQ1MCxvPWdsdXUiLAogICAgInJlcXVlc3RvcnMiOiJvdT1yZXF1ZXN0b3JzLG91PW94YXNpbWJhLG89QCFERkMyLjI0NzcuODNERi5BMjQwITAwMDEhOTQ5Ni5ENDUwLG89Z2x1dSIsCiAgICAicmVxdWVzdG9ycG9vbHMiOiJvdT1yZXF1ZXN0b3Jwb29scyxvdT1veGFzaW1iYSxvPUAhREZDMi4yNDc3LjgzREYuQTI0MCEwMDAxITk0OTYuRDQ1MCxvPWdsdXUiCn0K
```

If we simply change the `encode('base64')` lines in setup.py to use translate or replace string functions to remove newlines in the resultant base64 blob it will resolve this.
e.g.

``` python
-            plain_file_b64encoded_text = plain_file_text.encode('base64').strip()
+            plain_file_b64encoded_text = plain_file_text.encode('base64').translate(None, '\n').strip()
```

**Comment by ryno75** [comment]
@nynymike have you encountered this?  Any comments?  Looks like a patch to Properties.py will be needed but perhaps I am missing something.

**Comment by ryno75** [comment]
Maybe the easy/correct answer is to just change setup.py to use no whitespace in its base64 values.

**Comment by yurem** [comment]
I've added [new property](https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L63):

```
self.templateRenderingDict = {}
```

Now during rendering templates setup also uses this dictionary.

It's better to put base64 variables in this dictionary. We don't need to persist these values. Setup always generate them from source values at runtime.

**Comment by ryno75** [comment]
Hmm... that still isn't going to fix the newline problem.  the python string `encode` method will always insert those line breaks into the resultant string which are incompatible with the setup.properties file (based on how `properties.py` currently works.  Not to mention... having newlines in base64 is really only useful for human readability.  In something like a properties file we should never want/need those line breaks.

**Comment by nynymike** [comment]
Can you send me a linkedin? https://www.linkedin.com/in/nynymike

**Comment by yurem** [comment]
@uboznikov , @dmogn can review you asimba/cas/idp3 properties to store variables which we should not put to setup.properties.last in templateRenderingDict.

Setup.py has all required changes. You only need to do replacements like this. From:
```
self.idp3EncryptionCertificateText = self.load_certificate_text(self.certFolder + '/idp-encryption.crt')
```
to:
```
self.templateRenderingDict['idp3EncryptionCertificateText'] = self.load_certificate_text(self.certFolder + '/idp-encryption.crt')
```

Example variables: idp3EncryptionCertificateText, idp3SigningCertificateText

**Comment by yurem** [comment]
Fixed
