### ISSUE TITLE
Deprecate IDP2

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#187]
Should we remove IDP2 att all? Is oxTrust ready to support IDP3?

@nynymike , @uboznikov What do you think?

**Comment by nynymike** [comment]
In Gluu Server version 3 we should remove IDP v2. However, Gluu Server 2.4.4 should still contain Shib IDPv2.

**Comment by uboznikov** [comment]
[Shibboleth IDP v3](https://github.com/GluuFederation/community-edition-setup/commit/f8ef17e84d39406f073f47d8baac1fc9a1cceb92#diff-00facdf0aabaa8edf9db81b860e9f1fb)

**Comment by yurem** [comment]
Fixed
