### ISSUE TITLE
Remove OpenJDK from distirbutions

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#188]
This issue depends on https://github.com/GluuFederation/community-edition-setup/issues/187

If we will replace IDP2 with IDP3 I think we can remove OpenJDK from rpm/deb to save space and avoid conflicts and extra memory usage.

All other components uses Server JRE now: http://www.oracle.com/technetwork/java/javase/downloads/server-jre8-downloads-2133154.html

**Comment by nynymike** [comment]
aren't we still using OpenJDK for oxAuth / oxTrust? It sounds like you'd rather just ditch OpenJDK...

**Comment by yurem** [comment]
Fixed. Only server Oracle JRE exists in CE now
