### ISSUE TITLE
No /etc/resolv.conf in deb container right after installation

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/community-edition-setup#191]
Environment:
Gluu CE 2.4.4 from [here](https://repo.gluu.org/ubuntu/pool/main/trusty-devel/gluu-server-2.4.4_1-3~trusty+Ub14.04_amd64.deb), Ubuntu 14.04

Steps to reproduce:
1. Conduct regular installation and run `setup.py` script enabling Shibboleth, Asimba and oxAuth-RP components in addition to enabled by default
2. Run `# cat /etc/resolv.conf` in the container, check `/install/community-edition-setup/setup_error.log`

Result:
The `cat` command tells that such file doesn't exist. Running `# ll /etc/resolv.conf` produces next output:

```
# ll /etc/resolv.conf 
lrwxrwxrwx 1 root root 29 Oct  6  2015 /etc/resolv.conf -> ../run/resolvconf/resolv.conf
```

So this file is a symlink. But even under `/run/` there is still no file "resolv.conf".
Due to this fact setup.py script fails to load and install optional components (Asimba, oxAuth-RP), as it can't resolve name of the web server. Here is the [full setup.py error log](https://github.com/GluuFederation/community-edition-setup/files/556648/setuppy_error_log.txt)

**Comment by aliaksander-samuseu** [comment]
To circumvent it, you may create `/run/resolvconf/resolv.conf` file and put "nameserver 8.8.8.8" into it right before running setup.py.

**Comment by yurem** [comment]
Fixed in similar issue: https://github.com/GluuFederation/community-edition-setup/issues/121
