### ISSUE TITLE
DNS resolver file changing in CentOS7.2

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#192]
Problem: After performing setup.py operation, 'resolv.conf' ingredient changing. 
Affected piece: asimba.war is not downloading if we select it. 

Situation: 
- Before running setup.py, 'resolv.conf' looks like: 

```
[root@gluu_server_2 dist]# cat /etc/resolv.conf 
nameserver 8.8.8.8
nameserver 8.8.4.4
[root@gluu_server_2 dist]#

```
- After performing setup.py operation: 

```
[root@gluu_server_2 webapps]# cat /etc/resolv.conf 
# Generated by NetworkManager
search gluu.org


# No nameservers found; try putting DNS servers into your
# ifcfg files in /etc/sysconfig/network-scripts like so:
#
# DNS1=xxx.xxx.xxx.xxx
# DNS2=xxx.xxx.xxx.xxx
# DOMAIN=lab.foo.com bar.foo.com
[root@gluu_server_2 webapps]# 

```

**Comment by yurem** [comment]
We applied to CentOS 6.7 / Ubuntu 14.04 fix: https://github.com/GluuFederation/community-edition-setup/issues/121

Also we are going to apply the same to all other OS

**Comment by yurem** [comment]
Can you reopen it if needed?
