### ISSUE TITLE
Hostname is changed outside of the container each time Gluu service is started

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/community-edition-setup#198]
Environment:
CentOS 6.7, RHEL 6.8, Gluu CE 2.4.4 SP2

Preconditions:
Gluu CE instance is fully installed the way doc portal recommends, is configured to start up at boot, and the machine has been restarted at least once after that

Steps to reproduce:
1. Acquire access to console of the machine with Gluu installed (ssh etc)
2. Change hostname of the machine outside of the container to anything else with `# hostname thenewone`, then also persist the new hostname in "/etc/sysconfig/network" file
3. Restart the machine `shutdown -r now`, then run `# hostname` again, and check contents of the "/etc/sysconfig/network"

Results:
Despite "/etc/sysconfig/network" still keeps the new hostname you set at step 2), `# hostname` command outputs the name you set to the Gluu instance when you were running `setup.py` before. This causes users some troubles, specifically in cases when Puppet is used to manage CE cluster nodes behind some LB.It was reported that this won't happen if Gluu service isn't set to start up at boot, but even in this case hostname will be changed when it's started up manually. So it seems Gluu service script causing it.

Expected result:
Hostname outside the container is left intact.

The issue was previously reported [here](https://support.gluu.org/installation/3045/hostname-changed-by-gluu-installer/) and seems to be resolved for CentOS7/RHEL7.

**Comment by ganesh-at-wiw** [comment]
From my own experimentation and googling I reached same conclusion as is this post:
http://unix.stackexchange.com/questions/148514/how-can-i-force-chrooted-programs-to-use-a-virtual-ethernet-device
Reason is, both container and host use same set of environment variables.

Restart network service and it'll affect container. Restart gluu-server and it'll affect host.
It's going to be egg and chicken race.

So, same hostname should be used for both host and container.
For additional hostnames, the /etc/hosts of the server(host) should be used.
Ofc, hostname command will show same host in both container and the host.
