### ISSUE TITLE
Do not import IdP v2 to v3

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/community-edition-setup#208]
Just a heads-up, the following import scripts should not import IdP v2 files (`opt/idp`) to IdP v3 (`/opt/shibboleth-idp`) in Release 3.0.0.

[import24.py](https://github.com/GluuFederation/community-edition-setup/blob/master/static/scripts/import24.py)
[import244.py](https://github.com/GluuFederation/community-edition-setup/blob/master/static/scripts/import244.py)

IdP v3 should re-generate all the v3-compatible files from v2-migrated data from LDAP.

**Comment by tecoholic** [comment]
I think we will be writing a `import3.py` given the amount of changes that have gone into the release. This issue will be closed when that script is ready. Thanks for the heads up.

**Comment by uboznikov** [comment]
I have a second look on this and actually tested for good measure, and we indeed have to migrate some files, like the SP metadata and cert keys. Only the IdP-side templates are being re-generated. Sorry for the inconvenience. Will update when I get the whole picture. Thanks.

**Comment by yurem** [comment]
@uboznikov , @tecoholic can you update this ticket, please. Is it still needed?

**Comment by tecoholic** [comment]
@yurem I think ticket now is invalid as @uboznikov says

> we indeed have to migrate some files, like the SP metadata and cert keys

> Will update when I get the whole picture.

I am closing the ticket for now.

**Comment by uboznikov** [comment]
@tecoholic , Reopening this issue, please note below:

**To** be copied (2.4.4 --> 3.00):
`/opt/idp/metadata` --> `/opt/shibboleth-idp/metadata` (SP metadata)
`/opt/idp/ssl` --> `/opt/shibboleth-idp/ssl` (SP certs)

**Not** to be copied:
`/opt/idp/conf --> /opt/shibboleth-idp/conf` (these are re-generated from LDAP)

**Comment by tecoholic** [comment]
This will be updated in the import30.py script
