### ISSUE TITLE
Asimba jdbc resouces

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#210]
In the current build at asimba startup there is error:
```
java.lang.IllegalStateException: Nothing to bind for name jdbc/oaModel
	at org.eclipse.jetty.plus.webapp.PlusDescriptorProcessor.bindEntry(PlusDescriptorProcessor.java:914)
```

@dmogn What do you think? I think we are not using any internal/external JDBC sources in Asimba.
If this right we need to remove these lines from web.xml

```
	<!-- add standard resource-ref definitions when using the JDBC backend;
	these must be provided by the Application Server context! -->
	<resource-ref>
		<res-ref-name>jdbc/oaModel</res-ref-name>
		<res-type>javax.sql.DataSource</res-type>
		<res-auth>Container</res-auth>
	</resource-ref>
	<resource-ref>
		<res-ref-name>jdbc/oaSystem</res-ref-name>
		<res-type>javax.sql.DataSource</res-type>
		<res-auth>Container</res-auth>
	</resource-ref>
```

**Comment by dmogn** [comment]
>> @dmogn What do you think? I think we are not using any internal/external JDBC sources in Asimba.

- I comment these JDBC references. Looks like it works.

Wrong path in jetty-adapted template:
@dmogn What do you think? I think we are not using any internal/external JDBC sources in Asimba.
(ASIMBAWA) [2016-11-23 20:05:47] [INFO] OAContextListener Updating configuration items with the items in file: /opt/jetty-9.3/temp/jetty-0.0.0.0-8084-asimba.war-_asimba-any-1806820672751588748.dir/webapp/WEB-INF/asimba.properties
(ASIMBAWA) [2016-11-23 20:05:47] [INFO] OAContextListener No optional 'asimba.properties' configuration file found in servlet context classpath
(ASIMBAWA) [2016-11-23 20:05:47] [ERROR] FileConfigurationHandler Configuration file not found: /opt/web/jetty/asimba/webapps/WEB-INF/conf/asimba.xml
(ASIMBAWA) [2016-11-23 20:05:47] [ERROR] OAContextListener Can't start Engine with OAContextListener
com.alfaariss.oa.api.configuration.ConfigurationException: 0021
        at com.alfaariss.oa.util.configuration.handler.file.FileConfigurationHandler.init(FileConfigurationHandler.java:90)

- fixing.

**Comment by yurem** [comment]
We can try to get resources from war file. In 3.0.0 I decided to not do explode to avoid custom war modifications

**Comment by dmogn** [comment]
Yes, there are path examples http://www.eclipse.org/jetty/documentation/9.3.x/configuring-specific-webapp-deployment.html

Fixing...

**Comment by dmogn** [comment]
@yurem 
I moved asimba.xml to community-edition-setup templates.    ( /etc/gluu/conf/asimba/asimba.xml after setup)

asimba.properties has been included in asimba.war.

So, now we can:
- update asimba.war without asimba.xml manipulations in asimba.war
- copy asimba.war to production right after maven.   setup.sh does not need reassembly asimba.war after keystore password change in asimba.war

**Comment by nynymike** [comment]
@dmogn can you make the updates to setup.py or do you need help from yura or someone else?

**Comment by dmogn** [comment]
Fixed.
