### ISSUE TITLE
There is no OpenLDAP logs under Ubuntu 14.04

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#211]

**Comment by yurem** [comment]
@ganesh-at-wiw I think we need your admin skills to help with rsyslog configuration..

**Comment by tecoholic** [comment]
@ganesh-at-wiw By default the rsyslog daemon runs as the user `message-bus` and doesn't log anything. When I run rsyslog from the terminal as `rsyslogd` it logs without issues. But when I run `service rsyslog start` it runs under the user `message-bus` hence doesn't log.

**Comment by ganesh-at-wiw** [comment]
Starting this...

**Comment by ganesh-at-wiw** [comment]
Prepared the work-around.
Now changing the setup.py to adjust to the changes.

**Comment by ganesh-at-wiw** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/4a7d26d7800ad091adeec3ffd013243baddbab50#diff-2eeaed663bd0d25b7e608891384b7298

Arun, please test for yourself and then we can close this issue.

**Comment by yurem** [comment]
@ganesh-at-wiw , can you specify which lines you changed in original file? I think it's better to apply fix to original file than include whole file into  setup.

**Comment by ganesh-at-wiw** [comment]
Hi Yura, can you guide me on fixing, I can do that.
I just added three lines, specific to Ubuntu 14.04 logic only.

**Comment by yurem** [comment]
Can you give these 3 lines which you added?

In current builds with this update we get:
```
07:57:52 11/29/16 rsyslogd: pidfile '/var/run/gluu_rsyslogd.pid' and pid 41595 already exist.
If you want to run multiple instances of rsyslog, you need to specify
different pid files for them (-i option).
rsyslogd: run failed with error -3000 (see rsyslog.h or try http://www.rsyslog.com/e/3000 to learn what that number means)


U144
16:29:08 11/29/16 rsyslogd: run failed with error -2207 (see rsyslog.h or try http://www.rsyslog.com/e/2207 to learn what that number means)
rsyslogd: run failed with error -2207 (see rsyslog.h or try http://www.rsyslog.com/e/2207 to learn what that number means)
cat: /var/run/gluu_rsyslogd.pid: No such file or directory
/etc/init.d/rsyslog: 58: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
rsyslogd: run failed with error -2207 (see rsyslog.h or try http://www.rsyslog.com/e/2207 to learn what that number means)
```

**Comment by ganesh-at-wiw** [comment]
Yura, I added:
 ### rsyslog file customised for init.d
self.rsyslogInitFile = "%s/static/etc/init.d/rsyslog" % self.install_dir

And
self.copyFile(self.rsyslogInitFile, "/etc/init.d")
self.removeFile("/etc/init/rsyslog.conf")

**Comment by ganesh-at-wiw** [comment]
rsyslogd: run failed with error -2207 (see rsyslog.h or try http://www.rsyslog.com/e/2207 to learn what that number means)
Above like is okay, as we don't have much control over rsyslog binary. This error(ineffective) occurs because I made two changes to the /etc/init.d/rsyslog file in start and stop functions.

**Comment by tecoholic** [comment]
I tested the `gluu-server-3.0.0 Ubuntu 14 Build 25`, the logs are being generated without issue after the installation. 
@ganesh-at-wiw Thank you for the fix.

**Comment by yurem** [comment]
It works fine now without errors under Ubuntu 14.04
