### ISSUE TITLE
Unable to connect to OpenLDAP using openldap.crt

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#214]
CAS gets error when it opening connection to LDAP:
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Hostname '[localhost]' does not match the hostname in the server's certificate

I think OpenLDAP cert should have CN=localhost instead of hostname

setup.py method
    def gen_cert(self, suffix, password, user='root'):

should allows to specify cn=localhost

**Comment by uboznikov** [comment]
I specified `hostname` for Shib v3 as `localhost` returns the same error. Is this ok?

[OpenLDAP needs the hostname entered during installation](https://github.com/GluuFederation/community-edition-setup/commit/d505920d06614f70518607212eb610d646957f8e)

**Comment by yurem** [comment]
Now OpenLDAP CN=localhost
