### ISSUE TITLE
Update Saml script default parameters

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#215]
It's latest version of the script. We need to update default parameters to best fit for this script: https://github.com/GluuFederation/community-edition-setup/blob/master/templates/scripts.ldif#L1860

**Comment by mzico** [comment]
@yurem : How we should test it? There are two ways: 

 - Only SAML_Script ( no Asimba ) 
 - SAML script with Asimba. 

Do you think we should test both cases? 

Plus... Now... 'saml' script is named as 'asimba' in Custom Script configuration?

**Comment by nynymike** [comment]
Ideally both. But I'm not super concerned about QA-ing authentication scripts because they are easy to update post-release... i.e. just copy and paste new script.

**Comment by mzico** [comment]
@nynymike : Noted, thanks Sensei.
