### ISSUE TITLE
Deprecate cutom user object class

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#216]
We need to find in all places references to ox-XYZ custom object class in order to remove them.

**Comment by tecoholic** [comment]
@yurem Are you saying we don't need the ox-inumOrg objectclass at all? Can we remove that from the schema completely?

**Comment by tecoholic** [comment]
@yurem Need more information on this. Kindly update when you find time.

**Comment by yurem** [comment]
We don't support custom objcet OC-ORGINUM now. We need to remove it and sample customer attributes from schema

**Comment by yurem** [comment]
Fixed. https://github.com/GluuFederation/community-edition-setup/commit/ee964aec74ddd4b442d95560c7be63867e504265
