### ISSUE TITLE
Install JCE for Shibboleth v3

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/community-edition-setup#217]
https://wiki.shibboleth.net/confluence/display/IDP30/Installation

> If using the recommended Oracle JDK, make sure you've installed the Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files (see http://www.oracle.com/technetwork/java/javase/downloads/index.html, towards the bottom). If you don't do this, your deployment will be unable to make use of cryptographic algorithms such as AES with 256-bit keys which may be required for interoperability with some SPs.

**Comment by yurem** [comment]
Implemented in Beta5
