### ISSUE TITLE
Configure IdP v3 on Jetty behind Apache httpd

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/community-edition-setup#218]
>  ERROR [org.opensaml.saml.common.binding.security.impl.ReceivedEndpointSecurityHandler:200] - Message Handler:  SAML message intended destination endpoint 'https://v300.ubuntu14-shibv3.info/idp/profile/SAML2/Redirect/SSO' did not match the recipient endpoint 'http://v300.ubuntu14-shibv3.info/idp/profile/SAML2/Redirect/SSO'

[Running the IdP on Jetty behind Apache httpd](https://wiki.shibboleth.net/confluence/display/IDP30/Running+the+IdP+on+Jetty+behind+Apache+httpd)

**Comment by yurem** [comment]
Fixed, check if it works fine on new build with this update.
