### ISSUE TITLE
Add command to generate JWKS

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#219]
Tool which we need to include: https://github.com/mitreid-connect/json-web-key-generator

In the packaging process, we should run "mvn package" and just create a fold called `/opt/json-web-key-generator` that has the README.md and the jar with dependencies. We might also want to create a shell script that automatically runs the `java -jar ` command and just appends the extra CLI options.

**Comment by yurem** [comment]
I've checked what this tool do. We have similar our tool: KeyGenerator
It also supports command line parameters, etc.. We uses it and CE isntall to generate:
/etc/certs/oxauth-keys.json
/etc/certs/oxauth-keys.jks

I'm moving to 3.1 to make final decision about it later.

**Comment by yurem** [comment]
@qbert2k what do you think about this tool?

**Comment by mbaser** [comment]
We use our own key generation tool.
