### ISSUE TITLE
Setup don't run methods to configure indexes for attributes

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#222]
I didn't find in current setup places where we create indexes defined in this file:
https://github.com/GluuFederation/community-edition-setup/blob/version_2.4.4_sp2/static/opendj/opendj_index.json

Moreover there is no this file in 3.0.0

@tecoholic , is setup create indexes at setup?

**Comment by nynymike** [comment]
yes, this is a good point. The indexes are static in slapd.conf. They should be dynamically generated based on the json.

**Comment by tecoholic** [comment]
Since the index configuration is simply specifying it in `slapd.conf` we aren't relying on the `setup.py`. Is there a specific reason why we should maintain `index.json` instead of maintaining the index attribute list in the `slapd.conf`? If modularity is the issue. We can maintain a separate `index_list.conf` and add something like `include index_list.conf` in the `slapd.conf`.

**Comment by yurem** [comment]
I understand your point. It's up to you to choose best method.
But I think we need to try to keep _slapd.conf_ simpler and don't force developers to update it. This will protect us from unwanted  _slapd.conf_ changes. Also who knows if in future we decided to support other LDAP server too. I offer to generate list of indexes in setup and substitute in setup.
I offer to reuse our JSON format: https://github.com/GluuFederation/community-edition-setup/blob/version_2.4.4_sp1/static/opendj/opendj_index.json

Also there is 1 plus. Developers knows where to define new index already :)

**Comment by nynymike** [comment]
I'm ok with keeping indexes in slapd.conf 

The reason it was in JSON was that we had to iterate through the indexes, and run dsconfig, and JSON was easier for this purpose.

**Comment by yurem** [comment]
We might also need to run command to do initial indexing of all required attributes
slapindex -f /opt/symas/etc/openldap/slapd.conf -c uid

**Comment by tecoholic** [comment]
Not required. When the data is added ldapadd or modify the data is automatically indexed.
