### ISSUE TITLE
Custom attribute(s) not added to OpenLDAP

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/community-edition-setup#224]
Added the ff. to `/opt/gluu/custom.schema`:

```
attributeType ( oxAttribute:1003 NAME 'scimCustomFirst' 
	SUBSTR caseIgnoreSubstringsMatch EQUALITY caseIgnoreMatch
	SYNTAX 1.3.6.1.4.1.1466.115.121.1.15
	X-ORIGIN 'Gluu - dynamic registration custom attribute' )

attributeType ( oxAttribute:1004 NAME 'scimCustomSecond'
	SUBSTR caseIgnoreSubstringsMatch EQUALITY caseIgnoreMatch
	SYNTAX 1.3.6.1.4.1.1466.115.121.1.15
	X-ORIGIN 'Gluu - dynamic registration custom attribute' )
 
attributeType ( oxAttribute:1005 NAME 'scimCustomThird'
	SUBSTR caseIgnoreSubstringsMatch EQUALITY caseIgnoreMatch
	SYNTAX 1.3.6.1.4.1.1466.115.121.1.15
	X-ORIGIN 'Gluu - dynamic registration custom attribute' )
```

Also modified objectClass definition:

```
objectclass ( oxObjectClass:101 NAME 'oxAuthClientCustomAttributes' SUP top AUXILIARY MAY ( myCustomAttr1 $ myCustomAttr2 $ scimCustomFirst $ scimCustomSecond $ scimCustomThird ) X-ORIGIN 'Gluu - Custom objectclass' )
```

Restarted Gluu server and also executed:

```
GLUU.root@v300:/opt/symas/etc/openldap# /opt/symas/bin/slaptest -f /opt/symas/etc/openldap/slapd.conf -F /opt/symas/etc/openldap/slapd.d/
config file testing succeeded
GLUU.root@v300:/opt/symas/etc/openldap#
```

But when browsed in JXplorer, the new attributes does not show and `oxAuthClientCustomAttributes` objectClass not updated.

Tried also to register same attributes in oxTrust GUI, encountered an error.

**Comment by yurem** [comment]
These are all steps:
1. service solserver stop
2. Update OpenLDAP schema files
3. mv /opt/symas/etc/openldap/slapd.d /opt/symas/etc/openldap/slapd.d.bk01 where bk01 is backup index
4. mkdir -p /opt/symas/etc/openldap/slapd.d
5. opt/symas/bin/slaptest -f /opt/symas/etc/openldap/slapd.conf -F /opt/symas/etc/openldap/slapd.d
6. service solserver start

**Comment by yurem** [comment]
@willow9886 can you open issue in docs to add page about OpenLDAP schema customizations. In last comment there are list of steps which allows to do this

**Comment by willow9886** [comment]
Ok, will do.

**Comment by uboznikov** [comment]
I am encountering errors when registering custom attributes in oxTrust GUI that were successfully added to the schema. Build 32 ALPHA1 in Ubuntu 14.04.

![cant-add-custom-attr-oxtrust-gui](https://cloud.githubusercontent.com/assets/16329085/21255394/a1841b80-c3a6-11e6-9913-91f954c878a9.png)
