### ISSUE TITLE
CE 3.0.0 not start/stop rsyslog

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#231]
During gluu-server stop [script](https://github.com/GluuFederation/community-edition-package/blob/master/package/initd/gluu-server)  not checks if rsyslogd is up and as result not stop it

At startup gluu-server not run rsyslogd becuase there is no commands similar to [these ](https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L2185)to autostart it at chroot startup

**Comment by ganesh-at-wiw** [comment]
Added https://github.com/GluuFederation/community-edition-setup/commit/47902d20bde02b0925183192497c0daba00b2a00#diff-2eeaed663bd0d25b7e608891384b7298 for setup.py to let rsyslog start automatically with every start of gluu-server.

Added https://github.com/GluuFederation/community-edition-package/commit/1f8e28443f62d3626ae2268a96a295a7cbb08024#diff-5dfd552a9169b091ada6d476a7295596  to let rsyslog stop when gluu-server stops.

**Comment by yurem** [comment]
yes, according to updates this should work fine. I will check in new build

**Comment by zamilskhan** [comment]
RSyslog failing in 6-BETA2 package. Upon restart command got the following
```
[root@centos ~]# service gluu-server-3.0.0 restart
Shutting down Gluu Server...
Stopping Apache...
OK
Stopping Passport...
OK
Stopping oxAuth RP...
OK
Stopping Asimba...
OK
Stopping oxTrust...
OK
Stopping oxAuth...
Failed
Stopping RSyslog...
Failed
Stopping OpendLDAP...
OK

ERROR: Can't start gluu server.
HINT: Please manually remove /var/run/gluu-server-3.0.0.pid and unmount chroot container by running
rm -f /var/run/gluu-server-3.0.0.pid
df -aP | grep gluu-server-3.0.0 | awk '{print $6}' | xargs -I {} umount -l {}
```

**Comment by ganesh-at-wiw** [comment]
I've introduced further changes now.
https://github.com/GluuFederation/community-edition-package/commit/7e4f321b1caa06f04bf5217985d08a521b90177b#diff-5dfd552a9169b091ada6d476a7295596

This works as per my testing in Ubuntu 14.04.
