### ISSUE TITLE
There is warning at lastest CE install

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#235]
```
11:41:59 12/23/16 585d0d87 mdb_db_open: database "cn=accesslog" cannot be opened: No such file or directory (2). Restore from backup!
585d0d87 backend_startup_one (type=mdb, suffix="cn=accesslog"): bi_db_open failed! (2)
slap_startup failed (test would succeed using the -u switch)
```

After install CE works fine and config according to this is good too:
```
/opt/symas/bin/slaptest -f /opt/symas/etc/openldap/slapd.conf -F /opt/symas/etc/openldap/slapd.d
config file testing succeeded
```

**Comment by tecoholic** [comment]
I added the access log overlay. Let me check which verification is failing. The setup is tested. Nothing to worry about the functionality.

**Comment by yurem** [comment]
yes, CE woks fine. I wrote this in description of the issue. How we can fix this error at setup to avoid question about this in future?

**Comment by tecoholic** [comment]
@yurem this warning the thrown when we generate the `cn=config` directory in the line 2321 `self.run([self.slaptest, '-f', self.openldapSlapdConf, '-F', self.openldapCnConfig])`. This actually would throw 3 such errors for each `o=gluu`, `o=site` and `cn=accesslog` database suffixes. But when we import the ldif files from the templates, the DB file for `o=gluu` and `o=site` are created. But we don't import anything for the access log overlay, so the slaptest complains that the DB isn't available.

I will update with a fix.

**Comment by nynymike** [comment]
I thought we were not going to use cn=config db...

**Comment by tecoholic** [comment]
I remember we deciding to use the slapd.conf and also have cn=config generated after a talking with Symas. It would make a couple of things if we omit the cn=config. Do you want to disable the cn=config?

**Comment by tecoholic** [comment]
I am disabling the cn=config generation in setup.py. I have no clear benefits as of now to enable it by default. The admin can tweak the slapd.conf according to the needs and then generate it manually if he requires the On Line Configuration.

**Comment by nynymike** [comment]
Yes, enabling cn=config lead to confusion... we were updating slapd.conf, but the changes were not taking effect. I think disabling it by default is better, so anyone who enables it needs to really understand what they're doing.

**Comment by yurem** [comment]
There is no this error message in latest setup. Thanks!
