### ISSUE TITLE
OpenLDAP should listen on localhost only

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#236]
IN CE for security reasons OpenLDAP should bind to localhost only by default.

**Comment by tecoholic** [comment]
Presently the configuration in the [symas-openldap.conf](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/symas-openldap.conf) file is this

```
HOST_LIST="ldaps://%(ip)s:1636/ ldaps://127.0.0.1:1636/ ldapi:///"
```

Do you want to restrict this to `ldaps://127.0.0.1:1636` ? Wouldn't that render the editing LDAP in case of oxTrust lockout or troubleshooting?

**Comment by yurem** [comment]
For me it's better to restrict access to all services expect Apache https port by default. If customer need access to LDAP from remote server he should manually add host and ACI rules if needed.

**Comment by nynymike** [comment]
yes, ldap should be only `ldaps://127.0.0.1:1636`  If a customer wants to diverge from this config, they can modify `slapd.conf` post-installation
