### ISSUE TITLE
Enable openldap logging in 3.0.0 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#238]
There is no logging enabled for openldap at this moment. OpenLDAP logs should be inside '/var/symas/openldap-log' ( according to Symas documentation ).

**Comment by mzico** [comment]
@zamilskhan  got one log here... 

```
GLUU.root@proxy:/var/log/openldap# pwd
/var/log/openldap
GLUU.root@proxy:/var/log/openldap# ls
ldap.log
GLUU.root@proxy:/var/log/openldap# tail -n 10 ldap.log 
Dec 24 18:50:00 proxy slapd[3337]: conn=1005 fd=24 closed (connection lost)
Dec 24 18:50:00 proxy slapd[3337]: conn=1006 fd=25 closed (connection lost)
Dec 24 18:50:01 proxy slapd[3337]: conn=1000 fd=11 closed (connection lost)
Dec 24 18:50:01 proxy slapd[3337]: conn=1001 fd=20 closed (connection lost)
Dec 24 18:50:01 proxy slapd[3337]: conn=1002 fd=21 closed (connection lost)
Dec 24 18:50:01 proxy slapd[3337]: conn=1003 fd=22 closed (connection lost)
Dec 24 18:50:01 proxy slapd[3337]: conn=1007 fd=26 closed (connection lost)
Dec 24 18:50:02 proxy slapd[3337]: daemon: shutdown requested and initiated.
Dec 24 18:50:02 proxy slapd[3337]: slapd shutdown: waiting for 0 operations/tasks to finish
Dec 24 18:50:02 proxy slapd[3337]: slapd stopped.
GLUU.root@proxy:/var/log/openldap# 
```

**Comment by nynymike** [comment]
openldap uses syslog. We need to configure syslog to send slapd messages to a different file.

You can also use the [-l syslog-local-user] option to slapd
slapd -l LOCAL3 for exemple and then put in your syslog.conf a line:
local3.*       /var/log/ldap.log

from 
http://www.openldap.org/lists/openldap-software/200210/msg00269.html

**Comment by tecoholic** [comment]
OpenLDAP logging and Log rotation has been added and is working. See 490c6cddd397cbda428a2015331e9c9885984f51 and 855020d5bc84e8be5358a1d7a45c71b87a10c4ad

The logs are presently stored in `/var/log/openldap`. Is this ticket specifically asking for the location to conform to Symas defined location? If so, it can be changed. Otherwise kindly close this issue as resolved.

**Comment by tecoholic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Setup Symas OpenLDAP](https://trello.com/c/jwifOhE5/575-setup-symas-openldap)

**Comment by mzico** [comment]
@tecoholic 
>> The logs are presently stored in /var/log/openldap.

This log is showing startup and shutdown messages only; if I don't miss anything. 

We need access log, audit log as well to troubleshoot various ldap related issues.

**Comment by tecoholic** [comment]
Current Status:
- [x] System Log
- [x] Access Log
- [ ] Audit Log

**Comment by tecoholic** [comment]
> This log is showing startup and shutdown messages only; if I don't miss anything.

`/var/log/openldap/ldap.log` is configured as `loglevel stats sync` so it should be logging all search, and modify operations along with the connections. For example, here is what I observe:

```
Jan  6 17:02:42 gluu slapd[15331]: conn=1000 op=34 SEARCH RESULT tag=101 err=0 duration=0.330ms nentries=1 text=
Jan  6 17:02:42 gluu slapd[15331]: conn=1001 op=33 SRCH base="inum=@!1CE4.3F1B.D138.2F6A!0002!E2BE.9283,ou=appliances,o=gluu" scope=0 deref=0 filter="(objectClass=*)"
Jan  6 17:02:42 gluu slapd[15331]: conn=1001 op=33 SRCH attr=oxAuthenticationMode
Jan  6 17:02:42 gluu slapd[15331]: conn=1001 op=33 SEARCH RESULT tag=101 err=0 duration=0.192ms nentries=1 text=
Jan  6 17:02:42 gluu slapd[15331]: conn=1000 op=35 SRCH base="ou=oxauth,ou=configuration,inum=@!1CE4.3F1B.D138.2F6A!0002!E2BE.9283,ou=appliances,o=gluu" scope=0 deref=0 filter="(objectClass=*)"
Jan  6 17:02:42 gluu slapd[15331]: conn=1000 op=35 SRCH attr=oxRevision
Jan  6 17:02:42 gluu slapd[15331]: conn=1000 op=35 SEARCH RESULT tag=101 err=0 duration=0.197ms nentries=1 text=
Jan  6 17:02:42 gluu slapd[15331]: conn=1001 op=34 SRCH base="ou=scripts,o=@!1CE4.3F1B.D138.2F6A!0001!1EFC.1905,o=gluu" scope=2 deref=0 filter="(&(&(objectClass=top)(objectClass=oxCustomScript))(|(oxScriptType=person_authentication)(oxScriptType=client_registration)(oxScriptType=id_generator)(oxScriptType=uma_authorization_policy)(oxScriptType=application_session)(oxScriptType=dynamic_scope)))"
Jan  6 17:02:42 gluu slapd[15331]: conn=1001 op=34 SRCH attr=dn inum oxRevision oxScriptType oxModuleProperty gluuStatus
Jan  6 17:02:42 gluu slapd[15331]: conn=1001 op=34 SEARCH RESULT tag=101 err=0 duration=1.406ms nentries=20 text=
```

The above commit added the audit logging and it can be found in `/var/log/openldap/auditlog.ldif`. LDIF, well, because audit log overlay uses ldif format to store the info.
