### ISSUE TITLE
gluu-server-3.0.0_3-BETA2 for Ubuntu 14.04 removes whole /opt when using --purge option

### ISSUE THREAD

**Issue by ganesh-at-wiw** [GluuFederation/community-edition-setup#242]
Below are the commands to see what happens...

```
root@localhost:~# apt-get remove gluu-server-3.0.0 --purge
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  gluu-server-3.0.0*
0 upgraded, 0 newly installed, 1 to remove and 3 not upgraded.
After this operation, 1,130 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 91231 files and directories currently installed.)
Removing gluu-server-3.0.0 (3-BETA2~trusty+Ub14.04) ...
Checking to make sure Gluu Server is down...
Shutting down Gluu Server...

Your changes will be saved into /opt/gluu-server-3.0.0.saved
Purging configuration files for gluu-server-3.0.0 (3-BETA2~trusty+Ub14.04) ...
Your changes will be saved into /opt/gluu-server-3.0.0.saved
root@localhost:~# ls /opt
ls: cannot access /opt: No such file or directory
root@localhost:~# 

```

**Comment by adrian-gluu** [comment]
i made a fix in our latest built:
https://repo.gluu.org/ubuntu/pool/main/trusty-devel/gluu-server-3.0.0_5-BETA2~trusty+Ub14.04_amd64.deb

**Comment by yurem** [comment]
The fix not helps to fix this.

I've checked how dpkg removes package. In this process we not control backup of changed files.
It's package manager responsibility. And it works as expected when you specify '-r' option.

I thin we have 3 solutions:
1. Do full backup of /opt/gluu-server-3.0.0 folder if user specify '-P' option.
2. Don't allow to call uninstall with '-P' from preuininstall script
3. Allow dpkg manager do his work:
  - make /opt/gluu-server-3.0.0.save if user call uninstall script
  - remove everything if he call uninstall with "--purge" option

I vote for option 3. Please reopen this issue if you have another point of view on this issue
