### ISSUE TITLE
Add external configuration file which contains list of indexes whoich setup should add to OpenLDAP

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#245]
We need to add simular to this file into setup.py again
https://github.com/GluuFederation/community-edition-setup/blob/version_2.4.4_sp2/static/opendj/opendj_index.json

It's better to keep indexes configuration in this self explanatory format than update openldap configuration.

**Comment by tecoholic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add external configuration file which contains list of indexes whoich setup should add to OpenLDAP Setup #245](https://trello.com/c/nzMAlug5/57-add-external-configuration-file-which-contains-list-of-indexes-whoich-setup-should-add-to-openldap-setup-245)
