### ISSUE TITLE
Remove CAS as install option

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/community-edition-setup#247]
Shibboleth CAS protocol support only.

**Comment by yurem** [comment]
@nynymike I'm not sure that we need to completely remove CAS from CE until someone will test and told that IDP3+CAS provides same functionality. As far as I know we don't have IDP3+CAS configuration options in GUI and I'm not sure that it works as CAS out of the box.

**Comment by yurem** [comment]
I'm moving it to CE 3.1

**Comment by dmogn** [comment]
https://github.com/GluuFederation/community-edition-setup/issues/252

**Comment by dmogn** [comment]
CAS install option has been removed in setup.py menu since v3.0.0. 
We haven't bugreports for CAS via Shibboleth (> 2 month after release). So now we can complete remove old CAS from the installer.
Now it is safe.

**Comment by dmogn** [comment]
Done
