### ISSUE TITLE
Hide CAS installation by default

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#252]
I offer to not remove it from CE 3.0.0. We can remove it from 3.1.0
But hide this option.
For example in order to active it admin should enter
./setup.py --allowDeprecatedApplications

**Comment by dmogn** [comment]
Gluu installer has "--allow_pre_released_applications" flag.
I've created the flag with "--allow_deprecated_application" name, for same style keeping.

**Comment by dmogn** [comment]
Done.
