### ISSUE TITLE
CAS service start failed on Ubuntu 14.04

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/community-edition-setup#253]
GLUU.root@ce:~# service cas start
Starting Jetty: FAILED Tue Jan 17 15:09:12 UTC 2017
GLUU.root@ce:~# service cas stop 
Stopping Jetty: start-stop-daemon: warning: failed to kill 3386: No such process
1 pids were not killed
No process in pidfile '/var/run/cas.pid' found running; none killed.
OK
GLUU.root@ce:~#

No files in ...../cas/logs/ directory.

@yurem told me, that on redhat the service works well, so the problem is ubuntu-specific.
The problem detected since ~ 3.0.0 beta2. Early builds works well.

PS. CAS will be removed in v3.1 https://github.com/GluuFederation/community-edition-setup/issues/247.

**Comment by yurem** [comment]
I fixed this in: https://github.com/GluuFederation/community-edition-setup/commit/bccaee7bd121b8d31e6facfc9a13236d38fb354a

It happened when we installed all CE components with 3Gb only: As result java parameters were wrong:
-Xms256m -Xmx153m

After fix:
-Xms128m -Xmx153m

2.Beta3 contains this fix

Also lack of VM memory led to random applications shutdowns when during CE initial we specified more memory than VM can physically allocate.
