### ISSUE TITLE
Generate OP signing keys

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#254]
To support https://github.com/GluuFederation/oxAuth/issues/445 we need to generate OP signing keys.

**Comment by mbaser** [comment]
We use our own key generation tool.

**Comment by mbaser** [comment]
Accidentally closed this instead of https://github.com/GluuFederation/community-edition-setup/issues/219

**Comment by mbaser** [comment]
Related issue https://github.com/GluuFederation/oxAuth/issues/445 was closed
