### ISSUE TITLE
Restart command is not working - Ubuntu 14.04 

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/community-edition-setup#256]
root@ubuntu:/home/gluu# /etc/init.d/gluu-server-3.0.0 restart
Shutting down Gluu Server...
Stopping Apache...
OK
Stopping Passport...
OK
Stopping oxAuth RP...
OK
Stopping Asimba...
OK
Stopping CAS...
OK
Stopping IDP...
OK
Stopping oxTrust...
OK
Stopping oxAuth...
OK
Stopping OpendLDAP...
OK

ERROR: Can't start gluu server.
HINT: Please manually remove /var/run/gluu-server-3.0.0.pid and unmount chroot container by running
rm -f /var/run/gluu-server-3.0.0.pid
df -aP | grep gluu-server-3.0.0 | awk '{print $6}' | xargs -I {} umount -l {}
root@ubuntu:/home/gluu#

**Comment by yurem** [comment]
Which deb/rpm you used to test this?

**Comment by yurem** [comment]
Are there any feedback about beta4?

**Comment by yurem** [comment]
FIxed: https://github.com/GluuFederation/community-edition-package/commit/8fe62ebb3f894239b4c8552868cac93798dfaab9
