### ISSUE TITLE
100% space usage when back up taken with Gluu service running

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/community-edition-setup#263]
1. Keep Gluu services running
2. Take backup with "tar cvf gluu244-backup.tar /opt/gluu-server-2.4.4/" for 2.4.4
tar cvf gluu3000-backup.tar /opt/gluu-server-3.0.0/

gluu-server-3.0.0/proc/scsi/sg/device_hdr
gluu-server-3.0.0/proc/scsi/sg/device_strs
gluu-server-3.0.0/proc/scsi/sg/def_reserved_size
gluu-server-3.0.0/proc/scsi/scsi
gluu-server-3.0.0/proc/scsi/mptspi/
gluu-server-3.0.0/proc/scsi/mptspi/2
gluu-server-3.0.0/proc/scsi/device_info
gluu-server-3.0.0/proc/stat
gluu-server-3.0.0/proc/iomem
gluu-server-3.0.0/proc/kcore [..here space used 100%]
^C
root@ubuntu:/opt#

gluu@ubuntu:~$ df -h ./;date
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        78G   19G   56G  25% /
Wed Feb  1 18:15:36 PST 2017
gluu@ubuntu:~$ df -h ./;date
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        78G   20G   55G  27% /
Wed Feb  1 18:15:39 PST 2017
gluu@ubuntu:~$ df -h ./;date
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        78G   22G   53G  29% /
Wed Feb  1 18:15:41 PST 2017
gluu@ubuntu:~$ df -h ./;date
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        78G   24G   51G  32% /
Wed Feb  1 18:16:41 PST 2017
gluu@ubuntu:~$ df -h ./;date
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        78G   24G   51G  32% /
Wed Feb  1 18:16:42 PST 2017

Verified on both 2.4.4.2 and 3.0.0 versions

**Comment by willow9886** [comment]
@sahiliamsso is reporting that backups work properly when you stop the Gluu Server, but it's important that an organization is able to backup the server without stopping the server. The service needs to remain available even while backup is taking place.

**Comment by yurem** [comment]
@sahiliamsso It's  normal behavior of tar command why you add /proc or /dev or /sys patches.

These special file systems provides RAW access to disk partiions, also you can read memory, etc..

In order to make backup using this approach you need to add "--exclude=" parameters to exclude:
./gluu-server-3.0.0/proc/
./gluu-server-3.0.0/mnt/
./gluu-server-3.0.0/sys/
./gluu-server-3.0.0/dev/
