### ISSUE TITLE
setup.py - using an Ampersand (&) in admin password field fails

### ISSUE THREAD

**Issue by paulsorensenmagnet** [GluuFederation/community-edition-setup#268]
FROM Script:

Optional: enter password for oxTrust and LDAP superuser [VbLh1SQKDthS] : TEst&lu321

...

Proceed with these values [Y|n] y
Downloading Asimba war file...
Downloading oxAuth RP war file...
Downloading JCE 1.8 zip file...
sh: 1: lu321: not found

**Comment by ganesh-at-wiw** [comment]
Provided the fix in 3.0.0, 3.0.1 and 3.0.2.
These are the changes: https://github.com/GluuFederation/community-edition-setup/commit/e3fc8d56fa54045ae276a6db610c9bbbe260df60
But now in 3.1.0 new method: **obscure** is in use.

**Comment by mzico** [comment]
@ganesh-at-wiw : It's fixed.
