### ISSUE TITLE
Don't update /etc/hosts in old dist

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#270]
In CentOS 6.7/RHEL 6.7 during install we get error messages in logs:
07:48:18 02/27/17 Running: /bin/chmod -R 644 /etc/hosts /etc/hostname

07:48:18 02/27/17 /bin/chmod: cannot access `/etc/hostname': No such file or directory

...
second time: 07:48:52 02/27/17 /bin/chmod: cannot access `/etc/hostname': No such file or directory

Setup should check if there is this file in chroot befre trying to apply permissions

**Comment by ganesh-at-wiw** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/173b7ea53f86b656fac7f47a2d13518e9c45fec1#diff-2eeaed663bd0d25b7e608891384b7298
