### ISSUE TITLE
Wrong user:group during rsyslog configuraion

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#271]
CentOS 6.7/RHEL 6.7:

07:48:36 02/27/17 /bin/chown: invalid user: `syslog:adm'

CentOS 7.0/RHEL 7.0:
23:52:59 02/26/17 /bin/chown: invalid user: вЂsyslog:admвЂ™

Debian 8.4:
13:56:45 01/06/17 /bin/chown: invalid user: 'syslog:adm'

Only in Ubuntu 14.04/16.04 there is no errors.

Setup should take into consideration OS dist before running this 'chown' command.

**Comment by ganesh-at-wiw** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/65608c472c1997cd9ea84cca85fd5f71f3969ca0#diff-2eeaed663bd0d25b7e608891384b7298
