### ISSUE TITLE
Failed to stop Gluu services properly in RHEL 6.7

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#272]
These process still up after uninstalling CE 3.0.1:
rtkit     16544      1  0 00:26 ?        00:00:00   memcached -d -p 11211 -u memcached -m 64 -c 1024 -P /var/run/memcached/memcached.pid
root      16573      1  0 00:26 ?        00:00:00   /sbin/rsyslogd -i /var/run/syslogd.pid -c 5
496       16600      1  0 00:26 ?        00:00:00   /opt/symas/lib64/slapd -u ldap -g ldap -h ldaps://127.0.0.1:1636/

Also after installing package there is one process inside RHEL 6.7 chroot. We need to uninstall sshd from CE chcroot

root       8454   2470  0 Feb26 ?        00:00:06     sshd: root@notty
root       8458   8454  0 Feb26 ?        00:00:01       /usr/libexec/openssh/sftp-server
root      13554   2470  0 00:14 ?        00:00:05     sshd: root@notty
root      13558  13554  0 00:14 ?        00:00:00       /usr/libexec/openssh/sftp-server
root      13755   2470  0 00:16 ?        00:00:00     sshd: root@pts/1

**Comment by ganesh-at-wiw** [comment]
The rsyslogd and memcached process are from the host server not from chroot container. LDAP process is not seen when service gluu-server-3.0.1 is stopped.

So, it's fine for me.
Next I'll update after uninstalling the rpm.

**Comment by ganesh-at-wiw** [comment]
To me this all is fine even after uninstalling the rpm.

> [root@localhost ~]# ps -eaf|egrep "rsyslogd|memcached|ldap"
> root      1145     1  0 00:49 ?        00:00:00 /sbin/rsyslogd -i /var/run/syslogd.pid -c 5
> saslauth  4686     1  0 01:01 ?        00:00:00 memcached -d -p 11211 -u memcached -m 64 -c 1024 -P /var/run/memcached/memcached.pid
> pulse     4709     1  0 01:01 ?        00:00:00 /opt/symas/lib64/slapd -u ldap -g ldap -h ldaps://127.0.0.1:1636/
> root      5303  2247  0 01:04 pts/0    00:00:00 egrep rsyslogd|memcached|ldap
> [root@localhost ~]# yum remove gluu-server-3.0.1
> Loaded plugins: fastestmirror, refresh-packagekit, security
> Setting up Remove Process
> y
> Resolving Dependencies
> --> Running transaction check
> ---> Package gluu-server-3.0.1.x86_64 0:2-1.centos6 will be erased
> --> Finished Dependency Resolution
> 
> Dependencies Resolved
> 
> ========================================================================================================================================================================
>  Package                                Arch                        Version                           Repository                                                   Size
> ========================================================================================================================================================================
> Removing:
>  gluu-server-3.0.1                      x86_64                      2-1.centos6                       @/gluu-server-3.0.1-2-1.centos6.x86_64                      979 M
> 
> Transaction Summary
> ========================================================================================================================================================================
> Remove        1 Package(s)
> 
> Installed size: 979 M
> Is this ok [y/N]: Downloading Packages:
> Running rpm_check_debug
> Running Transaction Test
> Transaction Test Succeeded
> Running Transaction
> Checking if Gluu Server isn't running...
>   Erasing    : gluu-server-3.0.1-2-1.centos6.x86_64                                                                                                                 1/1 
> warning:    erase unlink of /opt/gluu-server-3.0.1/var/lock/subsys/httpd failed: No such file or directory
> warning:    erase unlink of /opt/gluu-server-3.0.1/var/lib/rpm/__db.004 failed: No such file or directory
> warning:    erase unlink of /opt/gluu-server-3.0.1/var/lib/rpm/__db.003 failed: No such file or directory
> warning:    erase unlink of /opt/gluu-server-3.0.1/var/lib/rpm/__db.002 failed: No such file or directory
> warning:    erase unlink of /opt/gluu-server-3.0.1/var/lib/rpm/__db.001 failed: No such file or directory
> warning:    erase unlink of /opt/gluu-server-3.0.1/etc/rc.d/rc5.d/K45memcached failed: No such file or directory
> warning:    erase unlink of /opt/gluu-server-3.0.1/etc/rc.d/rc4.d/K45memcached failed: No such file or directory
> warning:    erase unlink of /opt/gluu-server-3.0.1/etc/rc.d/rc3.d/K45memcached failed: No such file or directory
> warning:    erase unlink of /opt/gluu-server-3.0.1/etc/rc.d/rc2.d/K45memcached failed: No such file or directory
> Your changes will be saved into /opt/gluu-server-3.0.1.rpm.saved
>   Verifying  : gluu-server-3.0.1-2-1.centos6.x86_64                                                                                                                 1/1 
> 
> Removed:
>   gluu-server-3.0.1.x86_64 0:2-1.centos6                                                                                                                                
> 
> Complete!
> [root@localhost ~]# ps -eaf|egrep "rsyslogd|memcached|ldap"
> root      1145     1  0 00:49 ?        00:00:00 /sbin/rsyslogd -i /var/run/syslogd.pid -c 5
> root      5866  2247  0 01:05 pts/0    00:00:00 egrep rsyslogd|memcached|ldap
> [root@localhost ~]# 
> 

Please provide similar output before and after uninstall.

**Comment by ganesh-at-wiw** [comment]
I'm closing this issue.
If need be we can reopen this.
