### ISSUE TITLE
Faield to start rsyslog in RHEL 7.2

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#273]
03:23:36 02/27/17 Failed to restart rsyslog.service: Unit not found.

It looks like we not nonallied rsyslog package inside chroot

**Comment by ganesh-at-wiw** [comment]
Starting work on this. So far as I remember the package was available for Ubuntu 14.04 and CentOS 6.8.

**Comment by ganesh-at-wiw** [comment]
Starting work on this. So far as I remember the package was available for Ubuntu 14.04 and CentOS 6.8.

**Comment by ganesh-at-wiw** [comment]
We need to install rsyslog inside chroot of RHEL 7.

After my testing with RHEL7, I see that, if rsyslog is installed then this error is not encountered in setup.log and setup_error.log:

-bash-4.2# grep rsyslog setup.log 
00:59:15 03/11/17 Copied ./static/openldap/openldap-syslog.conf to /etc/rsyslog.d/
00:59:22 03/11/17 Running: /usr/bin/systemctl restart rsyslog.service
-bash-4.2# grep rsyslog setup_error.log 
-bash-4.2#

**Comment by ganesh-at-wiw** [comment]
@adrian-gluu, bro can you please install the package rsyslog inside the chroot of RHEL?
This will help the error from appearing in logs.

**Comment by adrian-gluu** [comment]
in RHEL or Centos rsyslog is integrated already in a different way instead of /var/log/syslog you have /var/log/messages

**Comment by adrian-gluu** [comment]
@ganesh-at-wiw can you check if /var/log/messages exist for you?

**Comment by ganesh-at-wiw** [comment]
I meant @adrian-gluu that the package itself does not exist.
That's why the message appears.

And Yes, the file exists as below:

```
[root@localhost ~]# ls /opt/gluu-server-3.0.1/var/log/messages 
/opt/gluu-server-3.0.1/var/log/messages
[root@localhost ~]# 


```

**Comment by ganesh-at-wiw** [comment]
Also, in CentOS 7, we have rsyslog package.
In RHEL 7, we don't have.

**Comment by adrian-gluu** [comment]
syslog is integrated on centos and rhel in a different way if you have /var/log/messages thats it

**Comment by adrian-gluu** [comment]
I will try to install rsyslog manually inside of RHEL chroot

**Comment by adrian-gluu** [comment]
yum --installroot=/opt/gluu-ce-rpm-311/gluu-server-3.1.1/ install rsyslog
Installed:
  rsyslog.x86_64 0:8.24.0-12.el7

rsyslog is in place now
