### ISSUE TITLE
OpenDJ fails to stop in CentOS 7.2

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/community-edition-setup#278]
Manual upgrade to 3.0.1 Opendj was followed. OpenDJ does not stop. The same issue was not found in CentOS 6.8. Please follow the [manual update procedure](https://github.com/GluuFederation/docs-3.0.1/blob/master/source/upgrade/manual-update.md) and stop container. See [Trello ticket](https://trello.com/c/TxGQZEr1/722-qa-3-0-0-opendj-not-stopping)

**Comment by yurem** [comment]
I think we can deprecate this issue
