### ISSUE TITLE
Render /etc/security/limits.conf

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#28]
There are recommendations about Max Open Files. I think we need to render in setup /etc/security/limits.conf file. Also during setup we should check host VM config:
cat /proc/sys/fs/file-max
We need to check if the system has enough file descriptors available overall.

These are sample values for production with high load:
 /etc/security/limits.config
opendj soft nofile 65536
opendj hard nofile 131072

**Comment by nynymike** [comment]
Also, this needs to be done in the host system, not just the chroot instance. As the chroot container is run as root, I'm not sure if the limits need to be set for the system in general.
