### ISSUE TITLE
import30.py is not importing SPs

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#280]
- Situation: Grabbed 'backup24' from 2.4.4 sp2 Server. Directory 'ssl' was missing in /backup_24/opt/idp/ssl/

Tried to use import30.py in one 3.0.1 server which has OpenLDAP. Results are: 

 - import30.py throw error: 
```
NFO     Copying Shibboleth IDP files...
Traceback (most recent call last):
  File "./import30.py", line 599, in <module>
    migrator.migrate()
  File "./import30.py", line 584, in migrate
    self.copyIDPFiles()
  File "./import30.py", line 572, in copyIDPFiles
    '/opt/shibboleth-idp/ssl')
  File "/usr/lib64/python2.7/distutils/dir_util.py", line 128, in copy_tree
    "cannot copy tree '%s': not a directory" % src
distutils.errors.DistutilsFileError: cannot copy tree 'backup_24/opt/idp/ssl': not a directory
``` 

     - This can resolved by manually inserting 'ssl' directory inside /backup_24/opt/idp/

- After that... 
   - No SP configurations are inserted in OpenLDAP tree. 
  - I can see files are migrated inside /opt/shibboleth-idp/
  - As there is no configuration of SPs inside OpenLDAP 'ou=trustRelationships....,ou=appliances,o=gluu' so there is no SP active in 3.0.1 oxTrust + Shibboleth-IDP.

**Comment by tecoholic** [comment]
@mzico There is no way data exported as LDIF from 2.4.4 would go missing from 3.0.1 after import. There will be log entries, if that happens. I haven't seen such an error in the logs.

I think the information was stored in files in 2.4.4 and then moved to the LDAP in version 3. I would need developer input if that is the case to transform the config from  XML file to the LDIF file.

**Comment by mzico** [comment]
>> There is no way data exported as LDIF from 2.4.4 would go missing from 3.0.1 after import. There will be log entries, if that happens. I haven't seen such an error in the logs.

@tecoholic : Ok that is a promising statement. However it happened. Lemme know how I can show you that. May be we can have a quick screen sharing meeting sometime? I'll show you.

**Comment by tecoholic** [comment]
I tested again creating SP in 2.4.4 and migrating the data to 3.0.1. I noticed that the SP config in LDAP is available after migration. However oxTrust doesn't provide the ways to check the presence of the SPs. The links don't appear under the `Outbound` section.
![gluu](https://cloud.githubusercontent.com/assets/383862/26736174/973c4b8c-47e2-11e7-9fed-8c410647542d.png)

Will investigate further and update the findings or fix.

**Comment by tecoholic** [comment]
@mzico I noticed that there are changes in ways Shibboleth V2 and V3 handles the configurations. It's [migration guide from v2 to v3](https://wiki.shibboleth.net/confluence/display/IDP30/UpgradingFromV2) outlines the differences. Can you take a look at it and help me decide if need to migrate the configs or not?

**Comment by mzico** [comment]
@zamilskhan  or @sahiliamsso : Can anyone of you test how it's doing now?

**Comment by tecoholic** [comment]
This has been fixed with some updates to the setup, import and export scripts. Now the migration of SPs happen smoothly between 2.4.4 to 3.0.x.
