### ISSUE TITLE
Update eduPerson OpenLDAP schema

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#283]
The correct schema for OpenLDAP eduperson can be found here:
https://spaces.internet2.edu/display/macedir/OpenLDAP+eduPerson

The current schema is missing attributes like `eduPersonScopedAffiliation`

**Comment by yurem** [comment]
@nynymike are you offer to replace OpenLDAP schema file /opt/symas/etc/openldap/schema/eduperson.schema with right one?

**Comment by yurem** [comment]
@nynymike in which version and part there is this issue. According to [this](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/oxtrust-config.json#L18):
```
    "personObjectClassTypes":[
        "gluuCustomPerson",
        "gluuPerson",
        "eduPerson"
],
```
oxTrust should create person entries with these OC.

**Comment by yurem** [comment]
@aliaksander-samuseu 
Is original issue https://github.com/GluuFederation/oxTrust/issues/499 not resolved yet?

![image](https://cloud.githubusercontent.com/assets/6104200/24909042/1121ac1c-1ecb-11e7-8a68-db85e7a30f45.png)

This is from ce-dev3 CE 3.0.1 server...

**Comment by ganesh-at-wiw** [comment]
I see eduPerson OC in openldap installation.
It has 8 attributes instead of 11 attributes suggested in the link @nynymike provided.
I'm holding off till we get Mike's answer.

**Comment by mzico** [comment]
@ganesh-at-wiw @nynymike @yurem : [This](https://github.com/GluuFederation/support-docs/blob/master/tmp/openldap/ePSA_schema.md) might be a workaround.

**Comment by aliaksander-samuseu** [comment]
@yurem 

>Is original issue GluuFederation/oxTrust#499 not resolved yet?

It's resolved in 3.0.1, but the same issue exists in 2.4.4 too, and is not resolved yet. I tested for [this archive](https://ox.gluu.org/maven/org/xdi/oxtrust-server/2.4.4.sp3/oxtrust-server-2.4.4.sp3.war) and by updating to SP3 with updater package from repos.

**Comment by ganesh-at-wiw** [comment]
Do we intend to make any changes for 2.4.4 now, or is it customer need based?

In case it's customer need based, we can close this issue.

**Comment by ganesh-at-wiw** [comment]
No further inputs received.
Closing it for now.
