### ISSUE TITLE
Don't index binary tokens

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/community-edition-setup#284]
See issue https://github.com/GluuFederation/oxAuth/issues/194

We have to pick either string or binary for the attribute type. If there are two different types of tokens then the only solution might be to create two different attributes.

**Comment by tecoholic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Don't index binary tokens Setup #284](https://trello.com/c/PKf2Uk17/51-dont-index-binary-tokens-setup-284)

**Comment by mbaser** [comment]
I looked at indexes, currently we don't have any indexes for binaries. Closing.
