### ISSUE TITLE
Ubuntu 14.04 (Trusty) installation not working

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/community-edition-setup#29]
Hi, I am using Ubuntu gluu-server package to configure gluu server on my ec2 instance. I followed the guide from here

http://www.gluu.org/docs/admin-guide/installation/ubuntu/

and successfully installed the server.

I have attached my setup.log and setup_error.log files to this ticket.

After login when I run ./setup.py. I entered following information

Enter IP Address [172.31.6.167] : 52.11.124.214
Enter hostname [ce.gluu.info] : ec2-52-11-124-214.us-west-2.compute.amazonaws.com
Enter your city or locality : Islamabad
Enter your state or province two letter code : IS
Enter two letter Country Code : PK
Enter Organization Name : Gluu
Enter email address for support at your organization : rahat.jaan@gmail.com
Enter maximum RAM for tomcat in MB [1536] :
Optional: enter password for oxTrust and LDAP superuser [047QJv6PycHh] :
Update the hostname, hosts, and resolv.conf files? [No] :
Install oxAuth OAuth2 Authorization Server? [Yes] :
Install oxTrust Admin UI? [Yes] :
Install Gluu OpenDJ LDAP Server? [Yes] :
Install Apache HTTPD Server [Yes] :
Install Shibboleth 2 SAML IDP? [No] :
Install Asimba SAML Proxy? [No] :
Install CAS? [No] :

and apparently everything is configured and working fine. But when looked at /home/gluu-server/opt/apache-tomcat-7.0.55/logs/oxtrust.log file

I can see error related to LDAP connection
"
LDAPException(resultCode=91 (connect error), errorMessage='An error occurred while attempting to connect to server localhost:1636: java.io.IOException: An error occurred while attempting to estabish"

After looking at the exception I checked /opt/opendj/logs/server.out

and I can see this

"

[02/Apr/2015:17:44:36 +0000] category=PROTOCOL severity=NOTICE msgID=2556180 msg=Started listening for new connections on Administration Connector 0.0.0.0 port 4444
[02/Apr/2015:17:44:36 +0000] category=PROTOCOL severity=NOTICE msgID=2556180 msg=Started listening for new connections on LDAP Connection Handler 0.0.0.0 port 1389
[02/Apr/2015:17:44:36 +0000] category=PROTOCOL severity=NOTICE msgID=2556180 msg=Started listening for new connections on LDAPS Connection Handler 0.0.0.0 port 1636"

That tells the opendj is working fine.

Can you please help me resolve this issue somehow.

Thanks

**Comment by mzico** [comment]
Rahat, 

What kind of problem you are observing. I mean, isn't IDP loading in your browser or are you getting some error after login there?

**Comment by willow9886** [comment]
Closing this...
