### ISSUE TITLE
Setup should allow to install CE without LDAP

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#291]
Right now there are 2 type of issues which we need to resolve to allow install CE without LDAP:

1. 
```
18:01:04 05/03/17 Found package '/opt/dist/symas/symas-openldap-gluu.amd64_2.4.44-20161020_amd64.deb' for install
18:01:04 05/03/17 Running: /usr/bin/dpkg --install /opt/dist/symas/symas-openldap-gluu.amd64_2.4.44-20161020_amd64.deb

```

2.
```
18:01:06 05/03/17 Running: /bin/su ldap -c cd /install/community-edition-setup; /opt/symas/bin/slapadd -b o=gluu -f /opt/symas/etc/openldap/slapd.conf -l ./output/base.ldif
18:01:06 05/03/17 590a1ae2 /opt/symas/etc/openldap/slapd.conf: line 167: invalid path: No such file or directory
slapadd: bad configuration file!

18:01:06 05/03/17 Running: /bin/su ldap -c cd /install/community-edition-setup; /opt/symas/bin/slapadd -b o=gluu -f /opt/symas/etc/openldap/slapd.conf -l ./output/appliance.ldif
18:01:06 05/03/17 590a1ae2 /opt/symas/etc/openldap/slapd.conf: line 167: invalid path: No such file or directory
slapadd: bad configuration file!
...
```

**Comment by ganesh-at-wiw** [comment]
Wow, but how would CE work without LDAP?

**Comment by tecoholic** [comment]
By configuring the ox-ldap.properties file to point to external LDAP server. Multiple oxAuth installations can point to same LDAP server :)

**Comment by ganesh-at-wiw** [comment]
Okay, now we succeeded in making CE work with remote LDAP in reproducible manner.
Next we're going to start trying to install gluu-server without LDAP.

**Comment by ganesh-at-wiw** [comment]
Succeeded in installing CE without LDAP and getting it working with remote LDAP.
Next we're trying to install gluu-server's only LDAP component and nothing else.

**Comment by ganesh-at-wiw** [comment]
Now, installation with only LDAP also succeeded.
After finally testing the things, we'll change setup.py at github.

**Comment by ganesh-at-wiw** [comment]
These are my changes committed to setup.py:
https://github.com/GluuFederation/community-edition-setup/commit/bcc473a1c4943df4e264cc4ad8b6b7200a3cc109#diff-2eeaed663bd0d25b7e608891384b7298

Brief instructions for testing:
1. Install CE at Server1 without LDAP and with some common domain name say: test.gluu.org.
2. Install CE at Server2 with only LDAP and without any components with same common name: test.gluu.org.
3. Copy /etc/gluu/conf/ox-ldap.properties  from Server2 to Server1 where LDAP is not installed. In that change: **servers: localhost:1636** with  **servers: <Server2_name>:1636**.  If the name of Server2 is not DNS resolved, use the /etc/hosts at both servers: Server1 and Server2.
4. Copy the /etc/gluu/conf/salt file as well from Server2 to Server1 at same location.
5. Edit the file /opt/symas/etc/openldap/symas-openldap.conf at Server2 to allow servers within chroot to connect to LDAP. Use the IP of Server2 here. Change the values of HOST_LIST.

`HOST_LIST="ldaps://127.0.0.1:1636/" to HOST_LIST="ldaps://127.0.0.1:1636/ ldaps://<server2_ip>:1636"`
6. Restart service: solserver at Server2.
7. Open port 1636 at Server2 to accept connections from outside.
8. Inside the LDAP of Server2, change the **localhost:1636** parameter to **<Server2Name>:1636**.
See example below. Create a file: mod.ldif. Below is just an example:
```
dn: inum=@!A98A.6BE2.C296.E833!0002!6599.9134,ou=appliances,o=gluu
changetype: modify
replace: oxIDPAuthentication
oxIDPAuthentication: {"type": "auth", "name": null, "level": 0, "priority": 1, "enabled": true, "version": 0, "config": "{\"configId\": \"auth_ldap_server\",           \"servers\": [\"vsurpr0002.gluu.org:1636\"],           \"maxConnections\": 1000,           \"bindDN\": \"cn=directory manager,o=gluu\",           \"bindPassword\": \"LE9HySqXeEt631cBL3UJzQ==\",           \"useSSL\": \"true\",           \"baseDNs\": [\"o=gluu\"],           \"primaryKey\": \"uid\",           \"localPrimaryKey\": \"uid\",           \"useAnonymousBind\": false,           \"enabled\": true}" }

/opt/opendj/bin/ldapmodify -ZX -D "cn=directory manager,o=gluu" -h Server2.gluu.org -p 1636 -w `/opt/gluu/bin/encode.py -D sKBsEJYn0mNKbYgcCpSRJA==` -f mod.ldif 

```
9. Restart oxauth and identity and apache services at Server1.
10. Access the CE with the url: https://test.gluu.org.
