### ISSUE TITLE
VM reboot does not start Gluu Server automatically in RHEL 7.2

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/community-edition-setup#292]
Gluu Server version 3.0.1 does not present oxTrust GUI after vm reboot. The detailed stack-trace and the steps to reproduce is given @ https://github.com/GluuFederation/gluu-qa/wiki/Itemized-Reports#vm-reboot. 
In short, `httpd` does not start and `oxtrust.log` shows a `ssl certificate download failure`.

**Note:** This issue is not present in CentOS 7.2 1511 build.

**Comment by mzico** [comment]
@zamilskhan @ganesh-at-wiw : From log...  _(99)Cannot assign requested address: AH00072: make_sock: could not bind to address 192.168.122.37:80_

Why it's trying to communicate with port 80? A workaround might be to check what happens if we keep port 80 open along with 443?

**Comment by mzico** [comment]
@zamilskhan @ganesh-at-wiw : Let's double check if that resolve the issue or not... 

enable 'gluu-server-3.0.1' by /sbin/gluu-server-3.0.1 enable
then reboot server
see if container is running automagically or not.

**Comment by ganesh-at-wiw** [comment]
Guys, is this issue still haunting?

`/sbin/gluu-server-3.0.1 enable
`
makes the system run fine after reboot. No?

**Comment by ganesh-at-wiw** [comment]
During working on #295 , I tested this reboot working problem. It works fine without any human interruption.
