### ISSUE TITLE
CentOS/RHEL 7.x resolv.conf is becoming blank after VM reboot

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#295]
OS: CentOS/RHEL 7.x
Gluu Server version: 3.x.x
--------------------------------------------
There was an entry in /etc/resolv.conf. 
Stopped container. 
Rebooted VM. 
Gluu-Server container started. 
But oxAuth is not working. Why? Because /etc/resolv.conf is blank and oxAuth unable to talk to backend AuthN server. 

Temp. workaround: 

- Log into container
- add entry in /etc/resolv.conf
- restart oxauth with 'service oxauth retstart'

**Comment by ganesh-at-wiw** [comment]
Here is my investigation:
This happens only when the gluu-server is enabled.
i.e after
**/sbin/gluu-serverd-3.0.1 enable**
is ran.
In such case, the gluu-server starts before the network portion of OS is ready and hence /etc/resolv.conf is empty.
**Solution:**
To  resolve this, edit the file: /etc/systemd/system/machines.target.wants/systemd-nspawn\@gluu_server_3.0.1.service
and add en entry in [Unit] section as below:

> After=network-online.target

So, finally, the entries should look something like:

```
[Unit]
Description=Container %I
Documentation=man:systemd-nspawn(1)
PartOf=machines.target
Before=machines.target
After=network-online.target

```
Before it looked like:
```
[Unit]
Description=Container %I
Documentation=man:systemd-nspawn(1)
PartOf=machines.target
Before=machines.target
```

**Comment by ganesh-at-wiw** [comment]
@adrian-gluu Please make the suggested change in /etc/systemd/system/machines.target.wants/systemd-nspawn\@gluu_server_3.0.1.service  file as suggested above.

**Comment by ganesh-at-wiw** [comment]
Any further inputs?

**Comment by adrian-gluu** [comment]
this is just in rhel7 not in centos7?

**Comment by adrian-gluu** [comment]
i will fix both just in case rhel7 and centos7

**Comment by adrian-gluu** [comment]
I added "After=network-online.target" in both unit files centos7 and rhel7
