### ISSUE TITLE
Don't allow to run setup.py after installation

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#30]

**Comment by arvindsinghtomar** [comment]
Sorry by mistake.

**Comment by willow9886** [comment]
@yurem not totally clear what this issue is about. Can you comment? Also, it's marked as high priority but still open from April 2015?!

**Comment by rocklyve** [comment]
Found this issue today. 
I think I can describe this, if this is neccesary. 
A few months ago I installed gluu the first time. I executed the setup.py with wrong parameters and after reexecuting the setup.py nothing changed. I figured out, that I have to completely remove the gluu-server from apt and reinstall it. Then I'm able to execute the setup.py with right parameters and everything worked. 
I'm not sure, why executing the setup.py multiple times should be a problem, but it is! 
Maybe you have to delete the old instances in setup.py before setting up a new one, but I don't know the code very well to have more detailed information.

**Comment by yurem** [comment]
@rocklyve you are right.
setup.py should check if there is specific folder/file (example: /etc/gluu/conf/ox-ldap.properties) in VM and don't allow to run it again.

@willow9886 I think we lost this issue. It's very easy to resolve it.

**Comment by rocklyve** [comment]
@yurem do you think that this is the real solution or another way to temporarily solve this? 
I think it would be very nice, if I'm able to execute the setup.py multiple times, but if the setup.py was executed before, there has to be a cleanup or anything else to reset the last setup execution. 
Or I have to be asked, if I would like to reset everything and execute a new setup. 
I don't know another solution than reinstalling gluu-server completely for executing setup.py a second time.

**Comment by yurem** [comment]
During installation setup creates folders in VM, install OpenLDAP package, install Jython, unzip archives, generate keys, loads data, etc..
As result it's much bigger effort to clean up old installation than just reinstall package. Also if we allow to run setup multiple times and implement clean up before second run someone accidentally can clean up production environment.
I think we need to follow generic way:

1. Install
2. Setup
3. Uninstall
4. Go to step 1

In this flow additional check (if it installed already) will protect instance from making unwanted changes.

**Comment by rocklyve** [comment]
okay right, 
so you don't allow to run setup.py again. 
I agree. :)

**Comment by nynymike** [comment]
setup.py should only be run once. The goal is to enable a person to quickly deploy the Gluu Server. It's not a generic configuration tool / package management tool.

**Comment by yurem** [comment]
Fixed
