### ISSUE TITLE
Remove IP address from https config

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#300]
Replace `%{ip}s:443` with `*:443` in apache config.

We should also remove the `/etc/hosts` entry, and see if anything breaks, in which case we could probably just remove the IP address prompt all together.

**Comment by tecoholic** [comment]
IP from Apache configs have been removed. I have left the /etc/hosts file after @ganesh-at-wiw's recommendataion that

* It's required to be in /etc/hosts for adverse situations. As a standard practice, it's used, so every name resolution doesn't go through DNS
* The other reason is: nsswitch refers to files first and then DNS
