### ISSUE TITLE
encode.py no such file or directory

### ISSUE THREAD

**Issue by jinxiao** [GluuFederation/community-edition-setup#302]
i run service gluu-server login to login gluu then run setup.py , it showed 
`sh: 1: /opt/gluu/bin/encode.py: not found
sh: 1: /opt/gluu/bin/encode.py: not found
sh: 1: /opt/gluu/bin/encode.py: not found
sh: 1: /opt/gluu/bin/encode.py: not found
sh: 1: /opt/gluu/bin/encode.py: not found
sh: 1: /opt/gluu/bin/encode.py: not found
sh: 1: /opt/gluu/bin/encode.py: not found
sh: 1: /opt/gluu/bin/encode.py: not found
`

**Comment by nynymike** [comment]
You'll have to register and ask this question on https://support.gluu.org   Unless its shown to be a bug (which it's probably not...) we won't open a ticket on github.
