### ISSUE TITLE
gluu-server-3.0.2/setup.py -- /opt/dist/gluu/oxauth.war (No such file or directory)

### ISSUE THREAD

**Issue by hariubc** [GluuFederation/community-edition-setup#308]
Running into the follow with setup.py on RHEL7 for gluu-server-3.0.2.

--- /opt/dist/gluu/oxauth.war (No such file or directory)

Any ideas on how to circumvent? Is this the same as https://ox.gluu.org/maven/org/xdi/oxauth-server?

"
SNIP...
Congratulations! You successfully installed Jython 2.7.0 to directory /opt/jython-2.7.0.

18:15:53 06/27/17 Running: /bin/ln -sf /opt/jython-2.7.0 /opt/jython
18:15:53 06/27/17 Running: /bin/chown -R root:root /opt/jython-2.7.0
18:15:53 06/27/17 Running: /bin/chown -h root:root /opt/jython
18:15:53 06/27/17 Installing node 6.9.1...
18:15:53 06/27/17 Extracting node-v6.9.1-linux-x64.tar.xz into /opt
18:15:53 06/27/17 Running: tar -xJf /opt/dist/app/node-v6.9.1-linux-x64.tar.xz -C /opt/ --no-xattrs --no-same-owner --no-same-permissions
18:15:56 06/27/17 Running: /bin/ln -sf /opt/node-v6.9.1-linux-x64 /opt/node
18:15:56 06/27/17 Running: /bin/chmod -R 755 /opt/node-v6.9.1-linux-x64/bin/
18:15:56 06/27/17 Running: /bin/mkdir -p /opt/node/temp
18:15:56 06/27/17 Copied ./static/system/initd/node to /opt/gluu/system
18:15:56 06/27/17 Running: /bin/chmod -R 755 /opt/gluu/system/node
18:15:56 06/27/17 Running: /bin/chown -R node:node /opt/node-v6.9.1-linux-x64
18:15:56 06/27/17 Running: /bin/chown -h node:node /opt/node
18:15:56 06/27/17 Running: /bin/mkdir -p /opt/gluu/node
18:15:56 06/27/17 Running: /bin/chown -R node:node /opt/gluu/node
18:15:56 06/27/17 Copying script files
18:15:56 06/27/17 Copied ./static/scripts/logmanager.sh to /opt/gluu/bin
18:15:56 06/27/17 Copied ./static/scripts/testBind.py to /opt/gluu/bin
18:15:56 06/27/17 Rendering encode.py
18:15:56 06/27/17 Running: /bin/chmod -R 700 /opt/gluu/bin
18:15:56 06/27/17 Installing Gluu base...
18:15:56 06/27/17 Preparing files needed to run OpenId keys generator
18:15:56 06/27/17 Unpacking oxauth.war...
18:15:56 06/27/17 Created dir: /opt/dist/gluu/tmp_oxauth
18:15:56 06/27/17 Running: /opt/jre/bin/jar xf /opt/dist/gluu/oxauth.war
18:15:56 06/27/17 java.io.FileNotFoundException: /opt/dist/gluu/oxauth.war (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at sun.tools.jar.Main.run(Main.java:307)
        at sun.tools.jar.Main.main(Main.java:1288)

18:15:56 06/27/17 Copying files to /home/jetty/lib...
18:15:56 06/27/17 Removed dir: /opt/dist/gluu/tmp_oxauth
18:15:56 06/27/17 Generating oxAuth OpenID Connect keys
18:15:56 06/27/17 Creating empty JKS keystore
18:15:56 06/27/17 Running: /bin/sh -c /opt/jre/bin/keytool -genkey -alias dummy -keystore /etc/certs/scim-rs.jks -storepass Cd24yKJmOCCK -keypass Cd24yKJmOCCK -dname "CN=oxAuth CA Certificates"
18:15:56 06/27/17 keytool error: java.io.IOException: Keystore was tampered with, or password was incorrect

18:15:56 06/27/17 Running: /bin/sh -c /opt/jre/bin/keytool -delete -alias dummy -keystore /etc/certs/scim-rs.jks -storepass Cd24yKJmOCCK -keypass Cd24yKJmOCCK -dname "CN=oxAuth CA Certificates"
18:15:56 06/27/17 keytool error: java.io.IOException: Keystore was tampered with, or password was incorrect

18:15:56 06/27/17 Runnning: /bin/sh -c /opt/jre/bin/java -Dlog4j.defaultInitOverride=true -cp  org.xdi.oxauth.util.KeyGenerator -keystore /etc/certs/scim-rs.jks -keypasswd Cd24yKJmOCCK -algorithms RS256
SNIP"

**Comment by nynymike** [comment]
You'll have to register and post this report on https://support.gluu.org. 

We don't provide support on github, and until we decide it's a bug, we won't address it here.
