### ISSUE TITLE
Remove CustomAttributes

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#311]
This custom objectclass was useful when we allowed dynamic schema extension in oxTrust, but now it just confuses the subject. The attributes should be removed, and the respective oxTrust config should also be removed.

```json
{
            "kind": "AUXILIARY", 
            "may": [
                "myCustomAttr1", 
                "myCustomAttr2"
            ], 
            "names": [
                "oxAuthClientCustomAttributes"
            ], 
            "oid": "1.3.6.1.4.1.48710.1.4.102", 
            "sup": [
                "top"
            ], 
            "x_origin": "Gluu - Custom client objectclass"
}
```

**Comment by yurem** [comment]
Do you mean attribute + OC or attributes only ?

**Comment by tecoholic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove CustomAttributes Setup #311](https://trello.com/c/V8IGuuu6/53-remove-customattributes-setup-311)

**Comment by tecoholic** [comment]
The custom attributes have been removed from the custom schema in 171f08961c70a1d687b73b1d79a558640fea06ed 

The issue will be closed once the configuration related to them are also updated.

**Comment by tecoholic** [comment]
The custom attributes have been removed from the oxauth-config.json. Closing this issue.
