### ISSUE TITLE
Check if file exists before applying runlevel changes

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#314]
We need to apply this fix to specific OS only or verify if source files exists before attempting to update links.
Now end of setup log in Ubuntu 14.04 looks like this:
```
10:18:16 07/11/17 Changing RC Level 3 Links
10:18:16 07/11/17 Running: mv /etc/rc3.d/S03solserver /etc/rc3.d/S80solserver
10:18:16 07/11/17 mv: cannot stat '/etc/rc3.d/S03solserver': No such file or directory

10:18:16 07/11/17 Running: mv /etc/rc3.d/S01oxauth /etc/rc3.d/S81oxauth
10:18:16 07/11/17 mv: cannot stat '/etc/rc3.d/S01oxauth': No such file or directory

10:18:16 07/11/17 Running: mv /etc/rc3.d/S01identity /etc/rc3.d/S82identity
10:18:16 07/11/17 mv: cannot stat '/etc/rc3.d/S01identity': No such file or directory

10:18:16 07/11/17 Running: mv /etc/rc3.d/S02apache2 /etc/rc3.d/S83apache2
10:18:16 07/11/17 mv: cannot stat '/etc/rc3.d/S02apache2': No such file or directory

10:18:16 07/11/17 Saving properties to ./setup.properties.last
```

**Comment by ganesh-at-wiw** [comment]
@yurem can you please name the deb which has its setup.py, this code? So, that I can directly rectify the setup.py and update the master branch.

**Comment by ganesh-at-wiw** [comment]
I could not reproduce with package: gluu-server-3.0.2_9-1~trusty+Ub14.04_amd64.deb.
Please suggest package to use.

**Comment by ganesh-at-wiw** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/0cf0236d55674875bb5040ba89bcc8f06738e239#diff-2eeaed663bd0d25b7e608891384b7298
