### ISSUE TITLE
Some minor security issues in current packages.

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/community-edition-setup#315]
A user shared results of security scans of their 3.0.1 CentOS 6.7 instance (I believe it still should hold for 3.0.2 as well). Below is list of some issues it revealed:

1. It seems Gluu CE pages may be susceptible to click-jacking attack due to lack of "X-Frame-Options" header in HTTP responses. We commented out line providing this header in Gluu's Apache config before as it was creating issues with RP's pages implementing OIDC session management protocol (`opiframe` page couldn't be added in iframe to RP's page as required by specs due to this header). So far it's been the only known issue created by this header, so perhaps it's time to add it back, just creating exception for path `/oxauth/opiframe` ?

2. It was pointed out that contents of `/error/` directory in our default package can be listed and viewed. It seems to be directory containing default Apache's error pages which is located at `/var/www/error/` in the instance in question. It doesn't seem like anything sensitive is leaked this way, but still better to disable directory browsing in Apache. Below is proposed solution from the document:
```
In your httpd.conf file, disable the "Indexes" option for the appropriate <Directory> tag by removing it from the Options line.
In addition, you should always make sure that proper permissions are set on all files and directories within the web root
```
Strange part is that it doesn't seem to exist both in 3.0.1 and 3.0.2 Ubuntu packages I have installed. Is it only created in CentOS6? We probably should check it too.

3. There is bunch of warnings due to the fact Apache allows usage of TLS1.0 and TLS1.1 by default, as well as cipher suites containing RC4 algorithm. Not sure how should we proceed here, as disabling a lot of cipher suites and protocols may harm some legacy clients still existing out there (in some cases there may not be easy way to update them, like in case of outdated mobile devices). I believe it was discussed before and was decided that default package should be permissible enough to support wide variety of clients, and each organization should enforce their own policies in this field, and handle all consequences of it for themselve.

**Comment by aliaksander-samuseu** [comment]
It seems we block suites using RC4 algorithm in Apache:
Strange.. Just've checked Apache's config at this instance:
```
SSLCipherSuite ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:DHE-RSA-AES128-SHA256:DHE-DSS-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES128-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK
```

I also did some scan with online tools, as well as with `openssl s_client`, and wasn't able to confirm RC4 can be negotiated. Let's ignore it for now, I'm asking for details from the user.

**Comment by tecoholic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Some minor security issues in current packages. Setup #315](https://trello.com/c/ptLgvYqS/49-some-minor-security-issues-in-current-packages-setup-315)
