### ISSUE TITLE
Unable to update RHEL 7.x based 3.0.1 to 3.0.2

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#319]
3.0.2 update package is not installing in 3.0.1: 

```
[root@checkit ~]# rpm -ivh gluu-updater-3.0.2-1-1.rhel6.x86_64.rpm
Preparing...                          ################################# [100%]
        file /opt/gluu-server-3.0.1/opt from install of gluu-updater-3.0.2-1-1.rhel6.x86_64 conflicts with file from package gluu-server-3.0.1-2-1.rhel7.x86_64
[root@checkig ~]#

```

**Comment by adrian-gluu** [comment]
can you try uninstall it the old one first?

**Comment by mzico** [comment]
@adrian-gluu : Sorry.. .. which old one again?

**Comment by adrian-gluu** [comment]
there is a confusion you are using a rhel6 and it looks like you already have rhel7 pkg installed, which rhel and pkg are you trying to install there?

**Comment by mzico** [comment]
@adrian-gluu : Hmm.. that makes sense. Re-checking again.

**Comment by mzico** [comment]
@adrian-gluu : Yes.. seems like there is no RHEL 7 package available here. So you are right.. .I was trying with RHEL 6 package. Closing this issue but can you please created a 7 package when you can manage some time; we have customers waiting on that. 

Thanks much!

**Comment by adrian-gluu** [comment]
@mzico there is a rhel7 pkg, please check the rhel7 repo:
https://repo.gluu.org/rhel/7/?C=M;O=D

**Comment by mzico** [comment]
@adrian-gluu : Thanks much! I'll ask customer to test.
