### ISSUE TITLE
Import custom ldif templates during CE isntall

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#325]
Now in order to import ldif we need to install CE, And run setup after that again with parameter to specify external ldif. If you makes mistake in parameter name setup can do install again which led to errors.

We need to setup CE and render/import ldif during install

**Comment by ganesh-at-wiw** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/058b4b8d7f0cba3c9ecf8f9a4d9524b0c5254171#diff-2eeaed663bd0d25b7e608891384b7298

If the setup is not run already, then the generation of ldif and import happens during the install.

For the case of wrong parameter name, the system excepts and prints help message and exits.
