### ISSUE TITLE
Ubuntu 16.04 package fixes

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#328]
1. After log in user get message:
`
root@ubuntu:~# service gluu-server-3.1.0 login
gluu-server-3.1.0 is running...
logging in...
mesg: ttyname failed: Success
`

2. setup location is wrong. Now it's here:
/install/community-edition-setup-version_3.1.0

**Comment by yurem** [comment]
There is also another problem:
3. We need to remove /etc/apache2/sites-enabled/000-default.conf

**Comment by yurem** [comment]
We need to fix 2-3 in 3.1.0
Point one we can fix in 3.1.1.

**Comment by adrian-gluu** [comment]
file removed  /etc/apache2/sites-enabled/000-default.conf

**Comment by adrian-gluu** [comment]
https://repo.gluu.org/ubuntu/pool/main/trusty/gluu-server-3.1.0_2~trusty+Ub14.04_amd64.deb

**Comment by yurem** [comment]
ok, we resolved 2-3 points. In next version we need to resolve point 1`:
```
root@ubuntu:~# service gluu-server-3.1.0 login
gluu-server-3.1.0 is running... logging in...
 mesg: ttyname failed: Success
```
