### ISSUE TITLE
Installation error for Debian package 3.1.0

### ISSUE THREAD

**Issue by ganesh-at-wiw** [GluuFederation/community-edition-setup#329]
root@vsdrpr0001:~# dpkg -i gluu-server-3.1.0_1-3~Db8jessie_amd64.deb 
Selecting previously unselected package gluu-server-3.1.0.
(Reading database ... 158103 files and directories currently installed.)
Preparing to unpack gluu-server-3.1.0_1-3~Db8jessie_amd64.deb ...
Unpacking gluu-server-3.1.0 (1-3~Db8jessie) ...
Setting up gluu-server-3.1.0 (1-3~Db8jessie) ...
dpkg: error processing package gluu-server-3.1.0 (--install):
 subprocess installed post-installation script returned error exit status 126
Processing triggers for systemd (215-17+deb8u2) ...
Errors were encountered while processing:
 gluu-server-3.1.0

**Comment by adrian-gluu** [comment]
post install script is just this:
#!/bin/bash

set -e

/usr/sbin/chroot /opt/gluu-server-3.1.0 /bin/su - root -c '/tmp/system_user.list' > /dev/null 2>&1
/usr/sbin/chroot /opt/gluu-server-3.1.0 /bin/su - root -c '/tmp/system_group.list' > /dev/null 2>&1

/bin/cp -a /etc/resolv.conf /opt/gluu-server-3.1.0/etc/ > /dev/null 2>&1

exit 0

not related with systemd can you gave me more info with journalctl?

**Comment by ganesh-at-wiw** [comment]
The package works fine now.
