### ISSUE TITLE
RHEL/CentOS 7 support

### ISSUE THREAD

**Issue by davidstrauss** [GluuFederation/community-edition-setup#33]
Title says it all. The current installation instructions specify CentOS/RHEL 6, which is pretty old now.

**Comment by nynymike** [comment]
We have a new build. Adrian, can you update the Centos Instructions?

**Comment by jeroenpeeters** [comment]
I'm in the process of evaluating Gluu. Unfortunately I cannot get the package to work on CentOS 7.1.1503. I would actually be happier if I could easily run this from Docker. Are you planning to do that? Or is there a manual available for installing all components separately. I would be more than happy to help to 'dockerize' Gluu.

Starting:

#> service gluu-server start
Starting gluu-server (via systemctl):                      [  OK  ]


However, when I try to login:

#> service gluu-server login
gluu-server is not running

**Comment by adrian-gluu** [comment]
Hello Jeroen, 

Right now we are in the middle of 2 new projects:
- RPM for centos 7
- and a Docker VM

So probably keep in touch with us, because soon you gonna have news about these new stuff.

Regards, Adrian.-

**Comment by gkout** [comment]
I have the same problem like Jeroen. It seems the new package for Centos 7 takes some time.
We are in July already :)

Cheers,
George

**Comment by adrian-gluu** [comment]
Hello George, we are working on that, unfortunately there isnt any estimated time yet on this.

Adrian.-

**Comment by cestith** [comment]
I just downloaded the server in September and have the same issue. Is there a time estimated yet?

**Comment by willow9886** [comment]
We're still working on this, Chris. We hope to publish packages for CentOS 7 in our next major release, 2.4.0, towards the end of the month. We'll update this issue when they are ready.

**Comment by adrian-gluu** [comment]
we have a 2.3.4 release ready for centos7/rhel7

**Comment by moebin** [comment]
So is it currently supporting Centos 7? I tried this morning and it seems like it doesn't work yet

**Comment by jimscarver** [comment]
It does not work for us either, see GluuFederation/community-edition-setup#70

**Comment by jimscarver** [comment]
According to https://support.gluu.org/view/installation/problem-installing-and-running-gluu-server-on-centos-7/2167 centos 7 is not working yet,

**Comment by willow9886** [comment]
We're still working on support for CentOS 7. For now, please use CentOS 6.5. Instructions [here](https://github.com/GluuFederation/community-edition-setup/issues/33#issuecomment-157303332)

**Comment by ramx** [comment]
I tried the CentOS 6.5 documentation for CentOS7 but it doesn't start my server : http://stackoverflow.com/questions/35203107/gluu-server-2-4-1-not-starting-on-centos-7

**Comment by willow9886** [comment]
Best to get support for this type of issue on http://support.gluu.org. We have new releases for CentOS and RHEL 7 which you can try.
