### ISSUE TITLE
Container restart failing in Ubuntu 14.04 && CentOS 6.8

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/community-edition-setup#343]
root@ubuntu2:/opt# service gluu-server-3.1.1 restart
Shutting down Gluu Server...
Stopping Apache...
OK
Stopping oxTrust...
OK
Stopping oxAuth...
OK
Stopping RSyslog...
OK
Stopping OpenLDAP...
OK

ERROR: Can't start gluu server.
HINT: Please manually remove /var/run/gluu-server-3.1.1.pid and unmount chroot container by running
rm -f /var/run/gluu-server-3.1.1.pid
df -aP | grep gluu-server-3.1.1 | awk '{print $6}' | xargs -I {} umount -l {}

**Comment by zamilskhan** [comment]
[root@centos ~]# service gluu-server-3.1.1 restart
Shutting down Gluu Server...
Stopping Apache...
OK
Stopping Passport...
OK
Stopping oxAuth RP...
OK
Stopping Asimba...
OK
Stopping IDP...
OK
Stopping oxTrust...
OK
Stopping oxAuth...
OK
Stopping OpenLDAP...
OK

ERROR: Can't start gluu server.
HINT: Please manually remove /var/run/gluu-server-3.1.1.pid and unmount chroot container by running
rm -f /var/run/gluu-server-3.1.1.pid
df -aP | grep gluu-server-3.1.1 | awk '{print $6}' | xargs -I {} umount -l {}

**Comment by ganesh-at-wiw** [comment]
Fix for restart has been added to new branch: 3.1.1 at community-edition-package init gluu-server.
Here is what was done. 
https://github.com/GluuFederation/community-edition-package/commit/df041e063cb3dc48ef28a290183bfcbfa62f570e#diff-5dfd552a9169b091ada6d476a7295596

At the time of update, ubuntu was working fine.
Now, checking for CentOS 6.x.

**Comment by ganesh-at-wiw** [comment]
Confirmed that the fix works for CentOS 6.x as well.

```
[root@vscrpr0001 ~]# service gluu-server-3.1.1 restart
Shutting down Gluu Server...
Stopping Apache...
OK
Stopping oxAuth RP...
OK
Stopping Asimba...
OK
Stopping oxTrust...
OK
Stopping oxAuth...
OK
Stopping OpenLDAP...
OK

Starting Gluu server, please wait...
[root@vscrpr0001 ~]# 

```
Closing the issue.
For testing, the gluu-server file https://github.com/GluuFederation/community-edition-package/blob/master/package/initd/gluu-server can be downloaded and copied as:
/etc/init.d/gluu-server-3.1.1
