### ISSUE TITLE
Stopping Gluu Server does not stop memcached in 3.1

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/community-edition-setup#345]
After stopping Gluu server, the memcached service will stay active.

**Comment by adrian-gluu** [comment]
probably we should trick the init file

**Comment by adrian-gluu** [comment]
we are going to add an stop for memcache in gluu-server init file hope that fix the issue

**Comment by adrian-gluu** [comment]
this happens in all the distros? @afroDC

**Comment by afroDC** [comment]
Yes, all distros Adrian. There's nothing that stops memcached in any of the
scripts.

Thanks

**Comment by adrian-gluu** [comment]
ok just submitted a fix:
https://github.com/GluuFederation/community-edition-package/commit/8029d9106b3c0c06d428dfa5404677de7b6493ce

**Comment by yurem** [comment]
According to update we are trying to stop memcached inside root but we need to do that inside chroot

**Comment by yurem** [comment]
Fix for this issue: https://github.com/GluuFederation/community-edition-package/commit/bb7269f8c56adda53fe815a9036f9af457b9d11c

It contains fir for `stopGenericService` method
