### ISSUE TITLE
passport component is missing

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/community-edition-setup#346]
Installed Gluu 3.1.1 with passport=Yes, But its not available under /opt/gluu/jetty

GLUU.root@ubuntu2:/opt/dist/gluu# cd /opt/gluu/jetty/
GLUU.root@ubuntu2:/opt/gluu/jetty# ll
total 20
drwxr-xr-x 5 jetty jetty 4096 Sep 21 23:14 ./
drwxr-xr-x 9 root  root  4096 Sep 21 23:14 ../
drwxr-xr-x 6 jetty jetty 4096 Sep 24 04:56 identity/
drwxr-xr-x 6 jetty jetty 4096 Sep 24 05:52 oxauth/
drwxr-xr-x 4 jetty jetty 4096 Sep 24 04:56 oxauth-rp/

When checked War file under ubuntu2:/opt/dist/gluu, its size is 0

GLUU.root@ubuntu2:/opt/dist/gluu# ll
total 245852
drwxr-xr-x 2 root root     4096 Sep 21 23:12 ./
drwxr-xr-x 5 root root     4096 Sep 21 23:07 ../
-rw-r--r-- 1 root root 93825628 Sep 19 11:49 identity.war
-rw-r--r-- 1 root root 51293882 Sep 19 11:52 idp.war
-rw-r--r-- 1 root root     5713 Sep 19 11:52 idp3_cml_keygenerator.jar
-rw-r--r-- 1 root root 34313629 Sep 19 12:36 oxauth-rp.war
-rw-r--r-- 1 root root 69347147 Sep 19 12:40 oxauth.war
-rw-r--r-- 1 root root        0 Sep 19 13:33 passport.tgz
-rw-r--r-- 1 root root  2947776 Sep 19 11:52 shibboleth-idp.jar

**Comment by yurem** [comment]
In CE 3.1.1 beta2 it exists.
