### ISSUE TITLE
Wrong directory in gluu-server uninstall notification

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/community-edition-setup#350]
Ubuntu 14.04 package (any version)

Message: 
$ sudo apt remove gluu-server-3.1.1 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  gluu-server-3.1.1
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 1.053 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 322423 files and directories currently installed.)
Removing gluu-server-3.1.1 (2.beta2~trusty+Ub14.04) ...
Checking to make sure Gluu Server is down...
gluu-server-3.1.1 is not running
Your changes will be saved into /opt/gluu-server-3.1.1.**saved**

real directory name:
/opt/gluu-server-3.1.1.**save**

**Comment by adrian-gluu** [comment]
.saved is how linux distros use, I'll check if we can rename it

**Comment by willow9886** [comment]
@adrian-gluu whats the verdict?

**Comment by adrian-gluu** [comment]
thats handle it by dpkg we cannot change the saved dir, let me see if i can move it in the postrm but is dangerous

**Comment by sahiliamsso** [comment]
Not fixed yet.

**Comment by adrian-gluu** [comment]
we already fixed the typo on 3.1.2 RC2 for ubuntu trusty
