### ISSUE TITLE
Add oxMultivaluedAttribute to oxEnrollmentCode attribute

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/community-edition-setup#351]
If [oxEnrollmentCode](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/attributes.ldif#L1074) is aimed at being part of custom attributes for SCIM (not sure if really needed), I think we should add `oxMultivaluedAttribute: false/true` to it, to keep it consistent with the other cust attributes (scimCustomFirst, second, ...) we already support by default.

**Comment by mbaser** [comment]
Done
