### ISSUE TITLE
Gluu server should start even if stopped when service gluu-server-xxxx restart

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/community-edition-setup#354]
# service gluu-server-3.1.1 stop
Shutting down Gluu Server...
Stopping Apache...
OK
Stopping oxTrust...
OK
Stopping oxAuth...
OK
Stopping RSyslog...
OK
Stopping OpenLDAP...
OK

root@c3:~# service gluu-server-3.1.1 restart
gluu-server-3.1.1 is not running

The Gluu server should still start even if is not running.

**Comment by ganesh-at-wiw** [comment]
Agreed.
https://github.com/GluuFederation/community-edition-package/commit/668985fa19160280140ee7cb41e01c518b203491#diff-5dfd552a9169b091ada6d476a7295596

Solution will be included in 3.1.2.
