### ISSUE TITLE
Getting 404 for '.well-known/simple-web-discovery' endpoint

### ISSUE THREAD

**Issue by shouro** [GluuFederation/community-edition-setup#358]
gluu server 3.1.1

When I hit this url : https://some.gluu.server/.well-known/simple-web-discovery
I get 404

Https conf location in CE,
https://github.com/GluuFederation/community-edition-setup/blob/version_3.1.1/templates/https_gluu.conf#L162

Same routing is implemented in DE 3.1.1 nginx,
https://github.com/GluuFederation/docker-nginx/blob/master/templates/gluu_https.conf.tmpl#L94

**Comment by willow9886** [comment]
cc @yurem

**Comment by willow9886** [comment]
I'm closing this out. It should be fixed in the latest version.
