### ISSUE TITLE
Gluu-server should support upgrade process with data restore

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#36]
Currently gluu-server package covers upgrade process partially. It stop previous services in order to allow new package install. But there are user data which should be restored after upgrade.
What about next simple solution:
1) Run full LDAP backup from pre-uninstall script and store result ldif into /opt/gluu-server.backup
Make sure that ldap export command returns success before allowing to resume package uninstall process.
2) Install new package.
3) Add to setup option to ask user if it should import backup if it exists.
4) Import entries from backup which not exists in new LDAP (don't override entries created with setup script)

**Comment by nynymike** [comment]
opendj has a command db2ldif that is probably the safest way to backup the ldap server.
