### ISSUE TITLE
In setup script: allow selection of LDAP or Couchbase as the database

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#360]
We need to do:
1. Investigate if it's possible to perform a silent installation of Couchbase. Should be similar to how LDAP is installed. Setup should have new method for Couchbase installation.

2. Setup should have method to do initial Couchbase configuration. It should create bucket, configure memory usage, create primary indexes, etc..

3. Setup should have a method to import LDIF into DB. @mbaser has a similar method already. We need to check if it loads all entries without errors. Also it should log count successfully and failed to load entries.

**Comment by mbaser** [comment]
Couchebase installation functions were added to setup.py with commit ce77307 but not tested. Couchebase uses port 8091 and this port also used by gluu, couchbase configuration should be changed to use another port

**Comment by mbaser** [comment]
Commit 6c95171 enables installation and configuration of couchbase. Currently installation is only possible for CentOS due to init-script.
Couchbase option is available with `--allow_pre_released_applications`
It looks couchbase installation package in directory `/opt/dist/couchbase`

**Comment by mbaser** [comment]
Still needs improvement, but basic functions were implemented. No need to keep open this issue.
