### ISSUE TITLE
Upgrade: ldap data import too slow

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#361]
I don't have much info / specific info on which DN/data are taking this much time but I'll do some tailing for import.log if possible. 

Just to give an example: around 8800 entries ( ldap data + user's information ) import took 2 hours to complete.

**Comment by arvindsinghtomar** [comment]
As you can see there is too much process going on during export and import processes, scripts reads each of the data and modifies according to new servers configuration this process is definitely going to take some time .

I am not sure I will be able to make it fast or not .

But I will try whatever will be possible to reduce time.

**Comment by yurem** [comment]
Can you try to use OpenLDAP .../sldapadd -b o=gluu -f file_name.ldif command to add entries?

**Comment by arvindsinghtomar** [comment]
'-b' is already included in commands 

`/opt/opendj/bin/ldapsearch -h localhost -p 1636 -Z -X -D "cn=directory manager" -j /tmp/tmpTl7cG9 -s one -b o=gluu o=* dn`

**Comment by mbaser** [comment]
Previously, upgrade scripts parses ldif files every time for each entry, this takes too long time for big data. Currently, ldif files parsed once and written to shelve database, this increases speed of upgrade script, importing 1e6 entries should not take more than 30 mins on a moderate server.
