### ISSUE TITLE
Upgrade:  `openIdClientPassword` changing in 'oxidp' configuration

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#367]
After upgrading from 3.0.1 to 3.1.1, base64 password of 'openIdClientPassword' is changing inside 'ou=oxidp,ou=configuration,inum.....,o=gluu' [ Screenshot attached ] .  This password should be same as 'oxTrust Admin GUI' client password; failing to do that resulting 503 error from Shibboleth IDP. 

![screenshot_7](https://user-images.githubusercontent.com/7156097/32895350-5ebbf6ea-caa5-11e7-91fe-a539bea536a1.png)

**Comment by arvindsinghtomar** [comment]
implemted
