### ISSUE TITLE
Log file of gluu-server

### ISSUE THREAD

**Issue by prabhu-rajendran-payoda** [GluuFederation/community-edition-setup#37]
I m trying to install and configure gluu-server in CentOS 6 based on http://www.gluu.org/docs/admin-guide/deployment/centos/

I installed gluu-server till before step setup.py, but cannot able to start gluu-server.

Searched for log file, it was NO WHERE.

**Comment by mzico** [comment]
What message do you get when you try command `service gluu-server start`

**Comment by prabhu-rajendran-payoda** [comment]
[root@ce /]# service gluu-server start
Starting gluu-server (via systemctl):                      [  OK  ]
[root@ce /]# service gluu-server status
gluu-server is not running
[root@ce /]#

**Comment by prabhu-rajendran-payoda** [comment]
[root@ce /]# service gluu-server start
Starting gluu-server (via systemctl):                      [  OK  ]
[root@ce /]# service gluu-server status
gluu-server is not running
[root@ce /]#

**Comment by prabhu-rajendran-payoda** [comment]
I could able to install and start after two retry..

But, stuck with error on setup.py, 

$ service gluu-server login
Gluu server is not started, please start it from root machine by service gluu-server start

**Comment by prabhu-rajendran-payoda** [comment]
When will be the release for CentOS 7 in place?

**Comment by adrian-gluu** [comment]
there isn't any estimated launch date yet, our team is working on that.

**Comment by prabhu-rajendran-payoda** [comment]
ok thanks

**Comment by prabhu-rajendran-payoda** [comment]
Finally, i installed with CentOS 6.5.. 

But, cant able to get it in browser.  -  https://{hostname}  --- not works
