### ISSUE TITLE
IdP starts prior to OpenLDAP in Xenial

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/community-edition-setup#371]
Environment:
Ubuntu 16.04.3 LTS, gluu-server-3.1.1-1-8~xenial+Ub16.04

Steps to reproduce:
1. Make sure the Gluu service is stopped
2. Start the Gluu service and wait for 5-10 minutes for all components to initialize. Make sure they did by accessing the login page. Try to access `/idp/shibboleth` (IDP's metadata endpoint) after that.

Results:
"Service unavailable" is returned. The issue is resolved by restarting just the `idp` service, but happens again if the whole Gluu service is restarted. `idp-process.log` contains hints it may be related to inability to access LDAP server at the moment of startup.

Further investigation shows it is indeed the cause. In the container's init script we specifically set runlevel to 3:

```
`/usr/sbin/chroot /opt/gluu-server-$GLUU_VERSION su - root -c '/etc/init.d/rc 3' > /dev/null 2>&1 && echo "started"`
```

Default startup priorities set for this runlevel in container are like below:

```
# ll /etc/rc3.d/
total 12
drwxr-xr-x  2 root root 4096 Nov 20 23:13 ./
drwxr-xr-x 63 root root 4096 Nov 17 20:25 ../
lrwxrwxrwx  1 root root   29 Nov 28  2016 K01apache-htcacheclean -> ../init.d/apache-htcacheclean*
-rw-r--r--  1 root root  677 Feb  5  2016 README
lrwxrwxrwx  1 root root   13 Nov 20 23:11 S01idp -> ../init.d/idp*
lrwxrwxrwx  1 root root   17 Nov 28  2016 S01rsyslog -> ../init.d/rsyslog*
lrwxrwxrwx  1 root root   14 Nov 28  2016 S03dbus -> ../init.d/dbus*
lrwxrwxrwx  1 root root   19 Nov 28  2016 S03memcached -> ../init.d/memcached*
lrwxrwxrwx  1 root root   18 Nov 17 18:50 S03passport -> ../init.d/passport*
lrwxrwxrwx  1 root root   15 Feb  3  2017 S03rsync -> ../init.d/rsync*
lrwxrwxrwx  1 root root   14 Nov 17 18:50 S04cron -> ../init.d/cron*
lrwxrwxrwx  1 root root   18 Nov 17 18:50 S05ondemand -> ../init.d/ondemand*
lrwxrwxrwx  1 root root   18 Nov 17 18:50 S05rc.local -> ../init.d/rc.local*
lrwxrwxrwx  1 root root   19 Nov 20 23:11 S80solserver -> ../init.d/solserver*
lrwxrwxrwx  1 root root   16 Nov 20 23:11 S81oxauth -> ../init.d/oxauth*
lrwxrwxrwx  1 root root   18 Nov 20 23:11 S82identity -> ../init.d/identity*
lrwxrwxrwx  1 root root   17 Nov 20 23:11 S83apache2 -> ../init.d/apache2*
```
As can be seen, all main component's services are seem to be specifically arranged in such order they'll start after `solserver`, except for idp which is left at the beginning of the list.

The corresponding section setting this startup sequence in `setup.py` seems to be [this](https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L2664):
```
    ##### Below function is temporary and will serve only 
    ##### Untill we're done with systemd units for all services for Ubuntu 16 and CentOS 7
    def change_rc_links(self):
        if self.os_type in ['ubuntu', 'debian']:
            if os.path.isfile('/etc/rc3.d/S03solserver'):
                self.logIt("Changing RC Level 3 Links")
                self.run(['mv', '/etc/rc3.d/S03solserver', '/etc/rc3.d/S80solserver'])
            if os.path.isfile('/etc/rc3.d/S01oxauth'):
                self.run(['mv', '/etc/rc3.d/S01oxauth', '/etc/rc3.d/S81oxauth'])
            if os.path.isfile('/etc/rc3.d/S01identity'):
                self.run(['mv', '/etc/rc3.d/S01identity', '/etc/rc3.d/S82identity'])
            if os.path.isfile('/etc/rc3.d/S02apache2'):
                self.run(['mv', '/etc/rc3.d/S02apache2', '/etc/rc3.d/S83apache2'])
############################   Main Loop   #################################################
```
As it says in comment section, it's sort of workaround for Systemd distros. **In such case it needs to also set startup priorities for IDP and Asimba.**

**Comment by ganesh-at-wiw** [comment]
The proposed resolution is here at:
https://github.com/GluuFederation/community-edition-setup/commit/9a65c9a795742e38312325caa197f51e8163204c#diff-2eeaed663bd0d25b7e608891384b7298

We can test in upcoming builds.
