### ISSUE TITLE
Syntax error seen

### ISSUE THREAD

**Issue by cpalmer9** [GluuFederation/community-edition-setup#387]
https://github.com/GluuFederation/community-edition-setup/blob/898846ca38fb47abbd25ff8a0ae00155eb4f25dc/static/scripts/export3031.py#L594

Probably a typo, but removing the leading ‘sudo’ allows the script to run.

**Comment by yurem** [comment]
@arvindsinghtomar please take a look on this. I think we can remove "sudo" from this line

**Comment by arvindsinghtomar** [comment]
https://github.com/GluuFederation/community-edition-setup/pull/388
