### ISSUE TITLE
Make user accept MIT License in setup.py

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#390]
We should print the MIT license and ask the user:

"Do you acknowledge that use of the Gluu Server is under the MIT license? [y|N]: " 

Defaults to not accepting the license.

**Comment by ganesh-at-wiw** [comment]
I've posted the fix to the fix:
https://github.com/GluuFederation/community-edition-setup/commit/0468f651d6a21be74f5bfa33e78e1f88ec7eb0a0#diff-2eeaed663bd0d25b7e608891384b7298

**Comment by ganesh-at-wiw** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/42585f1b9baf8adf8143e298632cac074689c200#diff-2eeaed663bd0d25b7e608891384b7298
