### ISSUE TITLE
Exception encountered during context initialization after reboot

### ISSUE THREAD

**Issue by alidsmith79** [GluuFederation/community-edition-setup#391]
Was in the process of setting up SAML with Gluu 3.1.1.Final after a reboot shibboleth is refusing to start, relevant excerpt from logs:
`2017-12-18 23:42:38,224 - WARN [net.shibboleth.ext.spring.context.DelimiterAwareApplicationContext:549] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.metrics.RegisterMetricSets$child#0' defined in URL [file:/opt/shibboleth-idp/conf/admin/metrics.xml]: Cannot resolve reference to bean 'shibboleth.metrics.AttributeResolverGaugeSet' while setting bean property 'arguments' with key [7]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.metrics.AttributeResolverGaugeSet' defined in URL [file:/opt/shibboleth-idp/system/conf/general-admin-syste
[shibboleth_logs.txt](https://github.com/GluuFederation/community-edition-setup/files/1569826/shibboleth_logs.txt)
m.xml]: Invocation of init method failed; nested exception is net.shibboleth.utilities.java.support.component.ComponentInitializationException: Injected service was null or not an AttributeResolver `

I have also included further log details in a file and the metrics.xml file (zipped)
[metrics.zip](https://github.com/GluuFederation/community-edition-setup/files/1569833/metrics.zip)
[shibboleth_logs.txt](https://github.com/GluuFederation/community-edition-setup/files/1569834/shibboleth_logs.txt)

Any help very much appreciated.

Regards

Alasdair Smith

**Comment by willow9886** [comment]
Hi Alasdair, 

Best to search the Gluu support portal: https://support.gluu.org 

If you can't find any existing similar pubic issues, feel free to register and open a ticket there. 

You can point to this ticket for relevant logs, etc. 

Thanks, 
Will
