### ISSUE TITLE
Strange attribute values in admin entry

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/community-edition-setup#394]
Recently I installed RC3. My admin user has some attributes I haven't seen set in other Gluu versions

For instance it has `picture`, `profile`, `telephoneNumber`, `website`, `zoneinfo`, `c`, `phoneNumberVerified`, `gender`, `emailVerified`

I am attaching a ldif file... I wonder why I have "America/Los_Angeles" in zone, or country=US if upon installation I did provide a different value for my location. Also the phone number... and birthday... it's weird.

Can someone replicate?

[admin.ldif.txt](https://github.com/GluuFederation/community-edition-setup/files/1583549/admin.ldif.txt)

**Comment by yurem** [comment]
We changed [this](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/people.ldif) template 4 month ago.

**Comment by yurem** [comment]
Or testes depends on this user values. We can create another admin user and move this user ldif to test data. Any ideas about new admin user uid?

**Comment by yurem** [comment]
@yuriyz @qbert2k I offer to change in our tests test user 'admin' to 'test' (or any other name). After that we can remove not required fields from admin user entry in CE

**Comment by mbaser** [comment]
@yurem Shall I copy current **admin** user as **testadmin** to test data and remove those attributes mentione by Jose?

**Comment by yurem** [comment]
@mbaser yes, we can do this in `master` branch

**Comment by mbaser** [comment]
Done
