### ISSUE TITLE
2.4.4.2 to 3.1.2 upgrade is missing Asimba component

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/community-edition-setup#398]
Install 2.4.4.2 with asimba installed
hostname                                            xxxxxxxxx
orgName                                            gluu
os                                                       ubuntu
city                                                       austin
state                                                          tx
countryCode                                                    us
support email                                                 sas
tomcat max ram                                               3072
Admin Pass                                                 xxxxxx
Install oxAuth                                               True
Install oxTrust                                              True
Install LDAP                                                 True
Install Apache 2 web server                                  True
Install Shibboleth SAML IDP                                  True
Install Asimba SAML Proxy                                    True
Install CAS                                                  True
Install oxAuth RP                                            True

Now export the content, and Install 3.1.2 . Use the setup.properties from backup_2431. You will see
installAsimba
-------------
False

Asimba is not installed.

**Comment by yurem** [comment]
Fixed: https://github.com/GluuFederation/community-edition-setup/commit/f29f08dbf4abc7f3171edc5940f7726f062e55b6
