### ISSUE TITLE
in setup script, force user to accept license first

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#399]
In the current setup script, you accept the license at the very end of the interactive questions. 

![image](https://user-images.githubusercontent.com/3717101/34782836-76dbe134-f5ef-11e7-9859-7cbb75829c82.png)

It would be better to move license acceptance to the first question... if they don't accept the license, exit!

**Comment by ganesh-at-wiw** [comment]
Is duplicate with #390

**Comment by ganesh-at-wiw** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/42585f1b9baf8adf8143e298632cac074689c200#diff-2eeaed663bd0d25b7e608891384b7298
