### ISSUE TITLE
setup.py should ask to accept MIT license first

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#402]
We should ask to accept the license first (not last):
![image](https://user-images.githubusercontent.com/3717101/35161942-59a832b0-fd07-11e7-8621-68355358e988.png)

If the user hits return to accept the default, `setup.py` will exit, and the information will have to be re-entered.

**Comment by yurem** [comment]
> **We should ask to accept the license first (not last):**
