### ISSUE TITLE
Remove default Gluu SP SAML Trust Relationship

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#404]
As oxTrust uses OpenID Connect, I don't think this is needed anymore.

![image](https://user-images.githubusercontent.com/3717101/35450268-17bbebde-0285-11e8-8ac4-db05ed11434d.png)

**Comment by yurem** [comment]
I suspect we use it in oxTrust tests. We need check this and move this TR to https://github.com/GluuFederation/community-edition-setup/tree/master/templates/test/oxtrust/data/oxtrust-test-data.ldif

This file is ldif. Here is sample of such file for oxAuth: https://github.com/GluuFederation/community-edition-setup/blob/master/templates/test/oxauth/data/oxauth-test-data.ldif

**Comment by yurem** [comment]
Removed
