### ISSUE TITLE
Update init_fixes to configure OpenDJ service too

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#405]
There is no information to update OpenDJ service in this array:
https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L513

**Comment by ganesh-at-wiw** [comment]
Added option for opendj in master and 3.1.3 branches.
The differences are:
https://github.com/GluuFederation/community-edition-setup/commit/534ff8547e1cb956d94c1716dc7d545d2f9540b9#diff-2eeaed663bd0d25b7e608891384b7298
