### ISSUE TITLE
Remove /opt/dist/gluu/oxauth-rp.war from CE and fetch_sources.sh script

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#406]
@nynymike 
I prefer not to download the bits dynamically. oxauth-rp is not really a trusted app, and it should not be deployed in production. The signed package has integrity.

**Comment by adrian-gluu** [comment]
together with davit, we removed the war files in this new build:
https://repo.gluu.org/centos/testing/gluu-server-3.1.3-1-4.centos6.x86_64.rpm
https://repo.gluu.org/ubuntu/pool/main/trusty-devel/gluu-server-3.1.3_1.4~trusty+Ub14.04_amd64.deb
