### ISSUE TITLE
SAML Scope should use domain, not hostname

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#408]
![image](https://user-images.githubusercontent.com/3717101/36051647-7a7badf0-0db0-11e8-9167-b560f54b397c.png)

I believe we can just update the template.

**Comment by yurem** [comment]
Is there generic approach to get domain from hostname? We can try to skip only first part of hostanme like"name." What do you think?
The is the problem because domains not always in format 'org-name.org-type'. There are domain names like `mit.edu`, `ai.mit.edu`

**Comment by nynymike** [comment]
Nevermind... I'm closing this. There is no easy way to tell the domain, and no one has complained.
