### ISSUE TITLE
Import data in 3.1.2 / dependency issue

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#414]
I am trying to upgrade a 2.4.4 to 3.1.2. 
Import script ( https://github.com/GluuFederation/community-edition-setup/blob/master/static/scripts/import2431.py ) in 3.1.2 is spitting dependency issues. 

 - First: 'python-ldap': which need to be installed to run import2431.py
 - Second: below one... I didn't find any package with that name. 

```
root@idp:~# ./import2431.py backup_2431/
Traceback (most recent call last):
  File "./import2431.py", line 32, in <module>
    from ldifschema_utils import OpenDjSchema
ImportError: No module named ldifschema_utils
```

**Comment by mbaser** [comment]
These are not bugs but missing documentation

**Comment by cristichiru** [comment]
Indeed, you need to `yum install -y python-ldap` to solve the dependency and this information needs to be added in the documentation.

**Comment by mbaser** [comment]
installation of python-ldap was in 2.x, and now added to 3.x
