### ISSUE TITLE
Some gluu services not started after VM restart or explicit command line restart

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/community-edition-setup#415]
Environment:
Testing this binary `3.1.3_1.5.BETA2~trusty` using a clean Ubuntu 14 VM
upon installation I chose the following: oxauth/oxtrust/openldap/passport

After installation I restarted the machine and enabled some cust scripts in the UI so oxauth, oxtrust and ldap were fine.

I did a `solserver restart` and got "failed"..

I restarted gluu server, but solserver was still down. I noticed the passport port wasn't shown in the list of open ports either. Then restarted the machine and no luck (LDAP and passport still down).

Some hours passed, I restarted once more, and now LDAP is up!...

I did `service passport status` and got "Node NOT running".

I ran `service passport start` and got "Starting Node: ok".

A few seconds afterwards, I ran `service passport status` and got "Node NOT running".

I hope someone can replicate ...

**Comment by yurem** [comment]
It might be related to this: https://github.com/GluuFederation/community-edition-setup/issues/417
