### ISSUE TITLE
Installer should backup system files before updating them

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#416]
Our installer can configure almost any OS to run CE. But there are few improvements which we need to apply for better user experience:
1. Setup should check if chroot/VM has all required packages for specific OS. We already has methods to determine OS version. We need to add map <os_version:packges_list> for all supported OS. setup can use it for this point and second one.
2. Get admin approval to add user/install missing required packages, etc.
3. Do install as usual but backup system files (everything outside /opt ) before applying CE specific changes.
4. Record in additional log file all OS specific changes (adding users/groups/replacing system files/etc)
5. If there is no /opt/dist/symas/*.<rpm|deb> instalelr should not ask to install OpenLDAP.
The purpose of this is to issue package without OS files for cases when admin want to use all up to date packages.

**Comment by yurem** [comment]
Points 1-2 are implemented. I merged them into 3.1.3

**Comment by mbaser** [comment]
implemented with previous commits
