### ISSUE TITLE
Update node passport init.d script

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#420]
We need to apply same changes which we applied recently to jetty script. Now we get next output in console.

Also script should use similar to jetty subfolder in /var/run .
```
GLUU.root@gomer-vbox:~# service passport start 
Starting Node: ok Tue Apr 10 00:48:59 UTC 2018
GLUU.root@gomer-vbox:~# service passport stop 
Stopping Node: start-stop-daemon: warning: failed to kill 6519: No such process
1 pids were not killed
No process in pidfile '/var/run/passport.pid' found running; none killed.
```

**Comment by ganesh-at-wiw** [comment]
Updated setup.py for using setup.py.

https://github.com/GluuFederation/community-edition-setup/commit/d1fa97cb34c70b685878115928c3bf8a138d2914#diff-2eeaed663bd0d25b7e608891384b7298

**Comment by ganesh-at-wiw** [comment]
Added passport init script:
https://github.com/GluuFederation/community-edition-setup/commit/eb4d1eccf2420840dd4101b1ad65e3e8e165c7e3#diff-5d4db15e913b918be2090e2d066db193

**Comment by ganesh-at-wiw** [comment]
Added location for logs in /etc/defaults/passport
https://github.com/GluuFederation/community-edition-setup/blob/version_3.1.3/templates/node/passport

**Comment by natt-tester** [comment]
Agreed, it's done:
<img width="674" alt="pid" src="https://user-images.githubusercontent.com/38302725/44205400-9b28a300-a199-11e8-9e26-ecee21f85422.png">
