### ISSUE TITLE
3.0.2 --> 3.1.2 upgrade / custom branding for login not working

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#423]
Here is how it looks like if we have a custom login page. Left side of screenshot: 3.1.2 login page. 
![custom_login_page](https://user-images.githubusercontent.com/7156097/39066662-7160a83e-449b-11e8-98e7-6e15acee7b26.png)

**Comment by mbaser** [comment]
we need to disable copying custom pages, there is no way to auto-edit custom pages to work

**Comment by mzico** [comment]
@mbaser : may be we can label it as 'enhancement' then and tackle slowly?

**Comment by mbaser** [comment]
I will disable it

**Comment by mbaser** [comment]
currently disabled

**Comment by yurem** [comment]
@mbaser We can use this commit as [reference](https://github.com/GluuFederation/oxAuth/commit/b731a7de98431fa869d9121ef77ed274e8cf79d8#diff-dfc78be63f0fc0c001ef4197933aa03b)

**Comment by mbaser** [comment]
I tried, but unable to make it work.

**Comment by mbaser** [comment]
closing this issue, as there is no reasonable way to render customer page and apply recent changes to customer page.
