### ISSUE TITLE
2.4.4 --> 3.1.2 upgrade / 'idp' process is not restarting after import in 3.1.2

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#424]
At the time of data importing in 3.1.2, `Idp Configuration Setting...` phase ( upper section of screenshot ) is taking forever and never completed. I had to log into server and manually restart `idp` service ( lower section of screenshot ). 

`idp` is the Shibboleth bit of Gluu Server. 

How to reproduce: 

- Install a 2.4.4 with Shibboleth on
- Export data from 2.4.4 for 3.1.2. Say 'Yes' for Shibboleth. 
- Install 3.1.2
- Import data in 3.1.2

Screenshot: 

![idp_manual_restart](https://user-images.githubusercontent.com/7156097/39121093-2ab0223a-46b6-11e8-986f-ce3e52171ce3.png)

**Comment by mbaser** [comment]
Python hangs on:
p = subprocess.Popen("/usr/sbin/service idp restart", shell=True, stdin=subprocess.PIPE,  stdout=subprocess.PIPE, stderr=subprocess.PIPE)
p.communicate()
