### ISSUE TITLE
2.4.4 --> 3.1.2 upgrade / shib unable to establish localhost:1636 connection

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#428]
It's about OpenDJ to OpenDJ based system. 
After upgrade, 'idp-process.log' is throwing error `Signature check failed` which prohibiting Shibboleth to load it's operation and releasing metadata with "https://[hostname]/idp/shibboleth". 

Error and resolution is stated here: https://github.com/GluuFederation/support-docs/blob/master/troubleshooting/shibboleth/Signature_does_not_match.md

**Comment by mbaser** [comment]
We don’t need to export opendj certificate and than add to truststore, since the script no longer migrates opendj certificate from old server.

**Comment by mbaser** [comment]
closed until someone face this
