### ISSUE TITLE
3.0.2 --> 3.1.1 upgrade / import script not running 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#430]
Followed this doc: https://gluu.org/docs/ce/3.1.1/upgrade/#upgrade-from-30x-to-311 [ OpenLDAP --> OpenLDAP ] 

Error: 

```
[root@upgrade ~]# ./import3031.py backup_3031/
Traceback (most recent call last):
  File "./import3031.py", line 31, in <module>
    from ldifschema_utils import parse_open_ldap_schema
ImportError: No module named ldifschema_utils
[root@upgrade ~]# pip install ldifschema_utils
```

**Comment by mbaser** [comment]
please follow docs
![screenshot from 2018-05-10 17 49 03](https://user-images.githubusercontent.com/6398752/39875851-679ede44-547a-11e8-8a0f-79f8a371302f.png)
