### ISSUE TITLE
Gluu 3.1.3 fail to start after system update

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/community-edition-setup#432]
# Description

I have a Centos 7 with Gluu 3.1.3(the setup.py script is not yet run), the server was installed two days after the final release. 
When i run the command **yum update -y**  i can see that the gluu 3.1.3 is also updated during the process and after update running the command **gluu-serverd-3.1.3 start** fail.

The error message is:
`– Unit systemd-nspawn@gluu_server_3.1.3.service has begun starting up.
May 25 09:23:22 node1.gasmyr.com systemd-nspawn[12584]: No image for machine ‘gluu_server_3.1.3’: No such file or directory
May 25 09:23:22 node1.gasmyr.com systemd[1]: systemd-nspawn@gluu_server_3.1.3.service: main process exited, code=exited`

We may fix it as soon as possible before a customer open a ticket about it. 

Thanks.

**Comment by ganesh-at-wiw** [comment]
As per docs, I think we should follow this point immediately after installation:
https://gluu.org/docs/ce/3.1.3/installation-guide/install/#5-disable-gluu-repositories

What do you think?

**Comment by syntrydy** [comment]
I agree

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/40543548-d95f020e-601c-11e8-9618-d8a65246f49d.png)
We can add it here just after the installation command

**Comment by ganesh-at-wiw** [comment]
@adrian-gluu can we perform above mentioned step in post-install step of the rpm/deb?

**Comment by ganesh-at-wiw** [comment]
This one I mean: https://gluu.org/docs/ce/3.1.3/installation-guide/install/#5-disable-gluu-repositories

You can prefer to change the file or remove the repo altogether.
