### ISSUE TITLE
OpenLdap replication in Gluu 3.1.3 is taking too much time to sync changes

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/community-edition-setup#438]
# Description

After setting up LDAP replication with Gluu 3.1.3 with the latest symas package, both server are taking too much time to since changes.

Sometimes it take over five minutes  to sync a single user's attribute changed.
Sometimes the sync took place after solserver service restart.

We need to find out what may be the root cause of that delay.

NB: Both ldap servers are on the same network.

**Comment by mzico** [comment]
@afroDC @yurem : thoughts?

**Comment by afroDC** [comment]
This is a Symas issue. It's out of our hands. Still awaiting a fix.

**Comment by yurem** [comment]
@willow9886 I offer to close it because we deprecated OpenLdap support

**Comment by willow9886** [comment]
agreed.  closed.
