### ISSUE TITLE
OpenID connect "sub" standard field not returned by UserInfo Request

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/community-edition-setup#44]
Extract of OpenID Connect standard (http://openid.net/specs/openid-connect-core-1_0.htm), §5.3.2 :
The sub (subject) Claim MUST always be returned in the UserInfo Response.
With Gluu 2.2.0, only a field named "inum" is returned with the concerned data.
With Gluu 1.7.0, the field was named "sub" so it was correct. Why its name is now "inum" ? This is not compatible with OpenId connected definition.

**Comment by willow9886** [comment]
Fixed and merged into 2.3.3
