### ISSUE TITLE
RHEL based gluu-server container now showing any message 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#443]
It's RHEL-7.x. 
I know my container is stopped but I just used `/sbin/gluu-serverd-3.1.2 login` and it showed me nothing. For other distributions, the message coming something like "Start Gluu-Server container" or so. 
Not major issue but 'would-be-good' if we can allow this in RHEL based system as well. 

```
[root@ip-xxxx ~]# /sbin/gluu-serverd-3.1.2 login
[root@ip-xxxx ~]# /sbin/gluu-serverd-3.1.2 start
[root@ip-xxxx ~]# /sbin/gluu-serverd-3.1.2 login
Last login: Wed Jun 20 18:01:41 2018 from localhost
-bash-4.2# 
```

**Comment by mzico** [comment]
@ganesh-at-wiw : thoughts?

**Comment by adrian-gluu** [comment]
we replaced gluu-serverd from centos7 on rhel7, now is showing the right msg
