### ISSUE TITLE
Apt-get Remove Gluu Server Leaves Residual Scripts

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/community-edition-setup#446]
Per [this ticket](https://support.gluu.org/installation/5538/update-rcd-error-initscript-does-not-exist-etcinitdgluu-server-313-ubunutu-16044-lts/#at35174) Gluu Server leaves leftover scripts that cause conflicts when trying to install or update Gluu Server.

Also the files `/var/lib/dpkg/info/gluu-server-3.1.3.*` fixes the issue, but it would be best if Gluu Server also removes the scripts.

**Comment by nikdavnik** [comment]
fixed in latest 4.0 packages
