### ISSUE TITLE
Shibboleth IDP client should have its own OpenID client creds

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#447]
"oxTrust Admin GUI" is also the client used for Shibboleth IDP authentication. That's why it has `redirect_uri` `https://hostname/idp/auth-code.jsp` 

It would be better if Shibboleth had it's own client creds, and didn't share them with oxTrust.  This would give us more flexibility to write customize SAML behavior by writing a consent gathering interception script.

Also, it seems from a security perspective that we'd want to be able to differentiate traffic from oxTrust and the IDP.

**Comment by yurem** [comment]
Fixed
