### ISSUE TITLE
Setup should configure site indexes

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#45]
Current setup version creates indexes in userRoot backend only. It should also create required indexes in site backend too.

**Comment by nynymike** [comment]
Very important! Cache refresh won't work without indexes.

**Comment by yurem** [comment]
Fixed: https://github.com/GluuFederation/community-edition-setup/commit/1b69de24cb6a51abe295291b2ef7bfc6d5cfb463
