### ISSUE TITLE
Create additional Couchbase backends during install

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#450]
We need to create 5 buckets per this [config](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/gluu-couchbase.properties#L8) to split data between buckets and allow to specify their type for optional performance.

Here is full list of buckets: gluu (default), gluu_user (for ou=people/ou=group), gluu_session (ou=sessions), gluu_statistic(ou=metric), gluu_site(o=site).

`gluu_session` should has type `Memcached`

Based on this we need to create proper index in each bucket.

@nynymike @mbaser  @afroDC Do you have any suggestions about this?

**Comment by yuriyz** [comment]
@yurem according to #83 we need add Couchbase cache provider. I guess we need `ou=cache` bucket for it.

**Comment by afroDC** [comment]
> specify their type for optional performance.

Can you elaborate on how they can specify their type?

> gluu (default)

I'm assuming this bucket will take everything not included in `sessions`, `group/people`, `metric` and `site`, right?

**Comment by mbaser** [comment]
I implemented this by commit c34f2176bad5eed96aab3327a97ebaeb28e4cd7f
However, current version of gluu is not working when additional buckets created, for this reason I commented them. Additionally:
1) we also need to identify which indexes should be created on each bucket,
2) determine how application ram will be distributed

**Comment by yurem** [comment]
Multiple buckets create works well with Couchbase 6.0.1
