### ISSUE TITLE
Couchbase should not listen by default on all server IPs

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#452]
By default Couchbase server listens on all IPs. It's unsecure. On the other extreme we should allow Couchbase to work in cluster. In any case I offer to reconfigure it to listen only on localhost by default.

**Comment by mbaser** [comment]
I could not fin a way to change bind address of couchbase services. I am afraid there is no way to change.
![screenshot_2018-07-05_17-16-12](https://user-images.githubusercontent.com/6398752/42331117-5282f408-807d-11e8-94f7-a79b01ca6395.png)

**Comment by yurem** [comment]
In this case I think we need to add information about opened ports at the end of Couchbase install before notes about Couchbase license.

Maybe just show Couchabse info in console? It should be usefull for admin. Sample from my VM:
```
Warning: Swappiness is not set to 0.
Please look at https://developer.couchbase.com/documentation/server/current/install/install-swap-space.html as for how to PERMANENTLY alter   this setting.
Minimum RAM required  : 4 GB
System RAM configured : 3.86 GB

Minimum number of processors required : 4 cores
Number of processors on the system    : 2 cores
Unpacking couchbase-server (5.1.0-5552-1) ...
Setting up couchbase-server (5.1.0-5552-1) ...
 * Started couchbase-server

You have successfully installed Couchbase Server.
Please browse to http://ce-dev2.gluu.org:8091/ to configure your server.
Please refer to http://couchbase.com for additional resources.

Please note that you have to update your firewall configuration to
allow connections to the following ports:
4369, 8091 to 8094, 9100 to 9105, 9998, 9999, 11207, 11209 to 11211,
11214, 11215, 18091 to 18093, and from 21100 to 21299.

By using this software you agree to the End User License Agreement.
See /opt/couchbase/LICENSE.txt.
```

**Comment by mbaser** [comment]
I am closing this issue. I had implemented this suggestion https://github.com/GluuFederation/community-edition-setup/issues/452#issuecomment-402791618
