### ISSUE TITLE
Add scopes to cred-manager client only if they are not already defaulted in CE installation

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/community-edition-setup#455]
About this script
https://github.com/GluuFederation/community-edition-setup/blob/version_3.1.3/static/extension/client_registration/CredManager.py

If the underlying installation has one (or more) of [profile, clientinfo, user_name] as default scopes, the whole registration process fails and this is shown in oxauth log:

`Caused by: com.unboundid.ldap.sdk.LDAPException: The provided LDAP attribute oxAuthScope contains duplicate values`

We need to add only the ones required to avoid the duplicate attribute problem.

**Comment by natt-tester** [comment]
I've just tested it with these scopes and there was no error or failure:

<img width="918" alt="scopes" src="https://user-images.githubusercontent.com/38302725/44267306-085b3780-a271-11e8-8daa-73751756e729.png">
<img width="926" alt="scope2" src="https://user-images.githubusercontent.com/38302725/44267321-1610bd00-a271-11e8-8e9f-f3b234becf35.png">
