### ISSUE TITLE
Why is A Temporary Password File Created For Importing LDIF's?

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/community-edition-setup#456]
We should just pass the ldap pass as an argument here, instead of creating a persistent file on disk that's scrubbed when the function is complete. Is there any reason it's done this way?

https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L2874

**Comment by mbaser** [comment]
All shell commands executed by setup.py is logged setup.log (if it gives error, then errorl.log). Some authors are strict about password to be recorded in text file.

**Comment by afroDC** [comment]
Thanks for the explanation @mbaser
