### ISSUE TITLE
Gluu is vulnerable to BEAST

### ISSUE THREAD

**Issue by zeroluck** [GluuFederation/community-edition-setup#457]
Hi,

I was recently reviewing vulnerability scanner results and the way apache is configured in gluu currently leaves it vulnerable to BEAST because TLS 1.0 is available.

Remediation: disable TLS 1.0 in apache configuration

**Comment by zeroluck** [comment]
Submitted https://github.com/GluuFederation/community-edition-setup/pull/458 to address this.

**Comment by yurem** [comment]
Merged already
