### ISSUE TITLE
Passport installation should be offline

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#460]
We need update installer to extract pre-build tar.gz with passport modules into `/opt/gluu/node/passport/node_modules` This should replace [npm](https://github.com/GluuFederation/community-edition-setup/blob/version_3.1.2/setup.py#L1899) command in installer.

This file we will add to each rpm/deb in 3.1.4: /opt/gluu/dist/passport-node_modules.tar.gz

**Comment by mbaser** [comment]
if archive `/opt/gluu/dist/passport-node_modules.tar.gz` exists, it extracts otherwise install as before.
Please put modules archive to `/opt/gluu/dist/` such as:
https://github.com/mbaser/gluu/raw/master/passport-node_modules.tar.gz

**Comment by mbaser** [comment]
closed by commit 5f6d27834794a44dd9daf92e407685e8d565e612

**Comment by nikdavnik** [comment]
implemented in new 3.1.4 builds.

**Comment by mbaser** [comment]
Passport on 3.1.4 uses some more modules, @nikdavnik please update this package:
https://github.com/mbaser/gluu/raw/master/passport-node_modules.tar.gz

**Comment by mbaser** [comment]
working on ubuntu 16 3.1.4.beta2
