### ISSUE TITLE
Support Ubuntu 18.04.1 and deprecate 14.04 support

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#462]
I offer to to build CE 4.0.0 binaries for Ubuntu 18.04.1.  Ubuntu 14.04 support will be ended at April 2019. I think there is no sene to continue support it. The main point to deprecate old OS is that modern OS uses openssl 1.1.x which is needed to support Token Binding in apache2.

@ganesh-at-wiw Can you check if there are replacements for Ubuntu 14.04 in AWS, DigitalOcean, etc..
@mzico What do you think from customer perspective about this idea?
@nynymike  @afroDC What is you opinition?

**Comment by adrian-gluu** [comment]
we already have 4.0 automated buils
