### ISSUE TITLE
Prompt to install all oxAuth integrations or selected only

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#463]
This issue depends on https://github.com/GluuFederation/oxAuth/issues/860 Once it will be resolved setup can use jar with integration to build list of integrations. After selecting required modules script should put xhtml/resources into custom pages folder and add custom script to LDAP.

**Comment by mbaser** [comment]
Since related issue GluuFederation/oxAuth#860 is closed, closing also this issue.
