### ISSUE TITLE
Enable apache2 DDOS protection modules

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#466]
oxAuth/oxTrust by default uses JSF 2.2 protection against CSRF attacks. In addition to this we need to defend Apache against DDoS attack too. After enabling these modules we need to make sure that their settings allow to open oxTrust pages without issues and there is no SCIM server random errors.

**Comment by nikdavnik** [comment]
apaches mod_evasive modules has been enabled in all 3.1.4 packages.
