### ISSUE TITLE
AWS EC2 Setup?

### ISSUE THREAD

**Issue by burkaygur** [GluuFederation/community-edition-setup#47]
What kind of security profile do I need? My HTTP 80 is open, but I dont have access to the server at https://<IPAddress>

Any instructions for EC2?

**Comment by nynymike** [comment]
tcp/80 and tcp/443 needs to be open. 80 only redirects to 443. API's should always use ssl.

If you need any further help, please pose your question on https://support.gluu.org and ask this question there. Github issues are only for bug reports, not requests for support.

**Comment by mzico** [comment]
Open 443 as well, that's https. There is no special requirement for EC2. Gluu Server runs with standard Amazon security profile.
