### ISSUE TITLE
Hide asimba in installation summary

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/community-edition-setup#473]
Please hide to display Asimba component in the summary when it is not prompted during setup.py

hostname xxxx.gluu.org
orgName gluu
os ubuntu
city austin
state tx
countryCode us
support email test@test.com
Applications max ram 7890
Admin Pass xxxxxxx
Install oxAuth True
Install oxTrust True
Install LDAP True
Install JCE 1.8 True
Install Apache 2 web server True
Install Shibboleth SAML IDP True
**Install Asimba SAML Proxy False**
Install oxAuth RP True
Install Passport False

**Comment by ganesh-at-wiw** [comment]
Hi Sahil,

Are we going to phase out Asimba installation along with gluu-server or we're going to use some logic according to which Asimba will be (not)installed. I'll use same logic for (un)hiding.

**Comment by ganesh-at-wiw** [comment]
Okay, I got it.

We're using the switch: **_allow_deprecated_applications_**.

Here is the work done:
https://github.com/GluuFederation/community-edition-setup/commit/5cc6f266505cd55cb01b14ba28ece53b580238ef#diff-2eeaed663bd0d25b7e608891384b7298

Please check and confirm.

**Comment by ganesh-at-wiw** [comment]
@sahiliamsso any comments?
