### ISSUE TITLE
running setup.py shows IP address instead of hostname as default option

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/community-edition-setup#474]
On Ubuntu 16x

** All clear text passwords contained in ./setup.properties.last.

Do you acknowledge that use of the Gluu Server is under the MIT license? [N|y] : y
Enter IP Address [192.168.1.80] :
Enter hostname [**192.168.1.80**] : xxxxxxx
Enter your city or locality : austin
Enter your state or province two letter code : tx

**Comment by mbaser** [comment]
Commit d60a605bfb41d9888a8ecb600dc41e86b3a29619 should fix this.

**Comment by ganesh-at-wiw** [comment]
Mustafa has provided the resolution. I tested it.
