### ISSUE TITLE
Fix typo in installation progress

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/community-edition-setup#477]
Please fix the typo in oxtrust after running setup.py

hostname                                           xxxxxx.gluu.info
orgName                                                      gluu
os                                                         ubuntu
city                                                       austin
state                                                          tx
countryCode                                                    us
support email                                      sahil@gluu.org
Applications max ram                                         6789
Admin Pass                                                 xxxxx
Install oxAuth                                               True
Install oxTrust                                              True
Install LDAP                                                 True
Install JCE 1.8                                              True
Install Apache 2 web server                                  True
Install Shibboleth SAML IDP                                  True
Install oxAuth RP                                            True
Install Passport                                             True

Proceed with these values [Y|n]
Installing [##                               ] Downloading oxAuth RP war file

Installing [########                         ] Installing Jython
Installing [###########################      ] Installing Gluu components: **oxtruest**

**Comment by ganesh-at-wiw** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/66abd93bf994a13e528a2161ddb0a6010fd6d0e8#diff-2eeaed663bd0d25b7e608891384b7298
