### ISSUE TITLE
package not signed for gluu-server-2.3.2-2.el6.x86_64.rpm

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#48]
.....
.....

Total download size: 636 M
Installed size: 1.4 G
Is this ok [y/N]: y
Downloading Packages:
gluu-server-2.3.2-2.el6.x86_64.rpm                                                                                                     | 636 MB     00:30

Package gluu-server-2.3.2-2.el6.x86_64.rpm is not signed
[root@test ~]#

**Comment by jimscarver** [comment]
The workaround is 

yum --nogpgcheck install gluu-server
