### ISSUE TITLE
low level creation of users with duplicate uids possible

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/community-edition-setup#481]
In 3.1.4RC, after exporting a given user entry to ldif, then changing `inum` and `dn`, and re-importing, the operation is successful

I can have 2 admin users...

However, creation of duplicate users in oxtrust is not possible

**Comment by mbaser** [comment]
commit e3fe9db94fe1513bc9b521a33ff3452a28fdcd42 closed this issue
