### ISSUE TITLE
Typo when restarting the Gluu Server

### ISSUE THREAD

**Issue by shmorri** [GluuFederation/community-edition-setup#483]
After running the upgrade script from 3.1.3 to 3.1.4, I noticed the following typo while restarting the Gluu Server:

![image](https://user-images.githubusercontent.com/36208047/46097764-53c60700-c188-11e8-80b5-76780ad79c60.png)

OpenDJ is misspelled. This may be present in other versions, as well.

**Comment by adrian-gluu** [comment]
sorted on 4.0
