### ISSUE TITLE
Build development package for CE

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#484]
Package should contains in /opt/dist/tools:
eclipse-java-oxygen-3a-linux-gtk-x86_64.tar.gz
PyDev 6.5.0.zip
pydevd-1.4.0.tar.gz

This is what installation script should do:
1. Ask user to install gtk 3.0 libraries.
2. apt-get install libgtk-3-0
3. cd /opt
4. tar -xzf /opt/dist/tools/eclipse-java-oxygen-3a-linux-gtk-x86_64.tar.gz
5. mv eclipse eclipse-oxygen-3a
6. ln -sf /opt/eclipse-oxygen-3a /opt/eclipse
7. cd /opt/eclipse
8. unzip /opt/dist/tools/PyDev\ 6.5.0.zip
9. mkdir -p /opt/libs
10. cd /opt/libs
11. tar -xzf /opt/dist/tools/pydevd-1.4.0.tar.gz
12. ln -sf /opt/libs/pydevd-1.4.0 /opt/libs/pydevd

Open questions:
13. Copy from user host /home/user/.Xauthority to /opt/gluu-server-3.1.4/root
14. export "DISPLAY=:0". Value of this variable we should take from host: export | grep DISPLAY

These are sample developer actions:
1. Run /opt/eclipse/eclipse &
2. Open Debug perspective
3. Start the remote debugger server by navigating to Menu > PyDev > Start Debug Server
4. Change location of script to file system
5. Modify script in file system. Add commands to enable debugger

**Comment by mbaser** [comment]
Implemented
[install.py.txt](https://github.com/GluuFederation/community-edition-setup/files/2460852/install.py.txt)

[prepare-dev-tools.py.txt](https://github.com/GluuFederation/community-edition-setup/files/2460855/prepare-dev-tools.py.txt)
