### ISSUE TITLE
Clean Up Apache Config

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/community-edition-setup#486]
Currently our Apache configuration looks messy, has leftover commented sections and inprecise tabbing all over. We should clean this up for legibility.

**Comment by ganesh-at-wiw** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/184baa65a2cba6d75f37b23224575726294f56b8#diff-03977dfe18120f823fed2a0408021ef1
