### ISSUE TITLE
Gluu-server should export JAVA_HOME, NODE_HOME and OPENDJ_HOME and modify PATH

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#488]
After log into Ubuntu 16 and probably other similar OS CE variables JAVA_HOME, NODE_HOME and OPENDJ_HOME, PATH are not set.

In other OS our solution with profile modification works well: https://github.com/GluuFederation/community-edition-setup/blob/master/templates/system_profile
We need to find similar approach for these OS.

**Comment by mbaser** [comment]
Debian Stretch is `systemd` and due to this compassion:
```
if self.os_initdaemon == 'init':
```
System profile is not updated. I think this comparison is needed only for:
```
if [ "$(ls -A /dev/pts/)" != "" ] && [ "$(ls -A /proc/)" != "" ] && [ "$(ls -A /lib/modules/)" != "" ] && [ "$(ls -A /sys/class/net/lo/)" != "" ] && [ "$(ls /dev/ | grep -vE 'null|pts')" != "" ]; then
	echo "Welcome to the Gluu Server!"
else
	echo "Gluu server is not started, please start it from root machine by service gluu-server start"
	exit
fi
```
So we need to split path update and these.

**Comment by mbaser** [comment]
And, I am not sure why we are appending to `/etc/profile` rather than writing to `/etc/profile.d`
