### ISSUE TITLE
Create Static Inum's

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/community-edition-setup#489]
Currently when the LDAP is rendered with `setup.py` we create unique identifiers where they are not necessary. For example:

```
inum=@!77DF.4072.981D.7349!0001!0244.0538!0000!BA97.20F7.7AD0.198D,ou=people,o=@!77DF.4072.981D.7349!0001!0244.0538,o=gluu
```

The only identified here that needs to be unique is `!BA97.20F7.7AD0.198D`, otherwise the rest can be the same across all Gluu Server installations. The following would suffice:

```
inum=@!0000.0000.0000.0000!0001!0000.0000!0000!BA97.20F7.7AD0.198D,ou=people,o=@!0000.0000.0000.0000!0001!0000.0000,o=gluu
```

Removing the GUID's would be ideal, but the current structure of the LDAP seems to be hard-coded. This would be a grand undertaking, and would require some complex data manipulation. In the mean-time, going forward, we can make operations and migration much easier by not having unnecessarily complicated inums, when they serve no purpose.

Refer to https://support.gluu.org/identity-management/6145/export-import-users/ for a sample use case.

**Comment by yurem** [comment]
We can close it because new one https://github.com/GluuFederation/community-edition-setup/issues/522 deprecated orgInum, applianceInum
