### ISSUE TITLE
Avoid SCIM hardcoded value for UMA Resource Id

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/community-edition-setup#492]
Please check
https://github.com/GluuFederation/community-edition-setup/blob/version_3.1.3/templates/scim.ldif#L45

Reported by https://support.gluu.org/access-management/6237/uma-resource-id-hardcodedstatic/#at40960

**Comment by afroDC** [comment]
@yuriyz can you tell me the formatting we have for oxId's so @mbaser can use some method (if it doesn't exist already) in setup.py to create them in the proper format? The default one `oxId=0f13ae5a-135e-4b01-a290-7bbe62e7d40f` Seems to be an (8)-(4)-(4)-(12) in lower-case hex, but I could be wrong.

@mbaser [this line](https://github.com/GluuFederation/community-edition-setup/blob/version_3.1.3/templates/scim.ldif#L45) needs to be something like this:

```
# SCIM Resource
dn: oxId=$(scim_resource_uma_id)ou=resources,ou=uma,o=%(inumOrg)s,o=gluu
objectClass: oxUmaResource
objectClass: top
displayName: SCIM Resource
owner: inum=%(inumOrg)s!0000!A8F2.DE1E.D7FB,ou=people,o=%(inumOrg)s,o=gluu
oxFaviconImage: http://www.gluu.org/img/scim_logo.png
oxAssociatedClient: inum=%(scim_rs_client_id)s,ou=clients,o=%(inumOrg)s,o=gluu
oxAuthUmaScope: inum=%(inumOrg)s!0010!8CAD.B06D,ou=scopes,ou=uma,o=%(inumOrg)s,o=gluu
oxId: 0f13ae5a-135e-4b01-a290-7bbe62e7d40f
oxResource: https://%(hostname)s/identity/restv1/scim/v2
oxRevision: 1
```

Another variable could be [added here](https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L530) which would contain `scim_resource_uma_id = None` which would be populated similar to [this portion of setup.py](https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L837).
