### ISSUE TITLE
Setup - list index out of range

### ISSUE THREAD

**Issue by msantic** [GluuFederation/community-edition-setup#493]
Ubuntu 14.04

Do you acknowledge that use of the Gluu Server is under the MIT license? [N|y] : y
Enter IP Address [192.168.139.128] : 
Enter hostname : ----
Enter your city or locality : 
Enter your city or locality : 
Enter your city or locality : 
Enter your city or locality : zg
Enter your state or province two letter code : hr
Enter two letter Country Code : hr
Enter Organization Name : gc
Enter email address for support at your organization : ----
Enter maximum RAM for applications in MB [3072] : 
Optional: enter password for oxTrust and LDAP superuser [6MxQR8Kf7l0h] : 
Install oxAuth OAuth2 Authorization Server? [Yes] : 
Install oxTrust Admin UI? [Yes] : 
Install Backend DB Server? [Yes] : 
Traceback (most recent call last):
  File "./setup.py", line 4109, in <module>
    installObject.promptForProperties()
  File "./setup.py", line 2469, in promptForProperties
    option=self.getPrompt(prompt_text, options[0])
IndexError: list index out of range

**Comment by msantic** [comment]
3.1.4

**Comment by mbaser** [comment]
I just installed **gluu-server-3.1.4_1-2~trusty+Ub14.04_amd64.deb** on Ubuntu 14, could not replicate this issue. The above can only be raised by `setup.py` for version 4 (beta). Closing this issue until someone replicate.
