### ISSUE TITLE
OpenDJ init Script Fixes

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/community-edition-setup#497]
The script in `/etc/init.d/opendj` for OpenDJ specifies the OPENDJ_JAVA_HOME as `/usr/java/latest`. This should point to `/opt/jre` as `/usr/java/latest` is undefied as far as I can tell.

The chkconfig command in the CDDL header is identified as `# chkconfig: 345 95 5`. According to [https://www.tldp.org/HOWTO/HighQuality-Apps-HOWTO/boot.html](https://www.tldp.org/HOWTO/HighQuality-Apps-HOWTO/boot.html)[0], this means that OpenDJ is scheduled to start last, when it should be started first. The remaining services should also have some start dependency based on OpenDJ.

> [0] Although these are comments, they are used by chkconfig command and must be present. This particular line defines that on runlevels 2,3,4 and 5, this subsystem will be activated with priority 95 (one of the lasts), and deactivated with priority 05 (one of the firsts).

**Comment by natt-tester** [comment]
Checked the first issue: it's DONE.

<img width="411" alt="obraz" src="https://user-images.githubusercontent.com/38302725/50287860-72285f80-0464-11e9-9ab2-175000625620.png">

Closing the issue as the second part can be checked in #499.
