### ISSUE TITLE
Why Do We Change The Hostname Inside The Chroot?

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/community-edition-setup#498]
There seems to be no reason why the host containers hostname is changed and also that we had the external ip address + hostname into `/etc/hosts`.

**Comment by mbaser** [comment]
If you are inside container, you don't have access to /etc/hosts file outside of the container. And if you don't have DNS entry for hour hostname, your hostname resolution will fail inside of the container. Having ip-hostname pair in /etc/hosts file outside of the container, won't make hostname resolution inside the container.

**Comment by mbaser** [comment]
Some network services uses hostname to identify itself. So if you don't set hostname inside container, some services may misbehave, and hostname outside of the container do not have any effect inside.

**Comment by mbaser** [comment]
Even I unset hostname or set to `localhost` gluu ui seems work.
