### ISSUE TITLE
Upgrade to 3.1.4 with export/import script - Shibb IDP Client is misconfigured

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#500]
If we upgrade to 3.1.4 with data collected and pushed through export/import script; one of the most important client named `IDP Client` remain misconfigured. This is very important client for shibboleth bit to work in 3.1.4. 

Workaround is available here: https://github.com/GluuFederation/support-docs/blob/master/troubleshooting/shibboleth/UPGRADE/Client_IDP_client_missing.md

**Comment by mbaser** [comment]
This is not an upgrade issue, but something with setup.py. I just installed 3.1.4 with setup.properties created by export3031.py, it contains None named IDP client.
![screenshot_2018-12-12_23-55-34](https://user-images.githubusercontent.com/6398752/49898229-7ef7f280-fe69-11e8-84ee-24585e2b17d4.png)
So setup.py did not created these variables: `idp_client_id` and `idpClient_encoded_pw`

**Comment by mbaser** [comment]
Commits 4b7d595e80912b26a74fee709174f1541e0a4da9 and ed054e7fa3192a6b17076b8c7f041886eabb7a9b closed this issue, should be fixed in `import2431.py`
