### ISSUE TITLE
login after installation is not working

### ISSUE THREAD

**Issue by rassiel** [GluuFederation/community-edition-setup#51]
I downloaded and installed gluu community edition last week, and it worked like a charm. Today I tried a new installation and when trying to login I'm getting a "Not Found".

Attemp to go to: https://gluu-server.cloudapp.net
URL will be:
https://gluu-server.cloudapp.net/oxauth/authorize?scope=openid+profile+email+user_name&response_type=code+id_token&nonce=nonce&redirect_uri=https%3A%2F%2Fgluu-server.cloudapp.net%2Fidentity%2Fauthentication%2Fauthcode&client_id=%40%21FA92.A5C9.2D35.DA41%210008%21F9F1.BC88

![image](https://cloud.githubusercontent.com/assets/8739469/9315233/01ca9648-44fc-11e5-875a-05d71649cd24.png)

**Comment by mzico** [comment]
@rassiel : We are releasing new Gluu Server 2.3.3. Please check the status of installation tomorrow.

**Comment by rassiel** [comment]
ohh... great, thanks for you quick answer!!!

**Comment by yurem** [comment]
Please, reopen this issue if needed.
