### ISSUE TITLE
How to pass a user defined parameter to setup.py?

### ISSUE THREAD

**Issue by Yamilquery** [GluuFederation/community-edition-setup#510]
Hi everyone!

We are creating a Terraform infrastructure, including a Gluu Server setup, but we need to automate the server creation and configuration, for that reason we need to know if it's possible to pass the initial parameters via terminal.

Thank you!

**Comment by mbaser** [comment]
You can write initial parameters to `/install/community-edition-setup/setup.properties` and then run setup.py, see sample file `/install/community-edition-setup/setup.properties.sample`

**Comment by Yamilquery** [comment]
Thank you very much, it works!

**Comment by Yamilquery** [comment]
I'm sorry, this works fine, but there is some issue because of the confirmation prompt "Proceed with these values [Y|n]". Is there some way to force the setup.py?

**Comment by mbaser** [comment]
Use argument `-n` 
To see other arguments `-h`

**Comment by mbaser** [comment]
Please use support system, we don't use github issues for help.
