### ISSUE TITLE
Setup fails on Ubuntu Server 18.04.1

### ISSUE THREAD

**Issue by mkauzlar** [GluuFederation/community-edition-setup#521]
gluu-server-3.1.5 (and 6):

...
Install oxAuth OAuth2 Authorization Server? [Yes] : 
Install oxTrust Admin UI? [Yes] : 
Install LDAP Server? [Yes] : 
Traceback (most recent call last):
  File "./setup.py", line 3699, in <module>
    installObject.promptForProperties()
  File "./setup.py", line 2394, in promptForProperties
    option=self.getPrompt(prompt_text, options[0])
IndexError: list index out of range

gluu-server-4.0:

...
Install oxAuth OAuth2 Authorization Server? [Yes] : 
Install oxTrust Admin UI? [Yes] : 
Install Backend DB Server? [Yes] : 
Traceback (most recent call last):
  File "./setup.py", line 4046, in <module>
    installObject.promptForProperties()
  File "./setup.py", line 2445, in promptForProperties
    option=self.getPrompt(prompt_text, options[0])
IndexError: list index out of range

**Comment by mbaser** [comment]
You are running setup.py out of container. Follow these instructions: https://gluu.org/docs/ce/3.1.5/installation-guide/install/

**Comment by apichick** [comment]
I am running the 3.1.6 installation on an ubuntu 16.04 vm and I am getting exactly the same problem.

**Comment by willow9886** [comment]
Please funnel support requests through https://support.gluu.org 

Thanks.
