### ISSUE TITLE
Replace python 2.7 with python 3.x

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/community-edition-setup#525]
Python 2.7 is near EOL, we need to replace with Python 3.x in all our containers.

**Comment by mbaser** [comment]
It may not be possible to completely remove python2.7 on  CentOS7 and RHEL since yum still uses python2.7 At least we must include python3.x on these containers.

**Comment by iromli** [comment]
An option is to write code that works on Python 2.7 and 3, for smooth transition. There are Python library that can help us, i.e. `six` library.

**Comment by nikdavnik** [comment]
python 3 have been installed in all 4.0 chroots: Please use python2 for version 2 and python3 for version 3
