### ISSUE TITLE
Generate initial JWKS with expiration time `keyRegenerationInterval` + `idTokenLifetime`

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#527]
Current count of days is 365. But `keyRegenerationInterval` is 2 days. We need to fix this.

**Comment by mbaser** [comment]
`keyRegenerationInterval` is 48 (2days)
 `idTokenLifetime`  is 3600 (1 hour?)

What to do? set `self.default_key_expiration` to two days?

**Comment by yurem** [comment]
yes

**Comment by iromli** [comment]
@mbaser aren't we going to change expiration to hours instead? ref: https://github.com/GluuFederation/oxAuth/issues/1047
