### ISSUE TITLE
Move all service startup scripts to systemd on CentOS7

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/community-edition-setup#532]
When we install couchbase on CentOS7, oxauth starts before couchbase server. Couchbase server started via systemd and oxauth is started via init.d scripts. We should move all to systemd scripts in order to be able to set service startup ordering.
![Screenshot_2019-05-06_20-20-02](https://user-images.githubusercontent.com/6398752/57246890-0cb9c180-7047-11e9-8ce6-5e147b816be5.png)

**Comment by nikdavnik** [comment]
In latest 4.0 packages we have systemd scripts
