### ISSUE TITLE
All attributes metadata should have filled gluuSAML1URI and gluuSAML2URI

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#536]
oxTrust can fill them at runtime. It loads data from LDAP schema. Couchbase can't provide such details. We need to prefill these attribute to not depend on LDAP schema.

Here are sample details for uid:
```
Attribute name

SAML2: urn:oid:0.9.2342.19200300.100.1.1
SAML1: urn:mace:dir:attribute-def:uid
Attribute source

uid (LDAP)
```

**Comment by mbaser** [comment]
I am attaching the script for future use
[attributes_add_metadata.py.zip](https://github.com/GluuFederation/community-edition-setup/files/3198394/attributes_add_metadata.py.zip)
