### ISSUE TITLE
Clean up Ubuntu 18 package

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#539]
1. According to this we not install token binding module as package:
dpkg -S /usr/lib/apache2/modules/mod_token_binding.so
dpkg-query: no path found matching pattern /usr/lib/apache2/modules/mod_token_binding.so

We need to build rpm/deb and use package to install module. The are many pluses of this:
 - it's easy to maintain it
 - it's easy to update it
 - not needed to install many dev packages which led to CE package size increase

2. There are temp dirs: ` mod_token_binding`, `token_bind`.
3. Why we need this link `gluu-server-4.0 -> /opt/gluu-server-4.0`?
4. After installing mod_token binding from package we need to uninstall dev package and purge caches to decrease package size.

**Comment by yurem** [comment]
It will be nice to add root user bash history clean on build

**Comment by nikdavnik** [comment]
@yurem where this link is located gluu-server-4.0 -> /opt/gluu-server-4.0 ?
I can not find it.

**Comment by yurem** [comment]
![image](https://user-images.githubusercontent.com/6104200/58486936-77a27800-816f-11e9-9d90-febcd3c7af90.png)

**Comment by nikdavnik** [comment]
Tested ubuntu18 package ub fresh VM. This link is not present. I guess its something specific with your VM.
![gluu_install2](https://user-images.githubusercontent.com/17772064/58549317-46cc4c80-821c-11e9-8f43-ba1bbee682f4.png)

**Comment by nikdavnik** [comment]
@yurem mot_tocken_binding can not be installed from package as right now its available only from https://github.com/zmartzone/mod_token_binding/ this repo and can be installed by source building. 

So should we keep or delete mod_token_binding from ubuntu18 ?

**Comment by mbaser** [comment]
This model was last updated on on Aug 29, 2019, I think it is dead.

**Comment by yurem** [comment]
yes, It's departed update
