### ISSUE TITLE
Setup.py update for couchbase-server-community edition

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/community-edition-setup#545]
Steps to reproduce:
1. Copy couchbase-server-community-5.1.1-centos7.x86_64.rpm in /opt/dist/couchbase
2. Run setup.py

Script shows Installation is successful but setup.log shows it couldnt find the enterprise package.
```
Installing [#################                ] Generating crypto
Installing [##################               ] Generating oxauth openid keys
Installing [##########################       ] Installing Gluu components: Couchbase

 Gluu Server installation successful! Point your browser to https://autoqa.gluu.org
```

setup.log
```
11:58:19 06/04/19 Couchbase package not found at /opt/dist/couchbase. Exiting with error...
11:58:19 06/04/19 ***** Error caught in main loop *****
11:58:19 06/04/19 Traceback (most recent call last):
```

Expected Output: Setup.py should either fail saying that "Community edition for couchbase is not supported, Please download enterprise edition" or provide support for community edition.

**Comment by mbaser** [comment]
fixed by commit eb4997b46913dbff9aa70ad5dc90e65ae2d0aa5e
