### ISSUE TITLE
Not bug report / open for discussion: Possibility of rotating admin password

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#547]
This raised by one customer. This issue is not about bug report or feature request but more like discussion and possibility.

Do you think it's okay to rotate 'admin' password? 'admin' password is that password which is being generated during installation and for oxTrust admin feature + ldap administrative credential. 

@nynymike @yurem @yuriyz @ganesh-at-wiw @mbaser @willow9886

**Comment by mbaser** [comment]
For me password rotation is not a good idea.

**Comment by mbaser** [comment]
No discussion on this topic. Closing
