### ISSUE TITLE
installing glue package not found

### ISSUE THREAD

**Issue by rassiel** [GluuFederation/community-edition-setup#55]
Hi. I'm trying to do a fresh gluu install on  Ubuntu 14.04.3 LTS
````
echo "deb http://repo.gluu.org/ubuntu/ trusty main" > /etc/apt/sources.list.d/gluu-repo.list 
curl http://repo.gluu.org/ubuntu/gluu-apt.key | apt-key add - 
apt-get update 
apt-get install gluu-server
````
at this point I'm getting *Unable to locate package gluu-server*

**Comment by willow9886** [comment]
Hey Rassiel, can you open this as a ticket on http://support.gluu.org? Thanks in advance.
