### ISSUE TITLE
Replace OpenDJ with WrendDS

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#562]
OpenDJ should be optional

**Comment by mbaser** [comment]
Now opendj is optional, to install opendj run setup.py with:
`setup.py --opendj`

opendj will be downloaded from https://ox.gluu.org/maven/org/forgerock/opendj/opendj-server-legacy/3.0.1.gluu/opendj-server-legacy-3.0.1.gluu.zip as we do for openJDK

**Comment by mbaser** [comment]
@nikdavnik Please close this issue after you had finished your part.

**Comment by mbaser** [comment]
@nikdavnik Please remove opendj-server-legacy-3.0.1.gluu.zip from container

**Comment by mbaser** [comment]
implemented in beta3
