### ISSUE TITLE
missing LSB information

### ISSUE THREAD

**Issue by rngadam** [GluuFederation/community-edition-setup#57]
```
09:58:43 09/04/15 update-rc.d: warning: /etc/init.d/tomcat missing LSB information
09:58:43 09/04/15 update-rc.d: warning: /etc/init.d/opendj missing LSB information
09:58:43 09/04/15 update-rc.d: warning: /etc/init.d/tomcat missing LSB information
```

update-rc.d: see http://wiki.debian.org/LSBInitScripts

**Comment by willow9886** [comment]
@adrian-gluu can you resolve this before the upcoming 2.4.2 release?

**Comment by yurem** [comment]
It's not mandatory information which not lead to any services startup problems. I'm mowing this to 3.0.1

**Comment by ganesh-at-wiw** [comment]
We've updated the init script to comply with LSB and it works fine.
