### ISSUE TITLE
Setup should be deployed as setup.zip

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#570]
We need to put setup as `/opt/dist/gluu/setup.zip|tgz` instead of `/install/community-edition-setup` into CE package.
Also we need to add `/opt/gluu/bin/install.sh|py` which should unzip setup archive into ``/install/community-edition-setup` and run it.

This should simplify package upgrade process.

**Comment by mbaser** [comment]
@nikdavnik please;
1. put `install.py`  to `/opt/gluu/bin` as executable file.
1. download community-edition-setup to `/opt/dist/gluu/community-edition-setup-<version>*.zip`
 `wget -nv https://github.com/GluuFederation/community-edition-setup/archive/master.zip -O /opt/dist/gluu/community-edition-setup-master.zip`

**Comment by yurem** [comment]
Link to install.py: https://github.com/GluuFederation/community-edition-setup/blob/master/install.py

**Comment by mbaser** [comment]
Fully implemented in beta4
