### ISSUE TITLE
Package manger should do upgrade without CE data loss

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#575]
We need to review all deb/rep pre/post/etc script to make sure that they handle upgrade flow well. Also upgrade process should not overwrite configuration files which setup update during install.

**Comment by nikdavnik** [comment]
Implemented in latest builds. 
This may need some more work at time when we release 4.1. So we can test upgrade from 4.0 to 4.1. 
Closing this issue for now.
