### ISSUE TITLE
Create new indexes for CB 

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#581]
Setup should create next indexes: in CB backend
CREATE INDEX `gluu_user_uid_oc` ON `gluu_user`(`uid`) WHERE (`objectClass` = "gluuPerson")
CREATE INDEX `gluu_token_grtId_oc` ON `gluu_token`(`grtId`) WHERE (`objectClass` = "token")

**Comment by mbaser** [comment]
There is `uid` index on bucket `gluu_user`:
https://github.com/GluuFederation/community-edition-setup/blob/3c7ece9e4d86aa34c00993432875385f1bbfd4ea/static/couchbase/index.json#L7

**Comment by mbaser** [comment]
Index `gluu_token(grtId)` was added
https://github.com/GluuFederation/community-edition-setup/commit/46b5e9c6f8ef356b7f60f5b873aa1a48c504c5f2

**Comment by yurem** [comment]
@mbaser I added missing part to indexes above `WHERE` statement
