### ISSUE TITLE
Datatype inconsistencies when using CouchBase

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/community-edition-setup#583]
I have observed 2 sources of inconsistencies with respect to how data is inserted in Couchabase:

1. Upon installation, generalizedTime values are inserted as strings. Example:

	```
	{
	  "uid": "test",
	  "birthdate": "20170907123010.485Z",
	  ...
	}
	```

1. Using oxtrust, both boolean and generalizedTime values end up inserted as strings. Example:

	```
	{
	  "uid": "test",
	  "gluuSLAManager": "false",
	  "oxCreationTimestamp": "20190818200526.021Z",
	  ...
	}


The couple of scenarios above can be troublesome. For instance, in SCIM, query filters can be built based on date values comparison.

As an example, the following are valid generalizedTime values: `2014010203+04`, `2014010203Z`, and `2014010203-04` (generalizedTime syntax is explained [here](https://ldap.com/attribute-syntaxes/) - near the bottom. )

It holds (in time terms) that:

`2014010203+04` < `2014010203Z` < `2014010203-04`

But lexicograhically comparisons do not always work, eg: `"2014010203Z" > "2014010203-04"`

Similar problems can happen with booleans.

In general, we should adhere to (LDAP) schema in order to know the data type for insertions in couchbase jsons.

For generalizedTime my proposition is to convert values into the equivalent numeric timestamp like number of milliseconds since Jan 1st 1970 00:00:00 UTC (unix epoch). 

I'm not sure how we are doing with certificate and binary attribute syntaxes and if that deserves some attention too

**Comment by jgomer2001** [comment]
This is where setup.py is converts ldif content to json
https://github.com/GluuFederation/community-edition-setup/blob/9000e860a1f3bcf2b9a2e7799588e34e9d838bca/setup.py#L4130

**Comment by yurem** [comment]
CouchBase ORM uses ISO-8601 date format. Here is java data format which it uses:
```
SimpleDateFormat jsonDateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");

Sample result:
2019-09-06T19:33:44.094+0300
```
I think this format is allow to compare dates stored as string.
We need to fix setup to use same data format.

Regarding Boolean. For me we need to use JSON/LDAP Boolean types.
In 4.0 we reviewed attribute data types. Now we uses boolean in setup if data type in schema is boolean.
But ORM don't use schema to check it type. It relay on data types specified in java code. It knows date, int, boolean types

**Comment by yurem** [comment]
@mbaser can you check if setup uses ISO-8601 data type during inserting entries into CB?

**Comment by mbaser** [comment]
After implementation, `birdthdate` becomes:
```
"birthdate": "2017-09-07T12:30:10.485000"
```
