### ISSUE TITLE
Automatically re-new license file for super gluu.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/community-edition-setup#587]
In Super Gluu authentication script we have code that validates license file. It is here:

https://github.com/GluuFederation/community-edition-setup/blob/999368187682db557d50a920fe662850fe3d9dc4/static/extension/person_authentication/SuperGluuExternalAuthenticator.py#L117

Problem is that when license is expired then we have to re-generated that file and give it to customer. Customer has to replace it on their machine (as described in support ticket here https://support.gluu.org/other/7458/supergluu-license/).

One idea is to write python script (triggered by cron periodically) which can automatically replace `license` json value inside the file with re-generated license taken from `https://license.gluu.org/oxLicense/rest/generate?licenseId=<license id from file here>`.

Reference:
https://github.com/GluuFederation/support-docs/blob/master/super_gluu/licensing/deployment.md

**Comment by yurem** [comment]
There is another enpoint `https://license.gluu.org/oxLicense/rest/metadata` which can give you details about license expiration time

**Comment by yurem** [comment]
@yuriyz  is there process in oxLicensse which regenerates licenses? Is it regenerate license after expiration or before hand to allow client avoid outages related to expired license?

**Comment by mbaser** [comment]
Implemented by commits
d33f849a37587018b05d4f81214528d14f750cbb
1b19f17b4de1e610c013bb50edcefb3357dc26ea

The script runs once a day through `/etc/cron.daily/super_gluu_lisence_renewer`
First it check license metadata if there is less than a day to expire. If so, it renews  license.
