### ISSUE TITLE
During oxauth build jenkins should copy profile files from target build server.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/community-edition-setup#591]
Currently during installation with '-t' option, setup imports test data where inside we have generated passwords. To run oxauth jenkins job right now we are forced to copy manually files from '/install/community-edition-setup/output/test/oxauth' to 

- https://github.com/GluuFederation/oxHudsonProfiles/tree/master/oxAuth/Server/profiles/ce-dev5.gluu.org
- https://github.com/GluuFederation/oxHudsonProfiles/tree/master/oxAuth/Client/profiles/ce-dev5.gluu.org

When we trigger oxauth build jenkins downloads these files.from github and executes build.

We want to avoid manual copy and force jenkins copy files from build server ( e.g. ce-dev5.gluu.org) directly to jenkins machine and then run tests.

**Comment by nikdavnik** [comment]
Added commands to download /install/community-edition-setup/output/test/oxauth from server to jenkins workspace. But in  server client_keystore.jks file is missing. (this one https://github.com/GluuFederation/oxHudsonProfiles/blob/master/oxAuth/Client/profiles/ce-dev5.gluu.org/client_keystore.jks)
So if test data are generated then client_keystore.jks also should be generated, so we can download it from server to jenkins. I will open subticket for it

**Comment by yuriyz** [comment]
It is not solved yet, we need successfil jenkins build with this new approach in order to close it.

**Comment by nikdavnik** [comment]
Configured Jenkins job https://ox.gluu.org/jenkins/job/oxAuth_4.2_LDAP/configure to get profile files from target build server. @yuriyz please check and confirm

**Comment by yuriyz** [comment]
@nikdavnik I've compared files. It looks good, lets see how test runner consume it. (cc @yurem )

**Comment by mbaser** [comment]
@yuriyz @yurem Can we close this issue?

**Comment by yuriyz** [comment]
Yes, it's done. Closing.
