### ISSUE TITLE
Brand new Ubuntu 18.04 server. /etc/hosts being deleted by Gluu-server install

### ISSUE THREAD

**Issue by zimage** [GluuFederation/community-edition-setup#594]
```
tnowaczyk@recipe:~$ sudo apt-get install gluu-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  gluu-server
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/794 MB of archives.
After this operation, 1,532 MB of additional disk space will be used.
Selecting previously unselected package gluu-server.
(Reading database ... 105472 files and directories currently installed.)
Preparing to unpack .../gluu-server_4.0-rc1-90~bionic+Ub18.04_amd64.deb ...
Unpacking gluu-server (4.0-rc1-90~bionic+Ub18.04) ...
Setting up gluu-server (4.0-rc1-90~bionic+Ub18.04) ...
Created symlink /etc/systemd/system/machines.target.wants/systemd-nspawn@gluu_server.service → /lib/systemd/system/systemd-nspawn@gluu_server.service.
Starting gluu-server ...
Extracting community-edition-setup package
mv: cannot stat '/etc/hosts.orig': No such file or directory
dpkg: error processing package gluu-server (--configure):
 installed gluu-server package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 gluu-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by zimage** [comment]
/etc/hosts gone after the apt-get install drops back to shell. If I recreate /etc/hosts and continue the install, I get the following.

`tnowaczyk@recipe:~$ sudo apt-get install gluu-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
gluu-server is already the newest version (4.0-rc1-90~bionic+Ub18.04).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up gluu-server (4.0-rc1-90~bionic+Ub18.04) ...
/bin/cp: cannot stat '/opt/gluu-server/tmp/gluu-serverd': No such file or directory
dpkg: error processing package gluu-server (--configure):
 installed gluu-server package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 gluu-server
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by willow9886** [comment]
Yes.. sorry for the issue. We're working on the Ubuntu 18 package right now. Will be fixed and operational shortly.

**Comment by nikdavnik** [comment]
Hi, I removed broken package from repo, Please use previous builds till we can build new package.
Thanks,

**Comment by nikdavnik** [comment]
Fixed in new builds.

**Comment by Pdubey1994** [comment]
### **Please help I am getting the below error**

### ****
# apt-get install gluu-server
Reading package lists... Done
Building dependency tree
Reading state information... Done
gluu-server is already the newest version (4.2.3~ubuntu18.04).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
Setting up gluu-server (4.2.3~ubuntu18.04) ...
/bin/cp: cannot stat '/opt/gluu-server/tmp/gluu-serverd': No such file or directory
dpkg: error processing package gluu-server (--configure):
 installed gluu-server package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 gluu-server
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by nynymike** [comment]
If you want support on the Gluu Server Community Edition, you need to register and post on https://support.gluu.org
