### ISSUE TITLE
Firefox can't find server at ce.gluu.info

### ISSUE THREAD

**Issue by wrabbit-revisited** [GluuFederation/community-edition-setup#6]
I'm running Centos 6.5 on VirtualBox. I followed the instructions, with the following differences for setup.py:
asked to update hostname, hosts, and resolv.conf files
asked to download latest oxAuth and oxTrust WAR files

The startup.py says the Gluu server installation was successful and i can ping "ce.gluu.info", but Firefox cannot find a server at https://ce.gluu.info.

**Comment by willow9886** [comment]
I'm going to close. Check out our latest release if you still having trouble. Thanks!
