### ISSUE TITLE
Support for Letsencrypt certificates and custom Certificates

### ISSUE THREAD

**Issue by AgelM** [GluuFederation/community-edition-setup#604]
Currently the Gluu Server setup script generates Self-Signed certificates for use by the internal components and Httpd. I would be very beneficial for the users/admins to have the ability to use their own, pre-issued certificates or have the possibility to request the issuance of lets-encrypt Certificates.

**Comment by provencio** [comment]
I myself went through the instructions at https://gluu.org/docs/ce/admin-guide/certificate/#updating-apache-certificate (which are not literally valid as they refer to a number of incorrect paths, etc.) and after that I can no longer log in.  A variety of functions work but attempts to log into to the control panel result in " Oops.  Something wrong happened."  If you could just specify valid certificates as part of the install my guess is life would be a lot easier.

**Comment by mbaser** [comment]
@ganesh-at-wiw what do you think?

**Comment by ganesh-at-wiw** [comment]
It's really easy to use letsencrypt certs or other third party ssl certs after the installation finishes. Later on we may update the setup script to ask for cert and key files to support third party certs on the spot.
