### ISSUE TITLE
Hardening setup and configuration

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#608]
These changes from `https://support.gluu.org/other/7647/security-hardening-instructions/#at53606` we can apply from setup:
4.1, 4.2.2 - 4.2.4, 4.2.8 Mustafa Baser, 4.3.1-4.3.2 Mustafa Baser

**Comment by mbaser** [comment]
Note for documentation:

if encrypted setup.ptoperties file is used, setup.py should be run with argument `-properties-password`, for example:
```
./setup.py -properties-password=TopSecret
```

**Comment by mbaser** [comment]
When I put supplied apache2.conf apache behaves inappropriately (4.2.1)
![Screenshot_2019-11-13_18-14-47](https://user-images.githubusercontent.com/6398752/68842467-7b9f6380-06d7-11ea-89a9-e559bfb3fe23.png)

Thus, I am not implementing 4.2.1

**Comment by mbaser** [comment]
Implemented by commits:

667f04d720d329a6e76f2c71b4553fa05fb126b5
3095850c83442c1e35e6cd6bc360c3447439f122
b9cd6c865c6fe1c56a83165da29a31e326ce34ae
6f081c675edf12fb8a7a422a725e813b471360cc
