### ISSUE TITLE
Hardening LDAP

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#610]
A few changes to the default installation to improve security of LDAP.

**Comment by mbaser** [comment]
We currently have the following settings
4.4.1
4.4.2
4.4.3
4.4.4

**Comment by mbaser** [comment]
I am still unsure about 4.4.5-4.4.8. I don't know if using another user than `cn=directory manager` helps us strengthening ldap security. This most probably will cause upgrade issues.

**Comment by nynymike** [comment]
Don't use a named user. This changes the behavior of the search results--i.e. named uses have constraints applied. The `cn=directory manager` user is the only user who has access to the system--this is not a open LDAP server--it should be network restricted to only talk to Gluu components (i.e. oxAuth, oxTrust). Also, triggering access controls has performance implications (each ACI triggers a search for evaluation). This idea was considered and rejected years ago.

**Comment by mbaser** [comment]
Closing this issue, since there is nothing to implement.
