### ISSUE TITLE
Preisntall memcached int ochroot

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#613]
We need to preinstall memcached to avoid such message:
```
You may need the following packages
memcached
```

**Comment by mbaser** [comment]
@yurem It used to be pre-installed, later we removed, and then decided it to be optional.

**Comment by yurem** [comment]
@mbaser maybe setup should not prompt about it unless admin specify option to install it?

**Comment by nikdavnik** [comment]
Closing as its optional

**Comment by mbaser** [comment]
> @mbaser maybe setup should not prompt about it unless admin specify option to install it?

We may remove this dependency, specifying `--install-memcached` has the same difficultly with
`apt-get install memcached`
