### ISSUE TITLE
attribDataTypes not defined in post-setup

### ISSUE THREAD

**Issue by pstabno** [GluuFederation/community-edition-setup#615]
Any attempt to install component after gluu instalation ends up with message: 

Traceback (most recent call last):
  File "./post-setup-add-components.py", line 44, in <module>
    attribDataTypes.startup('.')
NameError: name 'attribDataTypes' is not defined

Attempt was performed according to guide in documentation. Gluu server version: 3.1.6

**Comment by pstabno** [comment]
UPDATE: using version from before commit: 15777bb6f7eed9e60bc6d2ee15c33c3a08c8afce worked well.

**Comment by mbaser** [comment]
Closing, since it is working with latest script.
