### ISSUE TITLE
Automate enabling oxTrust API, Test Mode, UMA mode, Passport, SAML, Radius, and Casa

### ISSUE THREAD

**Issue by mogluu** [GluuFederation/community-edition-setup#616]
The target is to fully automate the gluu installation from CI pipeline. 
- Enable oxTrust API upon setup
- Enable Test Mode upon setup or if user disables this UMA mode for production should be used
- Enable backend scripts and passport if oxPassport is installed
- Enable Radius if Radius is installation
- Enable SAML if oxShibboleth is installed
- Enable Casa scripts if Casa is installed

We at the container team have supported these with installation.

For oxTrust API we have added this doc:
https://gluu.org/docs/de/4.0/operation/oxtrust-api/

**Comment by mbaser** [comment]
oxtrsut api is enabled by script https://raw.githubusercontent.com/GluuFederation/community-edition-setup/master/oxtrustapi_setup.py
The rest was implemented before.
