### ISSUE TITLE
Include npyscreen inside container

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/community-edition-setup#619]
TUI needs npyscreen. Please download  https://github.com/npcole/npyscreen/archive/master.zip as
`/opt/dist/app/npyscreen-master.zip`

**Comment by mbaser** [comment]
@nikdavnik @adrian-gluu Please include npyscreen in 4.2

**Comment by nikdavnik** [comment]
Added into ubuntu18 and centos7 chroots

**Comment by yurem** [comment]
Can we close this issue?

**Comment by adrian-gluu** [comment]
done with debian10 and rhel7, we can close this. zip is ready for next build.
