### ISSUE TITLE
Script for keys re-generation and validation of LDAP references to jks file key aliases

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/community-edition-setup#621]
We need script that perform key regeneration as described here:
https://github.com/GluuFederation/support-docs/blob/master/troubleshooting/oxAuth/oxAuth_key_regeneration.md

After keys are re-generated in jks file and updated in LDAP,  script must perform validation:
1. read `oxAuthConfWebKeys` json value from LDAP
2. open jks file
Check that json contains values that exists in jks. If no, list all non-existent keys with error message (print missed keys aliases)

**Comment by mbaser** [comment]
Closing for now up to an issue exists.
