### ISSUE TITLE
Attribute inum should not be editable by default 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#622]
We need to update the ldif for the inum attribute so it is not editable by the admin. 

See also https://github.com/GluuFederation/oxTrust/issues/1884

**Comment by mbaser** [comment]
Making an attribute `NO-USER-MODIFICATION` does not make it readonly on oxtrust ui
```
attributeTypes: ( 1.3.6.1.4.1.48710.1.3.117 NAME 'inum'
  DESC 'XRI i-number'
  EQUALITY caseIgnoreMatch
  SUBSTR caseIgnoreSubstringsMatch
  SYNTAX 1.3.6.1.4.1.1466.115.121.1.15
  NO-USER-MODIFICATION USAGE directoryOperation
  X-ORIGIN 'Gluu created attribute' )
```

**Comment by nynymike** [comment]
Not in the LDAP schema.... there is an entry under `ou=attributes,o=org-inum,o=gluu` which has the gluu metadata for each attribute.
