### ISSUE TITLE
Use oxauth-client-jar-with-dependencies for key generation/re-generation during setup

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/community-edition-setup#623]
Right now we maintain classpath for `KeyGenerator` manually which is error prone approach especially between CE versions. Maven already maintains all dependencies and allows to compile jar with dependencies. Idea is to use jar with dependencies. Jar with dependencies is already generated by jenkins we need to add it to package and use by setup script:

For this we need:
1) Place file https://ox.gluu.org/maven/org/gluu/oxauth-client/4.2.0-SNAPSHOT/oxauth-client-4.2.0-SNAPSHOT-jar-with-dependencies.jar as /opt/dist/gluu/oxauth-client-jar-with-dependencies.jar` (@nikdavnik )
2) Modify setup.py to use `/opt/dist/gluu/oxauth-client-jar-with-dependencies.jar` for keys creation (@mbaser )

**Comment by mbaser** [comment]
Reopening for @nikdavnik

**Comment by nikdavnik** [comment]
Implemented in 4.2.0 packages
