### ISSUE TITLE
Allow 'systemctl' for other OS which support it for services in upgrade script

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#624]
@mbaser : Do you think it's possible to allow 'systemctl' for service startup in upgrade script? 
As for example, [here](https://github.com/GluuFederation/community-edition-package/blob/master/update/3.1.7/update.py#L542), opendj is using 'init' for all systems other than Redhat 7. However... CentOS7 and Ubuntu 18 ( not sure about it ) support systemctl by default. 

May be we can use 'systemctl' for those systems which using it already?

**Comment by mbaser** [comment]
@ganesh-at-wiw Will it work? For example we use `/etc/init.d/opendj start` in 3.1.3 If I put systemctl script on this system, will it work?

**Comment by ganesh-at-wiw** [comment]
Hello guys,
In Ubuntu 18 and CentOS 7,8 only are these commands supported inside chroot container.
Not possible in Xenial and others.

**Comment by mbaser** [comment]
Implemented in commit https://github.com/GluuFederation/community-edition-package/commit/e6a7401258ed8d636605fa1174287faaa9ca05a0
