### ISSUE TITLE
Change default apache error pages?

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/community-edition-setup#625]
This is related to https://github.com/GluuFederation/oxAuth/issues/1192

We might also hide the details about the apache server in use...

If we decide to do so, some prominent pages are 502 and 503...

![503](https://user-images.githubusercontent.com/5444180/71583844-24feb500-2ade-11ea-8826-d808514c251b.png)

**Comment by mbaser** [comment]
Fixed by commit https://github.com/GluuFederation/community-edition-setup/commit/dd438f6a698da9290c44f579e570d76a1fa92dba

![Screenshot_2019-12-31_14-33-20](https://user-images.githubusercontent.com/6398752/71628030-efa1b680-2c06-11ea-9477-f083ac272603.png)
