### ISSUE TITLE
Update debugger script to reflex Gluu 4.0 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#627]
['Enable Debugger'](https://gluu.org/docs/ce/developer-guide/script-debugging/) script is looking for `ox-ldap.properties` configuration file as requirement but in 4.0 there is no `ox-ldap.properties` file, which is breaking the installation of `tools-install.sh` script. 

Gluu 4.0 ldap property file name is `gluu-ldap.properties` which should be updated in `install.py` ( generated by `tools-install.sh` script ). 

Ref. ticket: https://support.gluu.org/customization/7808/script-debugging-does-not-work-on-gluu-40/#at55177

**Comment by mbaser** [comment]
Fixed version is available at http://c1.gluu.org:8999/tools-intall.sh
 @mzico please close this issue after checking if new version is working.

**Comment by mzico** [comment]
@mbaser : working, thanks. Closing issue.

**Comment by yurem** [comment]
@mbaser Installation works well. I've opened separate issue to update tools which we uses in this package to more recent versions: https://github.com/GluuFederation/community-edition-setup/issues/628
