### ISSUE TITLE
Adjust casa installer/uninstaller to write config to database

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/community-edition-setup#631]
Starting with 4.2, there will be no casa.json file but configurations will be moved to the underlying database. Let's use something like

```
dn: ou=casa,ou=configuration,o=gluu
objectClass: top
objectClass: oxApplicationConfiguration
ou: casa
oxConfApplication: < ... contents of casa.json ... >
```

Please ajust installation/uninstallation stuff.

Related https://github.com/GluuFederation/casa/issues/88

**Comment by mbaser** [comment]
Impelemented in commit https://github.com/GluuFederation/community-edition-setup/commit/776f9aa0fdecec991e821e7ce520ffb1bda211c4
