### ISSUE TITLE
Generate separate log for post-setup-add-components script

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#632]
It will be easier to troubleshoot any post-installation issue if we have separate log for 'post-setup-add-components.py'

**Comment by mbaser** [comment]
Implemented:
https://github.com/GluuFederation/community-edition-setup/commit/21452285d83c2a62df9da17bab3069cd290b96a1
https://github.com/GluuFederation/community-edition-setup/commit/af906a890e196deb243d8b711f72c840dab60e8f
https://github.com/GluuFederation/community-edition-setup/commit/fdcb4317f7722198396e7907eca3a715e1defc48
