### ISSUE TITLE
Upgraded 3.1.6.sp1 can't perform post-installation for shibboleth

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#633]
I am trying to post installation Shibb and Passport in a 3.1.6.sp1 server which was upgraded from 3.1.2 to 3.1.6 and then 3.1.6.sp1.  Seems like Shibboleth configuration is not happening. 

Here are some points below: 

- `/opt/gluu/jetty/idp/` directory is empty: 
  ```
  [root@cl316test ~]# cd /opt/gluu/jetty/idp/
  [root@cl316test idp]# ls
  webapps
  [root@cl316test idp]#
  ```
- `webapps` is a file, not directory: 
  ```
  [root@cl316test idp]# cd webapps
  -bash: cd: webapps: Not a directory
  [root@cl316test idp]#
  ```
- Ownership of `/var/run/jetty` is wrong. 
 ```
 [root@cl316test run]# ll
 total 28
 .....
 ....
 -rw-r--r--.  1 jetty root      4 Jan 22 19:03 identity.pid
drwxr-xr-x.  2 root  root     40 Jan 22 19:03 jetty
drwxr-xr-x.  5 root  root    120 Jan 22 19:03 lock
drwxr-xr-x.  2 root  root     40 Jan 22 19:03 log
drwxr-xr-x.  2 root  root     60 Jan 22 19:03 mount
....
....
[root@cl316test run]#

 ```
- Finally, post-installation log: attached
[post_setup.log](https://github.com/GluuFederation/community-edition-setup/files/4099476/post_setup.log)
[post_setup_error.log](https://github.com/GluuFederation/community-edition-setup/files/4099477/post_setup_error.log)

**Comment by mbaser** [comment]
This issue will be closed after test on a server upgraded to 4.1
