### ISSUE TITLE
Ship Gluu Server with version printing script under /opt/gluu/bin/

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/community-edition-setup#635]
As suggested by customer in ticket 7916, now when we don't mirror package's version in chroot container's name, importance of `printVersion.py` script becomes more significant. It should be easier to find. Currently it's located at `/install/community-edition-setup/pylib/printVersion.py`, but I think a more natural its location would be `/opt/gluu/bin/printVersion.py`. We should relocate it, if possible.

**Comment by aliaksander-samuseu** [comment]
@mbaser 
I've also noted the script doesn't print the version of the base package itself, only versions of the core components. If possible, we should detect the base version as well.

**Comment by mbaser** [comment]
@aliaksander-samuseu can you clear me what you mean by **base version**?

**Comment by mbaser** [comment]
The script is copied as `/opt/gluu/bin/show_version.py`

And there is no way to determine package information inside container.

**Comment by mtgluu** [comment]
^Then can you put in the README or somewhere what versions of oxtrust/auth/etc are relate to the gluu version installed?

**Comment by nynymike** [comment]
It would be cool if we could add this to the startup script, so you could do something like 

```
# service gluu-server version

```

**Comment by mbaser** [comment]
It is already under `/opt/gluu/bin/` with name `show_version.py`

**Comment by mbaser** [comment]
@ganesh-at-wiw is this possible?

> It would be cool if we could add this to the startup script, so you could do something like
> 
> ```
> # service gluu-server version
> ```

**Comment by ganesh-at-wiw** [comment]
show_version() {
                /usr/sbin/chroot /opt/gluu-server su - root -c '/opt/gluu/bin/show_version.py'
}

        version)
                show_version
        ;;

        echo "Usage:  {start|stop|status|restart|login|ready|clear-logs|version}"

**Comment by adrian-gluu** [comment]
@ganesh-at-wiw just pushed into:
https://github.com/GluuFederation/community-edition-package/blob/version_4.1.1/package/systemd/gluu-serverd

**Comment by mbaser** [comment]
All implemented, closing
