### ISSUE TITLE
re-generate oxd ssl certificate for hostname

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/community-edition-setup#637]
casa won't start properly if CN of oxd certificate does not match hostname.  Default CN of oxd ssl certifiacte is `localhost`, we need to regenerate.

And we need to set `trust_all_certs: true` in oxd config.

**Comment by mbaser** [comment]
Developers did not see this issue relevant. Closing.

**Comment by yuriyz** [comment]
oxd is using : 

1. for incoming https calls. 
```
- type: https
      port: 8443
      keyStorePath: /opt/oxd-server/conf/oxd-server.keystore
      keyStorePassword: example
      validateCerts: true
```
It means that we should have keystore generated with valid certs in it

2. for outgoing https calls to AS/oxauth which is used to validate http traffic between oxd and AS.
```
trust_all_certs: false
trust_store_path: /opt/oxd-server/conf/oxd-op.keystore
trust_store_pass: secret
```

`trust_all_certs: true` switches off validation, so we should have it `false` and use valid certs to validate connection.

**Comment by mbaser** [comment]
So, in case of remote use, we need

* either valid certificate imported to `/opt/oxd-server/conf/oxd-server.keystore`
* or self signed certificate whose CN matches hostname

setup.py can ask if oxd server will be used for remote use and generate oxd-server.keystore that has CN matches hostname

setup.py can also create a small script that will be shipped to remote oxd and imports httpd certs to `/opt/oxd-server/conf/oxd-op.keystore` or Java truststore

**Comment by mbaser** [comment]
We need to run `setup.py` with argument `--generate-oxd-certificate` to re-generate `oxd-server.keystore` depending on hostname as follows:

```
./setup.py --generate-oxd-certificate
```

**Comment by mbaser** [comment]
Since, setup.py always creates oxd certifiacte, argument `--generate-oxd-certificate` is removed in commit https://github.com/GluuFederation/community-edition-setup/commit/23dee4d5219802e4728aac96a8c14c5e452f115f
