### ISSUE TITLE
Use defaults for properties missing in setup.properties

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#639]
If setup.properties is missing any values, populate with default values or generate missing values (for example keystore password).

**Comment by mbaser** [comment]
There is an issue for removing dependence on setup.properties, I worked some but could not figured out completely:

https://github.com/GluuFederation/community-edition-package/issues/31

The idea is to use backend (ldap/couchbase) and other files to re-create setup.properties.

**Comment by mbaser** [comment]
We have `check_properties()` that initializes missing variables.
@nynymike Which missing variables are not initialized you observed?

**Comment by mbaser** [comment]
Since `check_properties()`  does the work, closing the issue
