### ISSUE TITLE
Improve key_regeneration.py

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/community-edition-setup#641]
We should improve `key_regeneration.py` and recommend to use it instead of performing manual step. It should exclude human factor (typo, mistake) as well as give more information what is going on during re-generation.

1. Extend configuration
- `expiration` -> in days
- `expiration_hours` -> hours

2. Add logging which should help to understand when it was run and how many times. We should log:

- generation configuration
- old keys and new keys
- catch all error during re-generation and log them.

3. backporting

I've scheduled this improvement for 4.2 but our goal is to support all versions for which we got support tickets. If it doesn't mean huge effort of course. 4.0, 4.1 and 4.2 is must as for me. 3.1.6 and later is nice to have.

@mzico @aliaksander-samuseu can you say for which versions currently we got most of the support tickets related to key re-generation ?

**Comment by mzico** [comment]
@yuriyz : looks good to me. One opinion: 

 - As we are running script, may be script can 'backup' old key ( jks + json ) and ldif section as well. 

>> can you say for which versions currently we got most of the support tickets related to key re-generation ?

3.6, 3.7 and 4.0.

**Comment by mbaser** [comment]
Implemented. Closing for now.
