### ISSUE TITLE
Remove Dependence on setup.properties.last

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/community-edition-setup#643]
Currently we use `setup.properties.last` as one of our sources of truth regarding the state and configuration of the current Gluu Server for upgrade purposes. This however will not always be true as information in the LDAP can be changed, such as hostname. There's also the possiblity that `setup.properties.last` will no longer exist on the server in question. 

For that reason it would be best to gather the current state information from the configuration files and LDAP directory, and no longer have dependences on `setup.properties.last`.

**Comment by mbaser** [comment]
Draft script https://github.com/GluuFederation/community-edition-setup/blob/master/static/scripts/generate_ldap_properties.py
