### ISSUE TITLE
Shibb post install keeping 'configGeneration' false in 3.1.6.SP1

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#646]
Used post install script to install shibboleth in 3.1.6.sp1: 

'configGeneration' should be 'true'; otherwise no Trust Relationship will 'generate' and configure new configuration in Gluu Server. Screenshot attached. 
![Capture](https://user-images.githubusercontent.com/7156097/75264441-069ef800-57b5-11ea-8d32-d141c41d2f75.PNG)

**Comment by mbaser** [comment]
Implemented in
https://github.com/GluuFederation/community-edition-setup/commit/148b0c7587bada3758deeaec70a5ff058f403665

https://github.com/GluuFederation/community-edition-setup/commit/a30e35905fd0578599164efaf5bfdead2c5de71d
