### ISSUE TITLE
Make SCIM a separate component of CE

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/community-edition-setup#651]
See https://github.com/GluuFederation/oxTrust/issues/1930

setup.py should add to prompts if "SCIM API service" should be installed.

If so, a new jetty instance has to be setup (/opt/gluu/jetty/scim-server). The corresponding war will be `/opt/dist/gluu/scim-server.war`

This component might also be added after installation (post-setup-add-components.py)

**Comment by mbaser** [comment]
@nikdavnik Please include `/opt/dist/gluu/scim-server.war`

**Comment by mbaser** [comment]
@jgomer2001 what will be port? Shall I chose next available port?

**Comment by jgomer2001** [comment]
@mbaser yes

**Comment by nikdavnik** [comment]
@jgomer2001 please post here url from where I can download scim-server.war

**Comment by jgomer2001** [comment]
@nikdavnik it will take time to have the url ready, I will update this issue as soon as it becomes available

**Comment by jgomer2001** [comment]
@nikdavnik war is here https://ox.gluu.org/maven/org/gluu/scim-server/4.2.0-SNAPSHOT/

**Comment by mbaser** [comment]
@jgomer2001 Could you add scim entry here?
https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L303-L335

**Comment by mbaser** [comment]
@nikdavnik 
1. setup.py will seek file `/opt/dist/gluu/scim.war` for installtion
1. we need unit file for systemd. Please include `/usr/lib/systemd/system/scim.service` (included in attachment)
[scim.service.zip](https://github.com/GluuFederation/community-edition-setup/files/4503357/scim.service.zip)

**Comment by nikdavnik** [comment]
Added in Ubuntu18, centos7, debian9 for now

**Comment by adrian-gluu** [comment]
added rhel7 and debian10

**Comment by mbaser** [comment]
@adrian-gluu `gluu-server-4.2.0-361.centos7.x86_64.rpm` does not contain scim.war

**Comment by nikdavnik** [comment]
fixed centos7 package, next build should contain it

**Comment by adrian-gluu** [comment]
all the pkgs:
Ubuntu18 Centos7 rhel7 and debian9/10 has /opt/dist/gluu/scim.war and /usr/lib/systemd/system/scim.service
