### ISSUE TITLE
3.1.7 post setup script not available

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#654]
post-setup-add-components.py is not available for 3.1.7 which is included here in [doc](https://www.gluu.org/docs/ce/3.1.7/operation/faq/#adding-passportjs-andor-shibboleth-idp-post-installation)

```
[root@clupgrade community-edition-setup]# # wget -c https://raw.githubusercontent.com/GluuFederation/community-edition-setup/version_3.1.7/post-setup-add-components.py
[root@clupgrade community-edition-setup]# ls
ldif.py             output          README.md         setup_error.log        setup.properties.sample  templates
LICENSE             Properties.py   requirements.txt  setup.log              setup.py                 tests
openldap_migration  Properties.pyc  schema            setup.properties.last  static
[root@clupgrade community-edition-setup]#
```

**Comment by mbaser** [comment]
@mzico it is available, the dash character (`#`) at the beginning, means it should be run as root, but if you copy the text as is, then dash character at the beginning will be considered as comment by shell and nothing is done for that command, so you need to run:

`wget https://raw.githubusercontent.com/GluuFederation/community-edition-setup/version_3.1.7/post-setup-add-components.py`

(without dash at the beginnig)
