### ISSUE TITLE
Replace facter with python psutil based script

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/community-edition-setup#657]
As facter version changes, it's output differs. We can replace facter with a python script based on psutil module as attached.
[facter.py.zip](https://github.com/GluuFederation/community-edition-setup/files/4452371/facter.py.zip)

The script also avoid running `df` command

@nikdavnik please include psutil in chroot. you can install as

`pip3 install psutil`

Don't include OS release of psutil since they are too old

**Comment by adrian-gluu** [comment]
installed the pkgs from apt in debian10 and pkg-deb3 but i need ganesh to fix my ssh key for the rest of the build VMs

**Comment by mbaser** [comment]
> installed the pkgs from apt in debian10 and pkg-deb3 but i need ganesh to fix my ssh key for the rest of the build VMs

Don't install from apt use `pip3 install psutil`

**Comment by nikdavnik** [comment]
install on ubuntu18 and centos7 with pip3 install psutil

**Comment by mbaser** [comment]
Gasymr modified oxtrust to use my implementation of facter. So for the next release please remove facter package (and related packages) and include this one

wget https://raw.githubusercontent.com/GluuFederation/gluu-snap/master/facter/facter -O /usr/bin/facter
chmod +x /usr/bin/facter
OR if you wish, i can include it in community-edition-setup, and copy via setup.py

**Comment by mbaser** [comment]
@nikdavnik `facter` does not use psutils anymore, so please also remove psutils package form container

**Comment by nikdavnik** [comment]
psutils is removed from containers and factor is installed. We can close this ticket
