### ISSUE TITLE
Remove dependence on python-ldap

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/community-edition-setup#661]
Some Linux distributions does not include python-ldap, we need to remove dependency on python-ldap

**Comment by mbaser** [comment]
We need to remove this dependency from all scripts that uses python-ldap

**Comment by nynymike** [comment]
What do you propose as a replacement?

**Comment by mbaser** [comment]
> What do you propose as a replacement?
@nynymike 
Some recent Linux Distros don't have python-ldap package, python-ldap uses symas ldap libraries. I tried to compile one but unable since it has lots of dependency those does not exists on the distro. For example CentOS 8 even don't have slapd package, (Redhat permanently removed symas ldap)

**Comment by mbaser** [comment]
As a replacement, I used ldif3 package and python3-ldap3

**Comment by mbaser** [comment]
All scripts in use moved to python3 and ldap3
