### ISSUE TITLE
update oxd configuration

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/community-edition-setup#667]
Update oxd configuration as described in:
https://github.com/GluuFederation/oxd/issues/477#issuecomment-622422515

**Comment by mbaser** [comment]
@nikdavnik please include python3 ruamel.yaml in 4.2 containers. Packages:

CentOS, RedHat: `python3-ruamel-yaml`
Ubuntu, Debian: `python3-ruamel.yaml`

**Comment by adrian-gluu** [comment]
@nikdavnik just done with Centos,Ubuntu and Debian.
Just RHEL is missing because the pkg dependency setuptools is not on EPEL

**Comment by adrian-gluu** [comment]
done, just sorted RHEL
