### ISSUE TITLE
Remove python2 from 4.2 containers

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/community-edition-setup#671]
Since community-edition-setup was moved to python3, we can remove python2 from containers.
We can't remove python2 from RHEL/CentOS 7 since yum depends on python2

**Comment by adrian-gluu** [comment]
at the moment only Ub18 has a chroot for 4.0, I've just removed python2 from that container as you requested not touch RHEL 7 and Centos 7

**Comment by nikdavnik** [comment]
I tried to remove python2 from rhel7 and centos7 containers but seems yum package manager is using it so we cannot remove it, otherwise it will break yum.

**Comment by mbaser** [comment]
@nikdavnik I explained this in the issue message. CentOS7/RHEL7 should live with Python 2.

**Comment by nikdavnik** [comment]
ok @mbaser , removed from Debian9
Will close the ticket
