### ISSUE TITLE
Make casa installation use hostname (not localhost) for oxd configuration

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/community-edition-setup#676]
It seems oxd certificate does not use `localhost` as CN but the hostname now (eg. `my.gluu.co`)

In a default casa installation, let's make casa json configuration conform to that, example:
```
{
...
 "oxd_config" : {"host": "my.gluu.co",  "port": 8443
```

This applies for the case in which no oxd server was provided at installation time

**Comment by jgomer2001** [comment]
another question that comes up is if this has effects  in cluster manager.

**Comment by mbaser** [comment]
> another question that comes up is if this has effects in cluster manager.

I don't think, each node will use it's own oxd

**Comment by mbaser** [comment]
Implemented in commit https://github.com/GluuFederation/community-edition-setup/commit/e294184f0a743dfb2fd5a80e0d2c48a6dca42226
