### ISSUE TITLE
Xmx and metaspace too low 

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/community-edition-setup#682]
Using scim and fido2 as components in 4.2, I got the following in `/etc/default/scim` and also in fido2 file:

`JAVA_OPTIONS="-server -Xms179m -Xmx179m -XX:MaxMetaspaceSize=77m `

(this was using a 5GB of RAM)

`-Xmx` and `-XX:MaxMetaspaceSize` are not appropriate. If this is not an error in setup code, you can ping @yurem for advice. I think both values can be increased by 300MB

**Comment by mbaser** [comment]
`MaxMetaspaceSize` is calculated here:
https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L4281

@yurem can you guide me how to calculate?

**Comment by yurem** [comment]
I think we need to do:

1) Define new key/value in jetty_app_configuration to specify metaspace size

2) In memory calcluation method clculate applicationMemory = applicationMemory - applicationMetaspacMemory before cacluclating s_max_heap_mem

3) If max_heap_mem less than 256Mb show user warning that it’s not enough to run application proprly but allow to install CE

4) Use either JProfiler/YourKit/VisualVM to get metaspace size of running application plus add to this value small overhead - 25%

**Comment by mbaser** [comment]
Implemented in https://github.com/GluuFederation/community-edition-setup/commit/73a95c3ec6be7113e4eaa3c03b6d20f588d1ec2f
