### ISSUE TITLE
Offer uninstallation of components?

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/community-edition-setup#684]
CE has a good number of components: fido2, casa, scim, etc, etc... should we offer means to "remove" components post-install if admins don't want to use  some of them more?

**Comment by mbaser** [comment]
@yuriyz @yurem What do you think? I can implement in refactored version.

**Comment by yuriyz** [comment]
At first admin may not want to use some component. Lets say he/she removed it. What if admin changed his/her mind and want to use it again? I guess we should be careful here. Also we have dependencies between components. E.g. admin may think that he wants casa but doesn't want oxd. It doesn't look strightforward.

**Comment by nynymike** [comment]
I don't think this is necessary. Disk space is cheap. If the services are not running, the impact is minimal. And at a high level, I see Gluu moving towards K8, where services are running in containers anyway. So this is really just an issue for CE. I don't think the benefit of this feature has a positive impact on enough customers to justify the time.

**Comment by jgomer2001** [comment]
Fair, closing...
