### ISSUE TITLE
No module named 'pylib.dbutils' in post-setup-add-components

### ISSUE THREAD

**Issue by coltonmccormack** [GluuFederation/community-edition-setup#691]
I am in the process of upgrading our Gluu Server version 3.1.2 to 4.1 and things have gone well so far, except I now want to add Passport.js to the install. I am on Ubuntu 16.04 and currently unable to upgrade to a later Ubuntu version due to other production service dependencies. Python3 version is 3.5.2.

When running post-setup-add-components.py I am constantly getting 

> Traceback (most recent call last):
  File "post-setup-add-components.py", line 11, in <module>
    from pylib.dbutils import get_ldap_conn, get_cbm_conn
ImportError: No module named pylib.dbutils

I had a similar error for ldap3 but was able to fix it by installing the ldap3 package. However, I have been unable to bypass the above error by installing either the pylib or dbutils packages.

How do I solve this dependency issue?

**Comment by thatguyyoulove** [comment]
Upon further investigation it looks like these are local files that are present in the master branch community-edition-setup but not my server (which was provisioned this morning). I suspect somewhere in the upgrade from 3.1.2 to 4.0 the scripts aren't getting updated and/or the [4.1 documentation](https://gluu.org/docs/gluu-server/4.1/authn-guide/passport/) shouldn't reference the master branch version of the script?

**Comment by thatguyyoulove** [comment]
Looks like some changes have been made since I created this issue in 04a354487f2af3c578db4c2725c84cd17cae8597. Can anyone confirm that this addresses the import error? I found a workaround for installing Passport during my upgrade process that doesn't utilize post-setup-add-components.

**Comment by devrimyatar** [comment]
Can't reproduce
