### ISSUE TITLE
option to not use google fonts / host all webapp resources locally on gluu server

### ISSUE THREAD

**Issue by znerol2** [GluuFederation/community-edition-setup#697]
Hi there,

I'm testing gluu and I found that some webapp resources depend on external sites specifically fonts from googleapis. Is there an uncomplicated way to host all font resources locally on gluu server? or need to edit out all occurances manually?

in our case not all user browsers are able to access google due to regional internet censorship

Kind regards,
Lorenz

**Comment by mzico** [comment]
Hey @znerol2 

For support related questions.. please use our support portal: https://support.gluu.org
