### ISSUE TITLE
server fails to start on CentOS 7.1

### ISSUE THREAD

**Issue by jimscarver** [GluuFederation/community-edition-setup#70]
We installed 2.3.5-2.el6 following http://www.gluu.org/docs/admin-guide/deployment/centos/ on CentOS Linux release 7.1.1503 (Core) on DigitalOcean

It installs without issue but service gluu-server start it says it is started but is not.  The package did start fine on CentOS 6.5 but we had certificate issues there.

[root@ce etc]# service gluu-server start
Starting gluu-server (via systemctl):                      [  OK  ]
[root@ce etc]# service gluu-server login
gluu-server is not running
please start it and run /etc/init.d/gluu-server start

If we try to start it again we get the same result.  This looks like a bug.

We do find the chroot file systems mounted as follows

devtmpfs on /opt/gluu-server/dev type devtmpfs (rw,nosuid,size=1019784k,nr_inodes=254946,mode=755)
/proc on /opt/gluu-server/proc type proc (rw,noatime)
/sys/class/net/lo on /opt/gluu-server/sys/class/net/lo type sysfs (rw,relatime)
/dev/vda1 on /opt/gluu-server/lib/modules type ext4 (rw,relatime,data=ordered)
/dev/pts on /opt/gluu-server/dev/pts type devpts (rw,relatime,gid=5,mode=062,ptmxmode=000)
none on /opt/gluu-server/proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)

I could not find any entries in system or gluu-server logs.

Any suggestion will be welcome.

**Comment by nynymike** [comment]
You'll need to move this issue to https://support.gluu.org  It is not a bug on community-edition-setup

**Comment by jimscarver** [comment]
I see the issue is in https://support.gluu.org/view/installation/problem-installing-and-running-gluu-server-on-centos-7/2167

That is a bug in the community-edition-setup as far as I can see.  How is that not a bug that should be addressed by an open issue here?

**Comment by willow9886** [comment]
It's not a bug, CentOS 7 is just not yet supported. We're working on it and hope to have it supported by end of year.
