### ISSUE TITLE
Need Sample Post Authentication Script

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#700]
There is a new script called "Post Authentication"... we need a sample script here showing at least the interface, and some small piece of functionality (like how to access the existing session).

**Comment by yuriyz** [comment]
Sample script can be found here: 
https://github.com/GluuFederation/community-edition-setup/blob/master/static/extension/post_authn/post_authn.py

Session object can be taken as `context.getSession()`. There is notes to each method which hopefully should make script easy to use.
