### ISSUE TITLE
CB: Store sessions in new bucket `gluu_session`

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#707]
In 4.2.1 we store session as session entries. In 4.1.x we stored them as cache entries.

As result count of operations with `ou=sessions` is more than operations with other branches. To not affect performance we decided to add independent bucket.

We need to do:
1. Add `gluu_session` bucket
2. Move session indexes to this new bucket. In [4.2.1](https://github.com/GluuFederation/community-edition-setup/blob/version_4.2.1/static/couchbase/index.json#L80) lines 80 (["oxAuthUserDN"]) and 83 ([["exp"], "objectClass = \"oxAuthSessionId\""]).
3. Split the space allocated for CB in next ratio:
gluu_cache : gluu_session : gluu_token
1 : 6 : 4

With memory 20 GB for these 3 buckets it will be
2Gb : 12Gb : 8Gb

**Comment by mbaser** [comment]
implemented in commit 1d1b12b9311b36dfc75f27689a64cd211b551dea
