### ISSUE TITLE
"Timezone" setting for setup.py

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/community-edition-setup#71]
I had a minor issue with 2.3.4 rpm before. Timezone was set incorrectly inside the Gluu's container right after setup.py script finished its execution, but it was correctly set inside the host OS (outside of the container). Mb setup.py should ask a user about it during setup phase? It also could propose default value, the same as set for the host OS, in case it can't be correctly derived from the locality settings provided to the script on the previous steps (like, if user just typed in some arbitrary letters to the Country/City fields), or  derived from the locality settings he already has provides anyway (when he asked for settings needed to issue a self-signed certificate)

**Comment by adrian-gluu** [comment]
to set the timezone try service gluu-server login and after that inside of the container:
ln -s /usr/share/zoneinfo/xxxx   /etc/localtime

where XXXX is your timezone or try this command tzselect

**Comment by aliaksander-samuseu** [comment]
@adrian-gluu 

It's not the issue, it would be more convenient though that it would be set automatically. Now we have the same request from our customer too: [link](https://support.gluu.org/installation/gluu-server-system-time-config-2686)

**Comment by ganesh-at-wiw** [comment]
Alex what do you think should we set the timezone to?
Is UTC/GMT fine or something else?

**Comment by aliaksander-samuseu** [comment]
@ganesh-at-wiw , I would say `setup.py` should grap timezone from the host OS and set tz in container to be the same. It also should display what timezone it set into container in its output at some point, just to inform the user.

**Comment by ganesh-at-wiw** [comment]
setup can't see outside the container i.e at host OS.
But if in future need be, we will need to change the init script a bit.
Closing the issue for now.

**Comment by ganesh-at-wiw** [comment]
setup can't see outside the container i.e at host OS.
But if in future need be, we will need to change the init script a bit.
Closing the issue for now.
