### ISSUE TITLE
Outdated Velocity templates for Shibboleth's configuration files are being deployed by setup.py

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/community-edition-setup#72]
I was discussing the issue with @yurem before, so will just relay his judgement of the situation.
It seems there are 2 sets of those templates in the current Gluu CE packages (2.4.x) at the moment. One outdated set deployed together with tomcat located at [this branch](http://gitlab.gluu.org/root/gluu-ce-rpm/tree/master/gluu-server24/opt/apache-tomcat-7.0.55/conf/shibboleth2/idp), and a current one which is part of oxTrust and located at [this branch](https://github.com/GluuFederation/oxTrust/tree/master/configuration/template/shibboleth2/idp)
It seems when following usual setup steps provided in our docs (using yum/apt, then running setup.py) your instance ends up with outdated set, so updated Shibboleth configuration is never being deployed.

**Comment by willow9886** [comment]
It's unclear if the solution is to remove these templates from CE setup or to dynamically download them from the authoritative source?

**Comment by yurem** [comment]
Now we install shib templates during setup. Setup extract them from [oxtrust-configuration.jar](https://ox.gluu.org/maven/org/xdi/oxtrust-configuration/2.4.2.Final/oxtrust-configuration-2.4.2.Final.jar) and put into tomca/conf/shibboleth2 folder
