### ISSUE TITLE
Improve setup.py messages during oxd installation

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/community-edition-setup#720]
Current message confuses some people:
`By default oxd uses its own db. Do you want to use Gluu Storage for Oxd?`
E.g. what is the own db and whether some additional installation is required.

One option is to change it to something like this:
`By default oxd is using h2 built-in database for persistence. Do you want to change persistence type? [No, Redis, LDAP, Couchbase]`

(It's not bug but still may be worth to correct to avoid confusion.)

Support: 8954

**Comment by mbaser** [comment]
As discussed in chat, the message is changed as follows:
```
oxd includes a built-in h2 database for persistence. Do you want to change it to the Authorization Server's native persistence mechanism (recommended for high load only)?
```
