### ISSUE TITLE
The jar file `bcpkix-jdk15on-1.54.jar` missing at `/opt/oxd-server/lib/` (inside Gluu Chroot)

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/community-edition-setup#723]
We have `/lib/bcpkix-jdk15on-1.54.jar`  in `oxd-4.2.1` distribution zip. 
https://ox.gluu.org/maven/org/gluu/oxd-server/4.2.1.Final/oxd-server-4.2.1.Final-distribution.zip

**Expected :**
 `Gluu server + oxd` 4.2.1 installation should have `bcpkix-jdk15on-1.54.jar` at `/opt/oxd-server/lib/` location.

**Actual:**

The jar file (`bcpkix-jdk15on-1.54.jar`) is missing at `/opt/oxd-server/lib/` location of `Gluu server + oxd` 4.2.1 installation.

**Comment by adrian-gluu** [comment]
@duttarnab checked all the fetch_sources scripts for all our platforms and all points to the same directions:
"cp /home/jenkins/oxd_files/bcprov-jdk15on-1.64.jar $DIRWEB/oxd-server/lib/"

**Comment by adrian-gluu** [comment]
fixed on branch 4.2.1, here is the fix:
```cp /home/jenkins/oxd_files/bcpkix-jdk15on-1.54.jar $DIRWEB/oxd-server/lib/```
