### ISSUE TITLE
Prevent Admin from Running Upgrade script twice

### ISSUE THREAD

**Issue by imShakil** [GluuFederation/community-edition-setup#724]
Upgrading script is able to run again even after completely upgraded to the latest version.
![Screenshot from 2020-11-02 23-34-42](https://user-images.githubusercontent.com/20867846/98022595-040a9d00-1e30-11eb-9e86-c1dd5aea7560.png)

**Comment by mbaser** [comment]
We can't do this. May be the upgrade was incomplete due to some reasons.
Running upgrade multiple times won't break anything.
