### ISSUE TITLE
Debian Buster uninstall prints incorrect message.

### ISSUE THREAD

**Issue by sschueller** [GluuFederation/community-edition-setup#727]
On uninstall using ```apt purge gluu-server``` the following will output:

```
Your changes will be saved into /opt/gluu-server.saved
```

However the correct path is ```/opt/gluu-server.save```

Gluu: 4.2.1~debian10
OS: Debian 10.7 (4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux)

**Comment by nikdavnik** [comment]
Fixed in github.
We will have this fixed in next package build, i.e in 4.2.3
