### ISSUE TITLE
Debian buster uninstall not complete

### ISSUE THREAD

**Issue by sschueller** [GluuFederation/community-edition-setup#728]
Uninstall on Debian buster fails to remove the machine container and will cause a new install to fail.

Steps to reproduce:

1. Install Gluu (per docs: https://gluu.org/docs/gluu-server/4.1/installation-guide/install-debian/ )
2. Uninstall per docs
3. Reinstall
4. ```/sbin/gluu-serverd start``` will fail because of:

```
systemd[1]: Starting Container gluu-server...
systemd-nspawn[27558]: Failed to register machine: Machine 'gluu-server' already exists
systemd-nspawn[27558]: Parent died too early
systemd[1]: systemd-nspawn@gluu-server.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: systemd-nspawn@gluu-server.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Container gluu-server.
```
```machinectl``` shows the machine "gluu-server" present

Manually removing the container via: ```rm /run/systemd/machines/gluu-server```

Removes it from ```machinectl``` however there is a new error when trying to start the service:

```
systemd[1]: Starting Container gluu-server...
systemd-nspawn[1440]: Failed to register machine: Unit machine-gluu\x2dserver.scope already exists.
systemd[1]: systemd-nspawn@gluu-server.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: systemd-nspawn@gluu-server.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Container gluu-server.
```

I was able to get around this with:

```
systemctl stop "machine-gluu\x2dserver.scope"
```

Gluu: 4.2.1~debian10
OS: Debian 10.7 (4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux)

**Comment by nikdavnik** [comment]
Could not reproduce this issue. 
reinstalled package few times, all goes ok.
@sschueller I think this issue occures because of some mess in your systems between older and never versions of packages existing in system. Also we dont have any /run/systemd/machines/gluu-server file, not sure how you get that. Please check on some fresh installed debian 10 machine. thanks.
