### ISSUE TITLE
TUI and UI installation of 4.3.0 show wrends while actually Installing opendj

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/community-edition-setup#738]
## Describe the issue 
TUI and UI installation of 4.3.0 show wrends while actually installing opendj.

## Expected Result 
Opendj keyword must be displayed instead of wrends.

## Actual Result
'Wrends' is showing instead of opendj.

## Environment
Ubuntu 20
Gluu Server 4.3.0

## Screenshot
TUI  | Terminal
------------- | -------------
![Screenshot from 2021-06-03 20-53-16](https://user-images.githubusercontent.com/34593983/120671478-0c52b580-c4af-11eb-9d66-4625f8001366.png)  | ![Screenshot from 2021-06-03 20-41-31](https://user-images.githubusercontent.com/34593983/120671483-0e1c7900-c4af-11eb-9f6f-a61b748df46b.png)

**Comment by mbaser** [comment]
fixed in commit https://github.com/GluuFederation/community-edition-setup/commit/1ec480ba6d331fd16d50f9b8005586f67ba4ae51
