### ISSUE TITLE
TUI installation of 4.3 show only maximum 94% in progress bar during installation.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/community-edition-setup#739]
## Describe the issue 
TUI installation of 4.3 show only maximum 94% in progress bar during installation.

## Expected Result 
TUI progress bar must show 100% installation .

## Actual Result
TUI progress only showing 94% installation.

## Environment
Ubuntu 20
Gluu Server 4.3.0

## Screenshot
![Screenshot from 2021-06-03 20-57-07](https://user-images.githubusercontent.com/34593983/120672402-e5e14a00-c4af-11eb-8c0f-8da5e9946c80.png)

**Comment by mbaser** [comment]
fixed in commit https://github.com/GluuFederation/community-edition-setup/commit/1ec480ba6d331fd16d50f9b8005586f67ba4ae51
