### ISSUE TITLE
Shibboleth Configuration

### ISSUE THREAD

**Issue by vishalvenkategowda** [GluuFederation/community-edition-setup#74]
I am not able to configure Shibboleth on my SP. I have installed both Apache and Shibboleth according to the instruction for windows machine. After the IIS setup when I try to open https://<my domain>/Shibboleth.sso/Status, I get a blank page. I am expecting an xml as per the instructions.

I have gluu-server24 installed on my server(Linux). Now I need to install Shibboleth on my client system(windows) so I can generate the metadata file and create a trusted relationship on GLUU server.

Could anyone please let me know the steps in detail? If there is a video instruction that would be great, but screenshot would be good too. Actually any help will be greatly appreciated.

**Comment by mzico** [comment]
There are documentations out there in Internet on how to configure Shibboleth SP.

**Comment by nynymike** [comment]
Also, this issue should have been listed on https://support.gluu.org--not on github. It is not a bug on community-edition-setup
