### ISSUE TITLE
Gluu Server 4.3.0 installation fail with couchbase version 6.6.2.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/community-edition-setup#741]
### Describe the issue 

Gluu-server 4.3.0 is not installing with couchbase 6.6.2v ubutnu 20.04

### How to Reproduce

1. Get the Couchbase-server 6.6.2 ubuntu20.04 package in /opt/dist/couchbase

2. try to install Gluu-server with Couchbase server

### Gluu-server must be installed with couchbase current version (6.6.2)

Actual behaviour 

### Envrionment

Gluu Server 4.3.0
Ubuntu 20.04

### Error logs
```FATAL: True
Traceback (most recent call last):
  File "./setup.py", line 289, in do_installation
    couchbaseInstaller.start_installation()
  File "/install/community-edition-setup/setup_app/installers/base.py", line 37, in start_installation
    self.install()
  File "/install/community-edition-setup/setup_app/installers/couchbase.py", line 60, in install
    self.create_couchbase_buckets()
  File "/install/community-edition-setup/setup_app/installers/couchbase.py", line 308, in create_couchbase_buckets
    couchbaseClusterRamsize = (system_info['storageTotals']['ram']['quotaTotal'] - system_info['storageTotals']['ram']['quotaUsed']) / (1024*1024)
KeyError: 'storageTotals' ```

**Comment by mbaser** [comment]
@MohitMaliFtechiz please test and close if fixed. Use this package:
couchbase-server-enterprise_6.6.2-ubuntu20.04_amd64.deb

**Comment by MohitMaliFtechiz** [comment]
hi @mbaser ,

New fix working but while selecting SAML during installation its fail during saml installation.

```
15:43:36 06/09/21 FATAL
15:43:36 06/09/21 Traceback (most recent call last):
  File "./setup.py", line 313, in do_installation
    samlInstaller.start_installation()
  File "/install/community-edition-setup/setup_app/installers/base.py", line 37, in start_installation
    self.install()
  File "/install/community-edition-setup/setup_app/installers/saml.py", line 126, in install
    self.saml_couchbase_settings()
  File "/install/community-edition-setup/setup_app/installers/saml.py", line 190, in saml_couchbase_settings
    Config.post_messages.append('{}Please create a user on Couchbase Server with the following credidentals and roles{}'.format(gluu_utils.colors.WARNING, gluu_utils.colors.ENDC))
NameError: name 'gluu_utils' is not defined
```

**Comment by MohitMaliFtechiz** [comment]
Hi @mbaser ,

Also i have seen lots of error in setuperror.log file related to certificate.

```
5:38:52 06/09/21 Certificate was added to keystore

15:41:54 06/09/21 ERROR: Module /etc/apache2/mods-enabled/autoindex does not exist!

15:41:54 06/09/21 ERROR: Module /etc/apache2/mods-enabled/negotiation.conf does not exist!

15:41:54 06/09/21 ERROR: Module /etc/apache2/mods-enabled/filter does not exist!

15:41:54 06/09/21 ERROR: Module /etc/apache2/mods-enabled/auth_basic does not exist!

15:41:54 06/09/21 ERROR: Module /etc/apache2/mods-enabled/negotiation does not exist!

15:41:54 06/09/21 ERROR: Module /etc/apache2/mods-enabled/status does not exist!

15:41:54 06/09/21 ERROR: Module /etc/apache2/mods-enabled/dir does not exist!

15:41:54 06/09/21 ERROR: Module /etc/apache2/mods-enabled/authn_file does not exist!

15:41:55 06/09/21 ERROR: Module /etc/apache2/mods-enabled/dir.conf does not exist!

15:41:55 06/09/21 ERROR: Module /etc/apache2/mods-enabled/deflate.conf does not exist!

15:41:55 06/09/21 ERROR: Module /etc/apache2/mods-enabled/status.conf does not exist!

15:41:55 06/09/21 ERROR: Module /etc/apache2/mods-enabled/mod_token_binding.conf does not exist!

15:41:55 06/09/21 ERROR: Module /etc/apache2/mods-enabled/authz_user does not exist!

15:41:55 06/09/21 ERROR: Module /etc/apache2/mods-enabled/autoindex.conf does not exist!

15:41:55 06/09/21 ERROR: Module /etc/apache2/mods-enabled/mod_token_binding does not exist!

15:41:55 06/09/21 ERROR: Module /etc/apache2/mods-enabled/deflate does not exist!

15:41:56 06/09/21 ERROR: Module security2 does not exist!

```

**Comment by mbaser** [comment]
Fixed

![Screenshot_2021-06-11_21-41-49](https://user-images.githubusercontent.com/6398752/121735068-4bf84d80-cafe-11eb-89fa-b22a8b405452.png)

**Comment by mbaser** [comment]
> Hi @mbaser ,
> 
> Also i have seen lots of error in setuperror.log file related to certificate.
> 
> ```
> 5:38:52 06/09/21 Certificate was added to keystore
> 
> 15:41:54 06/09/21 ERROR: Module /etc/apache2/mods-enabled/autoindex does not exist!
> 
> 15:41:54 06/09/21 ERROR: Module /etc/apache2/mods-enabled/negotiation.conf does not exist!
> 
> 15:41:54 06/09/21 ERROR: Module /etc/apache2/mods-enabled/filter does not exist!
> 
> 15:41:54 06/09/21 ERROR: Module /etc/apache2/mods-enabled/auth_basic does not exist!
> 
> 15:41:54 06/09/21 ERROR: Module /etc/apache2/mods-enabled/negotiation does not exist!
> 
> 15:41:54 06/09/21 ERROR: Module /etc/apache2/mods-enabled/status does not exist!
> 
> 15:41:54 06/09/21 ERROR: Module /etc/apache2/mods-enabled/dir does not exist!
> 
> 15:41:54 06/09/21 ERROR: Module /etc/apache2/mods-enabled/authn_file does not exist!
> 
> 15:41:55 06/09/21 ERROR: Module /etc/apache2/mods-enabled/dir.conf does not exist!
> 
> 15:41:55 06/09/21 ERROR: Module /etc/apache2/mods-enabled/deflate.conf does not exist!
> 
> 15:41:55 06/09/21 ERROR: Module /etc/apache2/mods-enabled/status.conf does not exist!
> 
> 15:41:55 06/09/21 ERROR: Module /etc/apache2/mods-enabled/mod_token_binding.conf does not exist!
> 
> 15:41:55 06/09/21 ERROR: Module /etc/apache2/mods-enabled/authz_user does not exist!
> 
> 15:41:55 06/09/21 ERROR: Module /etc/apache2/mods-enabled/autoindex.conf does not exist!
> 
> 15:41:55 06/09/21 ERROR: Module /etc/apache2/mods-enabled/mod_token_binding does not exist!
> 
> 15:41:55 06/09/21 ERROR: Module /etc/apache2/mods-enabled/deflate does not exist!
> 
> 15:41:56 06/09/21 ERROR: Module security2 does not exist!
> ```

These errors should be omitted by commit https://github.com/GluuFederation/community-edition-setup/commit/c97c398d72c6e9ee6eab5ddc4a9909e623593cae
