### ISSUE TITLE
UMA SCIM resource not created after install

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/community-edition-setup#744]
On a fresh install of 4.3 beta (I selected scim to be included) there is the below error in oauth logs

```
2021-06-28 08:58:17,059 ERROR [qtp2051853139-21] [org.gluu.oxauth.uma.service.UmaResourceService] 
(UmaResourceService.java:171) - Failed to find resource set with id: 1203.db9e918c-0b4c-4b4b-8d7b-7fa1611fbbba
```

In LDAP, under `ou=resources,ou=uma,o=gluu` there is only one entry corresponding to “oxTrust api Resource”

This is how it used to look in 4.2.3 (oxTrust view):
![Screenshot from 2021-06-28 08-02-52](https://user-images.githubusercontent.com/5444180/123650497-42563180-d7f0-11eb-8283-0ca17b4d2e17.png)

@mbaser I also noticed the associated uma script was disabled (`inum=2DAF-F9A5,ou=scripts,o=gluu`)

**Comment by mbaser** [comment]
Fixed

![Screenshot_2021-06-28_22-26-18](https://user-images.githubusercontent.com/6398752/123693507-d3fd8780-d860-11eb-9287-e8c0dcc9f6c9.png)
