### ISSUE TITLE
Setup.properties file false flag

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/community-edition-setup#75]
The setup.properties file when used to install Gluu CE shows false for Shibboleth IDP installation. The previous installation had Shibboleth IDP checked and installed.

**Comment by nynymike** [comment]
I just committed a [fix](https://github.com/GluuFederation/community-edition-setup/commit/3f2bec79a970c77c06218beb93fd51ebfcb8fd90) but it needs testing.

**Comment by zamilskhan** [comment]
I tested RHEL 2.4.1 with setup.properties file. Still Shibboleth IDP and CAS does not change to "Yes".

**Comment by nynymike** [comment]
Can you paste in the propreties files you used to test this?

**Comment by zamilskhan** [comment]
I have pasted the contents of the setup.properties file in the following link in pastebin. http://pastebin.com/QLGzAWqh

**Comment by nynymike** [comment]
I think I fixed this problem--due to case mismatch (SAML v Saml and CAS v. Cas). You'll need to re-run setup.py which will save the properties with the right file name, and then try loading from properties to test.

**Comment by zamilskhan** [comment]
I tested RHEL 6.5 package. still the same. But I noticed that if there is a file named "setup.properties" in the "/install/ community-edition-setup/" then the option "-f setup.properties" is not necessary. The script takes the values from the file automatically.

**Comment by tecoholic** [comment]
This bug is a serious issue in the upgradation process as the `setup.py` file parses the exported `setup.properties` and sets all these components to false.

**Comment by willow9886** [comment]
From Mike yesterday: 

> Maybe @tecoholic can dig into how this information is stored in setup.properties because when you use properties, you go into a different flow. But it should be simple enough. I don't like defaulting to installing everything. Its actually bad security.

>

**Comment by tecoholic** [comment]
I have pushed code that fixes this issue. Needs testing. Reopen if testing fails. I am testing on my end as well.

**Comment by zamilskhan** [comment]
@tecoholic Tried on centos 6.6 with new fixed setup, getting error

```
INFO   | jvm 1    | 2016/06/01 21:56:37 | INFO: Illegal access: this web application instance has been stopped already.  Could not load com.unboundid.ldap.protocol.ProtocolMessages.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
INFO   | jvm 1    | 2016/06/01 21:56:37 | java.lang.IllegalStateException
```

**Comment by mzico** [comment]
@tecoholic : Any news on this issue? Seems like making cluster is becoming harder if we can't use flag in second ( or..third ..fourth ) installation.

**Comment by tecoholic** [comment]
@mzico I will investigate and update soon.

**Comment by economike** [comment]
HI, was told to leave a comment here:

This is the error we get when running setup.py:

GLUU.[root@idp community-edition-setup]# ./setup.py -r

Use setup.py to configure your Gluu Server and to add initial data required for
oxAuth and oxTrust to start. If setup.properties is found in this folder, these
properties will automatically be used instead of the interactive setup.
Options:

    -a   Install Asimba
    -r   Install oxAuth RP
    -c   Install CAS
    -d   specify the directory where community-edition-setup is located. Defaults to '.'
    -f   specify setup.properties file
    -h   Help
    -n   No interactive prompt before install starts. Run with -f
    -N   No apache httpd server
    -s   Install the Shibboleth IDP
    -u   Update hosts file with IP address / hostname
    -w   Get the development head war files

This line:

def getOpts(argv, setupOptions):
    try:
        opts, args = getopt.getopt(argv, "acd:fhNn:suw")

Needs to change to include r flag:

opts, args = getopt.getopt(argv, "arcd:fhNn:suw")

**Comment by zamilskhan** [comment]
Tested on CentOS6.6 with Shibboleth and Asimba. Worked fine @mzico @tecoholic

**Comment by tecoholic** [comment]
@economike Thanks for pointing it out. It was fixed after the 2.4.3 release at https://github.com/GluuFederation/community-edition-setup/commit/0bc665a4ac76d867d7b4f8587d2e0abaff5f583d

@zamilskhan I am closing this issue for now then.

**Comment by mzico** [comment]
@tecoholic , @zamilskhan and @economike : I'll give a try with 2.4.3 + CentOS6.x. 
Will update you soon.

**Comment by mzico** [comment]
@tecoholic @zamilskhan and @economike : I am confirming that... it's working fine in CentOS6.x. 
Thanks for all your help, Gentlemen!
