### ISSUE TITLE
Post Installation for CASA  failed in 4.3.0

### ISSUE THREAD

**Issue by imShakil** [GluuFederation/community-edition-setup#769]
Hi

I tried to install CASA through the post-installation method. But It fails to install. 
showing this error:  ```Setup needs ports 4444,1636 are free. Exiting```
Please see the attached pictures.

![Screenshot from 2021-11-09 23-34-18](https://user-images.githubusercontent.com/20867846/140975264-2e8af470-e317-4452-af05-3f02c034baf2.png)

NB: Tested through the **TUI** based installation method and this way CASA was installed properly.

**Comment by mbaser** [comment]
Fixed

![Screenshot_2021-11-10_19-13-57](https://user-images.githubusercontent.com/6398752/141150491-28762667-ba5b-4cec-b15a-5b5a745593da.png)
