### ISSUE TITLE
Add SINGLE-VALUED defintion to ldif schema

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#787]
In `101-ox.ldif` there is no SINGLE-VALUED in attributes definitions. But in `gluu_schema.json` we use `"multivalued": true` for multi-valued attributes.
We need to make sure that we generate same single/multi-valued attributes for RDBS/LDAP.

**Comment by yurem** [comment]
According to @nynymike with LDAP, there is never any benefit to making attributes SINGLE-VALUED.

**Comment by nynymike** [comment]
And obviously now that we are supportibg RDBMS, we need to specify which data fields are multi value out of the box
