### ISSUE TITLE
Render 101-ox.ldif at runtime during setup process

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#789]
Setup generate SQL statements to create tables from `gluu_schema.json` during CE install with RDBMS. 

`101-ox.ldif` we have generate from ``gluu_schema.json``  during setup too.

**Comment by mbaser** [comment]
Implemented by https://github.com/GluuFederation/community-edition-setup/pull/790/commits/6ec6807380b023348aa15ad35afa200b17225ee7
