### ISSUE TITLE
Add new option to install into single jetty container

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#806]
Current setup version install each application into separate jetty container. We need to add new option to install all application into single `gluu` container.
Here is what we needed to implement this:
1. Use by default jetty 10.x. We can enable this by default in 4.4.0. In 4.3.3 we need to enable this only if single container install is explicitly selected in GUI or with option.
2. Instead of multiple containers create single `gluu` container
3. Merge `/etc/default/service` files.
 - In merged file we need to add all unique options specified in JAVA_OPTIONS
 - Sum each -Xms and -Xmx for merged file
4. Update apache config to use `gluu` jetty instance port

**Comment by nynymike** [comment]
Moving this to Janssen Project
