### ISSUE TITLE
Make length of UID value in RDBMS to 256 char

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#819]
It there is no problem in overall operation in Gluu Server, please increase UID value to 256 character. 
Here is the status of current 4.3.1: 
![Screenshot from 2022-03-02 10-55-27](https://user-images.githubusercontent.com/7156097/156297709-7d4ccfa8-b18c-4632-a02e-b4269484e1c8.png)

**Comment by yurem** [comment]
Why increase uid to 256? We need to try to keep fields which DB index as small as possible. According to result in screenshot above uid length is 10

**Comment by nynymike** [comment]
10 is particularly short for uid. Can this be made longer by customers if 10 is not enough?

**Comment by yurem** [comment]
This select query which determines max uid in their DB.

**Comment by yurem** [comment]
Here is current uid/pwd length:
![image](https://user-images.githubusercontent.com/6104200/156445192-ef78199b-ce15-478f-913f-0110f4712b1c.png)

**Comment by mzico** [comment]
@yurem : right, 256 is way too much but that customer is using this. If it's a special requirement ( not generic for all users ) then is it possible to increase/decrease such limit by users himself?

**Comment by yurem** [comment]
yes, with SQL it's very easy to do:
```
ALTER TABLE `jans`.`jansPerson` 
CHANGE COLUMN `uid` `uid` VARCHAR(256) NULL DEFAULT NULL ;
```
