### ISSUE TITLE
Fix gluu-server permissions

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#82]
/opt/gluu-server folder should not allow any system users to read it...

When I do an ls -l on /opt:
    drwxr-xr-x 22 root root 4096 Jan 21 11:51 gluu-server-2.4.1

This means that any unix user can see the contents... and potentially copy the entire opendj file, private keys etc.

Shouldn't it look like this:
    drwx------ 22 root root 4096 Jan 21 11:51 gluu-server-2.4.1

**Comment by willow9886** [comment]
Moved this issue to the `chroot` repo: https://github.com/GluuFederation/chroot/issues/4
