### ISSUE TITLE
Two descriptions on gluuSmtp attributes

### ISSUE THREAD

**Issue by cam-miller** [GluuFederation/community-edition-setup#87]
See https://github.com/GluuFederation/community-edition-setup/blob/master/static/opendj/101-ox.ldif lines 539 to 581.

 Causes issues with some schema parsing libraries.

**Comment by yurem** [comment]
Fixed:
https://github.com/GluuFederation/community-edition-setup/commit/5c0c4b0f786bac813643c0f4baea9097a70bb7d9
