### ISSUE TITLE
fix: few attributes from 96-eduperson.ldif are multivalued

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#870]
Attribute `eduPersonScopedAffiliation` is multi valued. How to specify this in setup to create it with proper type in SQL DB?
@mzico Can you list all multi-valued attributes from this file?

**Comment by mzico** [comment]
Attributes which _can be_ multi valued. So we have to facilitate multi value option for these attributes: 

 - departmentName
 - eduPersonAffiliation
 - eduPersonEntitlement
 - eduPersonOrcid
 - eduPersonOrgUnitDN
 - eduPersonPrimaryAffiliation
 - eduPersonPrimaryOrgUnitDN
 - eduPersonScopedAffiliation
 - telephoneNumber
 - sn
 - memberOf
 - cn
 - role

**Comment by yurem** [comment]
We need to update only edu attributes in this issues defined in `96-eduperson.ldif`
```
eduPersonAffiliation
eduPersonEntitlement
eduPersonOrcid
eduPersonOrgUnitDN
eduPersonPrimaryAffiliation
eduPersonPrimaryOrgUnitDN
eduPersonScopedAffiliation
```

**Comment by mbaser** [comment]
> Attribute `eduPersonScopedAffiliation` is multi valued. How to specify this in setup to create it with proper type in SQL DB? @mzico Can you list all multi-valued attributes from this file?

We can add those attributes to `sql_data_types.json`

**Comment by mbaser** [comment]
![image](https://user-images.githubusercontent.com/6398752/168235501-ceceec21-a43b-4bb3-a659-85c8985f019d.png)
