### ISSUE TITLE
Skip not required SQL tables creation

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#872]
We need to skip next tables creation: eduPerson, vdapcontainer, vdDirectoryView, vdlabel
Also remove oxProx outdated objectClasses and attributes which belong to these OC classes only: oxProxOp, oxProxConfiguration, oxProxClient, oxProxAccessToken

@nynymike Can you confirm that we not need tables realated to oxProx. We are trying to clean up gluu schema.

**Comment by yuriyz** [comment]
re: for all `oxProx` related things I can confirm that we don't need it. It was added many yeas ago and are not used.

**Comment by mbaser** [comment]
Implamented
