### ISSUE TITLE
cacerts location in oxTrust config template points to a broken symlink

### ISSUE THREAD

**Issue by harrdou** [GluuFederation/community-edition-setup#874]
The default cacerts location in [oxtrust-config-json](https://github.com/GluuFederation/community-edition-setup/blob/68c34f134d7fe765cd6637bd1b8770f0d83c0c36/templates/oxtrust/oxtrust-config.json#L70) points to `/usr/java/latest/jre/lib/security/cacerts` however `/usr/java/latest` is a broken symlink pointing to a non-existent OpenJDK.

The value should probably point to the Corretto truststore at `/opt/jre/jre/lib/security/cacerts`.

**Comment by mbaser** [comment]
Fixed
