### ISSUE TITLE
ObjectClasses of oxTrust JSON configuration need to review 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#889]
Currently mapped user's information isn't available in oxTrust due to Object Class declared in oxTrust JSON configuration.  

 - default install inserting `gluuCustomPerson` as personObjectClassTypes. It should add `gluuPerson`, `eduPerson` as well. 
 - default install providing null value for `personObjectClassDisplayNames`. It should add `gluuPerson`, `gluuCustomPerson` , `gluuPerson` and `eduPerson`( for eduPerson related attributes )
 
 
 A howTo doc is available, please contact me directly ( only Gluu people ).

**Comment by MohitMaliFtechiz** [comment]
this issue has been fixed 
![Screenshot from 2022-07-08 12-45-55](https://user-images.githubusercontent.com/34593983/177938165-02644400-c3da-4860-b18f-25e189150d1b.png)
![Screenshot from 2022-07-08 12-45-50](https://user-images.githubusercontent.com/34593983/177938196-d276361e-0795-4ad5-8729-2aaadb80e22c.png)

**Comment by packia7** [comment]
Thank you so much for this update. I am new to Gluu and installed latest 4.4 in two days back and blocked because of this issue.
