### ISSUE TITLE
LDAP to SQL migration script

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#894]
We would like to help our customers and community who is migrating from Gluu Server LDAP to Gluu Server MySql/Aurora. 
Let's have a script for that.

**Comment by devrimyatar** [comment]
OpenDJ  to MySQL migration script is fixed and a short documentation is provided.
See https://github.com/GluuFederation/community-edition-setup/blob/version_4.4.1/tools/ldap_to_mysql/README.md
