### ISSUE TITLE
Move shibboleth2 templates files to setup

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#9]
We should do next:
1) Remove /opt/tomcat/conf/shibboleth2 folder with files from rpm.
2) Put http://ox.gluu.org/maven/org/xdi/oxtrust-configuration/2.0.0.Final/oxtrust-configuration-2.0.0.Final.jar into /opt/dist as oxtrust-configuration.jar
3) During setup unpack oxtrust-configuration-2.0.0.Final.jar into temporary folder
4) Move shibboleth2 folder into /opt/tomcat/conf
5) Remove temporary folder

**Comment by willow9886** [comment]
@yurem is this related to https://github.com/GluuFederation/community-edition-setup/issues/72 ? We thought this might be an oxTrust issue...
