### ISSUE TITLE
CentOS7 uninstall not successful

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#90]
'Running transaction' is not completing. Screenshot
![uninstallation_failing](https://cloud.githubusercontent.com/assets/7156097/13219710/602a099c-d937-11e5-89c3-96f080f53e52.png)
 attached.

**Comment by adrian-purism** [comment]
[2/24/16, 9:18:10 PM] Adrian Alves: root@pkg-rpm2 centos7.241]# rpm -ivh rpmbuild/RPMS/x86_64/gluu-server-2.4.1-1-2.centos7.x86_64.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:gluu-server-2.4.1-1-2.centos7    ################################# [100%]
[root@pkg-rpm2 centos7.241]# rpm -e gluu-server-2.4.1-1
Checking if Gluu Server isn't running...
Your changes will be saved into /opt/gluu-server-2.4.1.rpm.saved
[root@pkg-rpm2 centos7.241]#
[2/24/16, 9:18:15 PM] Adrian Alves: i think is working now


http://repo.gluu.org/centos/testing/gluu-server-2.4.1-1-2.centos7.x86_64.rpm

**Comment by adrian-gluu** [comment]
[2/24/16, 9:18:10 PM] Adrian Alves: root@pkg-rpm2 centos7.241]# rpm -ivh rpmbuild/RPMS/x86_64/gluu-server-2.4.1-1-2.centos7.x86_64.rpm 
Preparing... ################################# [100%]
Updating / installing...
1:gluu-server-2.4.1-1-2.centos7 ################################# [100%]
[root@pkg-rpm2 centos7.241]# rpm -e gluu-server-2.4.1-1
Checking if Gluu Server isn't running...
Your changes will be saved into /opt/gluu-server-2.4.1.rpm.saved
[root@pkg-rpm2 centos7.241]#
[2/24/16, 9:18:15 PM] Adrian Alves: i think is working now

http://repo.gluu.org/centos/testing/gluu-server-2.4.1-1-2.centos7.x86_64.rpm
