### ISSUE TITLE
LDAP issue for Gluu 4.2.3 on RHEL 8

### ISSUE THREAD

**Issue by imShakil** [GluuFederation/community-edition-setup#907]
No admin user is created at the installation of Gluu Server 4.2.3 on RHEL 8. 
Thus `oxtrust` login is failed.

Please see attached setup log, where some LDAP operations failed at the beginning:
[setup.log](https://github.com/GluuFederation/community-edition-setup/files/9420100/setup.log)

Ref Ticket: https://support.gluu.org/10736

## How to Replicate:

- Just install Gluu 4.2.3 on RHEL 8
- Try to login using `admin` credential

**Comment by devrimyatar** [comment]
rpm was rebuilded https://repo.gluu.org/rhel/8/gluu-server-4.2.3.1-rhel8.x86_64.rpm
