### ISSUE TITLE
Setup should configure tomcat, ldap, apache users ulimit

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#91]
For me info please contact @zamilskhan He planned to add documentation page based on conversation in support chat

**Comment by zamilskhan** [comment]
Currently, there is so specific requirement set for separate components. A general file descriptor requirement with how-to is given.

https://www.gluu.org/docs/admin-guide/deployment/#operating-system-requirement

**Comment by yurem** [comment]
We need to add commands to setup to configure: jetty, ldap, root users inside chroot

**Comment by yurem** [comment]
Thank you for fix
