### ISSUE TITLE
feat: Install CB/Spanner DB libraries from separated archive

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#937]
In recent war files there is no CB/Spanner DB drivers. We removed them to reduce number of security issues. As result we should update setup to deploy required jar files into each jetty container during install if admin selected to install CE with CB or Spanner.

For example to add CB drivers to oxAuth setup should do next:
1. Download and unpack `https://maven.gluu.org/maven/org/gluu/gluu-orm-couchbase-libs/4.5.0-SNAPSHOT/gluu-orm-couchbase-libs-4.5.0-SNAPSHOT-distribution.zip` into `/opt/gluu/jetty/oxauth/custom/libs/couchbase`
2. Update `/opt/gluu/jetty/oxauth/webapps/oxauth.xml`. Setup should append `<Set name="extraClasspath">`. It should add for example:
`./custom/libs/couchbase/core-io-2.3.0.jar,./custom/libs/couchbase/java-client-3.3.0.jar,./custom/libs/couchbase/reactive-streams-1.0.3.jar,./custom/libs/couchbase/reactor-core-3.4.17.jar`
3. The same steps setup should do for all other jetty container as well.

For Spanner link to archive is next: `https://maven.gluu.org/maven/org/gluu/gluu-orm-spanner-libs/4.5.0-SNAPSHOT/gluu-orm-spanner-libs-4.5.0-SNAPSHOT-distribution.zip`. The steps for it are the same. The only one update is the folder name for spanner DB driver. We should use `/opt/gluu/jetty/oxauth/custom/libs/spanner`

After unpacking `gluu-orm-couchbase-libs-4.5.0-SNAPSHOT-distribution.zip` or `gluu-orm-spanner-libs-4.5.0-SNAPSHOT-distribution.zip` setup should check if there are same files in war files. Duplicate files should be removed from custom libs folders in order to avoid conflicts. In other words libraries from war files have higher precedence than files from DB driver archives.

**Comment by devrimyatar** [comment]
@yurem Since spanner and cb libraries are used in many war files, instead of extracting libraries to custom lib dir for each jetty service, can we extrat rdbm files to `/opt/gluu/jetty/common/spanner` and `/opt/gluu/jetty/common/cb`, and use full path in `extraClasspath`? For example
```
<Set name="extraClasspath">/opt/gluu/jetty/common/spanner/google-http-client-1.42.2.jar, /opt/gluu/jetty/common/spanner/google-http-client-1.42.2.jar/proto-google-cloud-spanner-admin-instance-v1-6.31.2.jar ...
</Set>
```

**Comment by yurem** [comment]
I like this idea

> @yurem Since spanner and cb libraries are used in many war files, instead of extracting libraries to custom lib dir for each jetty service, can we extrat rdbm files to `/opt/gluu/jetty/common/spanner` and `/opt/gluu/jetty/common/cb`, and use full path in `extraClasspath`? For example
> 
> ```
> <Set name="extraClasspath">/opt/gluu/jetty/common/spanner/google-http-client-1.42.2.jar, /opt/gluu/jetty/common/spanner/google-http-client-1.42.2.jar/proto-google-cloud-spanner-admin-instance-v1-6.31.2.jar ...
> </Set>
> ```
