### ISSUE TITLE
Error in 2.4.2 Setup.py

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/community-edition-setup#94]
Ryan Kinzy: It seems like there is an issue in setup.py script:
"/opt/gluu-server-2.4.2/install/community-edition-setup/setup.py"
Method a bit weird by itself but also it does not take into consideration Ubuntu where apache service is called apache2 rather than httpd which cause failure during installation:
Error:
Traceback (most recent call last):
 File "./setup.py", line 1756, in <module>
   installObject.apache_version = installObject.determineApacheVersion()
 File "./setup.py", line 635, in determineApacheVersion
   apache_version = p.stdout.read().strip().split(' ')[2].split('/')[1]
IndexError: list index out of range

[3:47] 
method is 
   def determineApacheVersion(self):
       # httpd -v
       # Server version: Apache/2.2.15 (Unix)  /etc/redhat-release  CentOS release 6.7 (Final)
       # OR
       # Server version: Apache/2.4.6 (CentOS) /etc/redhat-release  CentOS Linux release 7.1.1503 (Core)
       cmd = "httpd -v | egrep '^Server version'"
       PIPE = subprocess.PIPE
       p = subprocess.Popen(cmd, shell=True, stdin=PIPE, stdout=PIPE, stderr=subprocess.STDOUT, close_fds=True, cwd=None)
       apache_version = p.stdout.read().strip().split(' ')[2].split('/')[1]
       if re.match(r'2\.4\..*', apache_version):
           return "2.4"
           
       return "2.2"

[3:47] 
to work under ubuntu    cmd = "httpd -v | egrep '^Server version'" should be replaced with    cmd = "apache2 -v | egrep '^Server version'"
[16:05:01] Ryan Kinzy: it looks like they got through it, but they notified me of that issue

Ryan Kinzy: here's the install doc:
[16:07:51] Ryan Kinzy:  https://login.skype.com/login/sso?go=xmmfallback?pic=0-eus-d3-fa714bf4b5a62e8fa073a0ebd8926473
[16:13:49] Ryan Kinzy: install was handled by commenting out apache version check in python scrypt and this one is not handled http://storage4.static.itmages.com/i/16/0225/h_1456413256_1314043_a1eaf8ed5a.png (51KB)

**Comment by nynymike** [comment]
Fixed [927c88b](https://github.com/GluuFederation/community-edition-setup/commit/927c88ba265e6c4c41be406a0a0522aa2ae99ffa)

**Comment by dmogn** [comment]
I have repeated a same bag (Ubuntu 14.04.4):

sirius@ksvb:~$ sudo dpkg -i Downloads/gluu-server-2.4.2_1-BETA3_amd64.deb 
Selecting previously unselected package gluu-server-2.4.2.
(Reading database ... 254669 files and directories currently installed.)
Preparing to unpack .../gluu-server-2.4.2_1-BETA3_amd64.deb ...
Unpacking gluu-server-2.4.2 (1-BETA3) ...
Setting up gluu-server-2.4.2 (1-BETA3) ...
Processing triggers for ureadahead (0.100.0-16) ...

sirius@ksvb:~$ sudo service gluu-server-2.4.2 login
gluu-server-2.4.2 is running...
logging in...
Welcome to the Gluu Server!
GLUU.root@localhost:~# cd /install/community-edition-setup/
GLUU.root@localhost:/install/community-edition-setup# ./setup.py 
Traceback (most recent call last):
  File "./setup.py", line 1756, in <module>
    installObject.apache_version = installObject.determineApacheVersion()
  File "./setup.py", line 635, in determineApacheVersion
    apache_version = p.stdout.read().strip().split(' ')[2].split('/')[1]
IndexError: list index out of range
GLUU.root@localhost:/install/community-edition-setup#
