### ISSUE TITLE
Incorrect JDBC driver class in SAML IDP  [postgresql]

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/community-edition-setup#946]
After installation of Gluu CE 4.5, SAML IDP does not return attributes as described in [this related issue](https://github.com/GluuFederation/oxShibboleth/issues/155). 
The cause of this is during installation, the wrong JDBC driver class is specified in the file `/opt/shibboleth-idp/conf/datasources.properties`.
The property `idp.attribute.resolver.datasource.driverClass` has value `com.pgsql.jdbc.Driver` instead of `org.postgresql.Driver`. 

Also the property `idp.attribute.resolver.datasource.jdbcUrl` has the wrong value. It is currently prefixed with `jdbc:pgsql` instead of `jdbc:postgresql`.

**Comment by uprightech** [comment]
Unfortunately this isn't working. 
This results in the driverClass having the value  `com.postgresql.jdbc.Driver` instead of `org.postgresql.Driver`. 
Note the `com` instead of `org` at the start of the driverClass and the extra `jdbc` right after `postgresql` which shouldn't figure there.

**Comment by devrimyatar** [comment]
This time, it should be good
![image](https://user-images.githubusercontent.com/6398752/204597393-dc23924e-6cd7-4508-b1f2-cdc797aa8ac9.png)

**Comment by uprightech** [comment]
One last thing again. The `jdbc` suffix after `postgresql`  must be removed. So it is `org.postgresql.Driver` not `org.postgresql.jdbc.Driver`. This is only on postgresql.
