### ISSUE TITLE
Gluu radius post installation failed when the backend is spanner.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/community-edition-setup#961]
### Describe the issue 

Gluu radius post installation failed when the backend is spanner.

### How to Reproduce

1  Install Gluu-server with minimum config.
2. Run setup.py again 
3. Select Gluu Radius and run the setup.

### Actual behaviour 
 
Post installation failed for Gluu-radius
 
### Envrionment

Gluu Server 4.5 + spanner

Ubuntu 20.04

### Error logs
```
 09:42:49 01/03/23 Traceback (most recent call last):
  File "./setup.py", line 417, in do_installation
    install_services()
  File "./setup.py", line 357, in install_services
    radiusInstaller.install_gluu_radius()
  File "/install/community-edition-setup/setup_app/installers/radius.py", line 107, in install_gluu_radius
    base.current_app.RDBMInstaller.create_tables([schema_json_fn])
  File "/install/community-edition-setup/setup_app/installers/rdbm.py", line 178, in create_tables
    alter_table_sql_cmd = 'ALTER TABLE %s{}%s ADD %s{};' % (self.qchar, self.qchar, column_add)
AttributeError: 'RDBMInstaller' object has no attribute 'qchar'
```

**Comment by devrimyatar** [comment]
Fixed in https://github.com/GluuFederation/community-edition-setup/commit/2d55a9dd3fc1379137ac2e414e95d5c35d13ed0b
