### ISSUE TITLE
feat: configure password for passwurd keystore file

### ISSUE THREAD

**Issue by SafinWasi** [GluuFederation/community-edition-setup#979]
The keystore for the passwurd API (/etc/certs/passwurdAKeystore.pkcs12) should have a non-default password. One of the following:
- Allow user to define during install time with a commandline option
- Set same password as oxTrust admin

**Comment by maduvena** [comment]
1. Create a file in `/etc/certs/scan_creds.json` to store the keystore path and password (encrypted using the salt). 
Contents as follows:
```
{keystore_path:”….”, keystore_password:”...”}
```
2. The script shoud populate the path and password on initialization
